### ISSUE TITLE
"GPR limit exceeded - shader requires 125 registers" from r600_shader.c.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#703] opened 2015-04-15 12:24 UTC
Enabldur send me a mail. He get's a lot of console spam looking like this during normal play:

    EE r600_shader.c:2525 r600_shader_from_tgsi - GPR limit exceeded - shader requires 125 registers
    EE r600_shader.c:158 r600_pipe_shader_create - translation from TGSI failed !
    EE r600_state_common.c:761 r600_shader_select - Failed to build shader variant (type=0) -12

Apparently the error is not logged to `daemon.log` but is printed to the console.

> I'm on ArchLinux
> Unvanquished 0.38.0 Linux x86_64 Apr  7 2015
> 
> lscpu:
> Architecture:          x86_64
> CPU op-mode(s):        32-bit, 64-bit
> Byte Order:            Little Endian
> CPU(s):                6
> Model name:            AMD Phenom(tm) II X6 1090T Processor
> 
> lspci:
> 07:00.0 VGA compatible controller: Advanced Micro Devices, Inc.
> [AMD/ATI] Cypress XT [Radeon HD 5870]
> OpenSource drivers.

Not sure if this is a bug or really just bad verbosity about an unsupported feature. @gimhael, do you know the meaning of this?

**Comment by Amanieu** [comment] 2015-04-15 14:49
This error is printed directly to stderr by the OpenGL driver. It is not in daemon.log because it does not go through our logging functions.

**Comment by Kangz** [comment] 2015-04-20 18:35
This is a duplicate of #701 keeping for now as it has different info.

**Comment by gimhael** [comment] 2015-05-02 14:56
This should be fixed by commit ed8ca2cee90a277a5308c2bf898b1498bff1ec52.

**Closed by gimhael** 2015-05-02 14:56 UTC
Labels: A-Renderer
