### ISSUE TITLE
G_SanitiseString() in sg_cmds.cpp seems to not filter ^P###o color codes

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#770] opened 2015-07-12 03:52 UTC
Hi, the [wiki says](https://wiki.unvanquished.net/index.php?title=Colours) we can use extended color codes like `^P123o`, but [I read in `sg_cmds.cpp`](https://github.com/Unvanquished/Unvanquished/blob/dca6c01f3ffa4a441ea9678f9300dc9f943075f5/src/gamelogic/sgame/sg_cmds.cpp#L52) that `G_SanitiseString()` only skips two characters:

```c
		if ( Q_IsColorString( in ) )
		{
			in += 2; // skip color code
			continue;
		}
```

**Comment by DolceTriade** [comment] 2015-07-12 05:02
Only ^P would be the color code, which are the two characters skipped.

**Comment by DolceTriade** [comment] 2015-07-19 21:48
Working as intended then?

**Comment by illwieckz** [comment] 2015-08-04 14:32
OK, these RGB color codes are not rendered in-game:

![RGB failure](https://dl.dropboxusercontent.com/u/48965095/unvanquished_2015-08-05_002655_000.jpg)

They are not rendered in console:

```
Die: 6 1 MOD_LEVEL0_BITE: [bot]900o Soizic killed [bot]009o Baudry              
Die: 2 5 MOD_MACHINEGUN: [bot]009o Audran killed [bot]900o Nolwen 
```

They are not filtered in logs:

```
  0:03 ClientConnect: 5 [127.0.0.1] (XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX) "[bot]900o Nolwen" "^9[bot]^P900o Nolwen" [BOT]
  0:03 ClientConnect: 6 [127.0.0.1] (XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX) "[bot]900o Soizic" "^9[bot]^P900o Soizic" [BOT]
  0:23 Die: 6 3 MOD_LEVEL0_BITE 5 1: [bot]900o Soizic killed [bot]009o Alaric; [bot]900o Nolwen assisted
  0:30 Die: 5 3 MOD_LEVEL0_BITE 6 1: [bot]900o Nolwen killed [bot]009o Alaric; [bot]900o Soizic assisted
```

So I suggest to just drop these RGB codes and use instead the Xonotic RGB color codes Melanosuchus is importing to Daemon.

**Comment by illwieckz** [comment] 2015-08-04 14:35
It seems the only place where these codes were handled was in the third-party tool [xqf](http://xqf.github.io)… :stuck_out_tongue:

**Comment by mbasaglia** [comment] 2015-08-09 11:12
Just a few notes based on what I've seen while working on colors:
* <code>^P...o</code> wasn't parsed anywhere
* <code>^*</code> was parsed only in some places (now that should be fixed in my branch)
* <code>^;</code> and <code>^:</code> are always the same, not sure why the wiki says otherwise
* There are a few characters that are parsed as valid codes even if they shouldn't

**Comment by mbasaglia** [comment] 2015-10-24 12:57
I think this issue has been deprecated by my string refactoring.

**Comment by Kangz** [comment] 2015-10-24 17:27
Good catch, closing.

**Closed by Kangz** 2015-10-24 17:27 UTC
Labels: A-UI, T-Cleanup
