### ISSUE TITLE
lower FPS in 0.37

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#657] opened 2015-03-07 18:22 UTC
I've been experiencing lower FPS in the 0.37 release and I've heard from others that they have as well.

Normally I'm pegged at 60fps (driver limited, can't turn off vsync). With this release I've been dropping to 30fps.

Here's an example screenshot of an area/effect where this happens, however it also happened in a busy game yesterday with no specific effects.

http://postimg.org/image/6ady3e1jb/

glxinfo:
http://pastebin.com/Xaz13mUF

**Comment by Kangz** [comment] 2015-03-08 00:21
Did you build from sources? if yes then compile with optimizations (Release or RelWithDebInfo).
I'll check if I can repro with optimizations though.

**Comment by overvolting** [comment] 2015-03-08 00:25
This is from the debian package.

**Comment by Viech** [comment] 2015-03-08 15:17
Can you check whether you're CPU limited? Also, maybe you framerate dropped from slightly above to slightly below 60 fps and vsync is responsible for the additional performance loss?

**Comment by overvolting** [comment] 2015-03-08 23:41
vsync is hardcoded to 60 by the driver. It's never switched to 30 before under any condition.

How do I check if I'm CPU limited?

**Comment by Amanieu** [comment] 2015-03-09 05:04
Set r_swapInterval to 0 to disable vsync

**Comment by Viech** [comment] 2015-03-09 22:07
If one of your CPU cores runs an Unvanquished thread at high load it's possible that load peaks are responsible for the FPS drops. This is confirmed for the outside area on chasm, as the snow particles stress the CPU a lot since the current alpha (above 70% on an i7 for me).

**Comment by DolceTriade** [comment] 2015-03-09 22:47
Also if you're on linux, you might need to set vblank_mode=0 if you use mesa.

**Comment by overvolting** [comment] 2015-03-12 00:52
On chasm, using top, one core was at 60% until with unvanquished and another was 43% util with nacl_helper. Doesn't look like CPU maxed out.

Yes I'm having the particle slowdown, but as indicated in the first post, this happens in games on old maps like utcs with no particle sources except players.

**Comment by Kangz** [comment] 2015-03-21 04:34
@overvolting  c517ba0 should help fix that, you can try it on the for-0.38.0 branch, you'll need to add -set vm.cgame.type 2 or 3 to have it run. If it fixes all the slow downs then it is great, otherwise can you give me some other repro steps?

**Comment by Viech** [comment] 2015-04-11 17:37
@overvolting are your issues fixed on Alpha 38?

**Comment by Kangz** [comment] 2015-04-11 20:51
This should have been fixed by the change I mentioned, I was more concerned about the UTCS perf he mentioned.

**Comment by Viech** [comment] 2015-04-27 10:53
@overvolting we marked this issue [critical](https://forums.unvanquished.net/viewtopic.php?f=4&t=1816). Please report back with your performance on Alpha 38.

**Comment by overvolting** [comment] 2015-05-02 19:19
General FPS average performance in 0.38 is slightly better than 0.37 but still much worse than 0.36.
On chasm for example i used to experience no fps drop in the snowy area, in 0.37 it became a slide show, in 0.38 it's a slightly faster slide show.

The other issue of frequent short freezes #705 is new to 0.38.

**Comment by overvolting** [comment] 2015-05-02 19:23
on chasm:
 %CPU %MEM     TIME+ COMMAND                                              
 79.8  4.1   7:28.18 daemon                                               
 34.7  0.3   3:09.98 nacl_helper_boo

**Comment by Viech** [comment] 2015-05-03 19:08
So it appears that particles under NaCl are still rather expensive. @Kangz or @gimhael do you see more potential to improve performane?

**Comment by Kangz** [comment] 2015-05-03 19:18
I cannot repro on my laptop; if you give a perf record I'll be able to investigate more.
Also be sure to NOT compile in Debug but in RelWithDebInfo or Release

**Comment by Viech** [comment] 2016-11-10 13:48
Closed as outdated: No input for over a year.

**Closed by Viech** 2016-11-10 13:48 UTC
Labels: T-Performance
