### ISSUE TITLE
using an old version of the game fails ungracefully

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#554] opened 2015-02-04 01:23 UTC
connecting with 0.35 to a 0.36 server for example leads new people to think the game doesn't work when really they need to update their version. You should give them a very easy to understand message.

**Comment by DolceTriade** [comment] 2015-02-04 01:30
+1. In the works.

**Comment by Viech** [comment] 2015-02-04 14:16
This is a duplicate of #405.

**Closed by Viech** 2015-02-04 14:16 UTC
