### ISSUE TITLE
Game overlays broken in 0.42 : health shown top, red screen, chat input invisible

### ISSUE THREAD

**Issue by guillaume-uH57J9** [Unvanquished/Unvanquished#791] opened 2015-08-10 12:58 UTC
Hi,

I have noticed odd behavior with the overlays in unvanquished 0.42, using a Intel HD Haswell graphics card, open-source drivers, Linux. 

The issues seemed to appear somewhat randomly, and changed/worsened at each start/game. 
1. Chat overlays : no text visible while typing, the message is only visible on top after it's sent. 
2. Health overlay : the overlay is not well positioned in the bottom left. It sometime has a small position offset, other time it moved completely top left.
3. Screen (almost) completely red

My system details: 

unvanquished 0.42 (from universal zip)
Software : Debian GNU/Linux testing ; Linux 4.0.0 ; mesa 10.6.3 ; libdrm 2.4.62
Graphics:
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.3

Notes: 

That issue did not occurs when running previous versions on the same machine. 
Another player reported the same issue on Windows 10 during yesterday's game.

**Comment by guillaume-uH57J9** [comment] 2015-08-10 13:02
Screenshot of the red screen issue : http://pix.toile-libre.org/upload/original/1439211716.png

Also, note these are  is an in-game issues. It

**Comment by guillaume-uH57J9** [comment] 2015-08-10 13:11
I backed up autogen.cfg between starts. It was automatically modified, here is the diff:

```
--- autogen.cfg.a	2015-08-10 15:06:18.505229340 +0200
+++ autogen.cfg	2015-08-10 15:08:17.567765919 +0200
@@ -1,5 +1,5 @@
 // generated by Unvanquished, do not modify
 seta language fr
-seta r_customwidth 1920
 seta r_customheight 1080
+seta r_customwidth 1920
 seta audio.al.device ""
```

When manually undoing this change, the red screen temporarily goes away.

**Comment by Kangz** [comment] 2015-08-10 15:25
Issue number 3 has been resolved, I'm not sure about 1 and 2

**Comment by DolceTriade** [comment] 2015-08-10 16:40
THer are issues with element positioning in the HUD. Try using /reloadHud to make them go away instead as a workaruond until I track down the root cause.

**Comment by guillaume-uH57J9** [comment] 2015-08-11 20:10
/reloadHud seems to work. The red screen did not immediately go away, but it did on the next game/start.

**Comment by DolceTriade** [comment] 2015-08-11 21:05
This stuff should be fixed with new assets and a new cgame.

**Closed by DolceTriade** 2015-08-11 21:05 UTC
