### ISSUE TITLE
Prediction errors on edges of buildables

### ISSUE THREAD

**Issue by enneract** [Unvanquished/Unvanquished#425] opened 2014-08-24 20:08 UTC
Colliding with buildables often results in visible prediction errors. This is probably a consequence of using the bounding box sent by server (crapped through entityState_t's "solid" field at low precision) instead of the accurate values from config files.

**Comment by slipher** [comment] 2021-07-18 04:23
A curious feature of the bug is that it seemingly relates to closeness to the edge as a percentage of buildable size, rather than actually being on the edge. If I make a 10x scale medistation, then I get prediction errors without even being close to the edge of the bounding box. (You need to go all the way over the red part to fall down.)

![unvanquished_2021-07-17_224454_000](https://user-images.githubusercontent.com/7809431/126055608-8a73bbdd-61e0-406d-b09f-d4b8742e6a3c.jpg)

**Comment by slipher** [comment] 2021-07-29 19:42
Disregard previous comment. The bug with the giant medistation was caused by code that doesn't work with bboxes with maxs larger than 255.

Another thing I've found is that the bug cannot be reproduced via saveviewpos/setviewpos. You don't get the prediction errors after restoring the saved position. Maybe there is some sort of feedback loop with deltas to produce the bug.

**Comment by illwieckz** [comment] 2021-08-02 20:18
> You don't get the prediction errors after restoring the saved position. Maybe there is some sort of feedback loop with deltas to produce the bug.

I noticed that when restoring saved position, the spectator does not suffer from any move which seems to be some leftover for accumulated speed. Maybe the non-spectator also suffer from such accumulated speed leftover?

**Comment by necessarily-equal** [comment] 2021-08-02 22:14
@illwieckz if you want to test this, you may want to test https://github.com/necessarily-equal/Unvanquished/commit/15023cf9ef2640469111093004c5e03e004f2a17 that fixes the leftover speed. For some reason, because of a GitHub bug, I can't make a PR for it but well. You may also want to check @slipher's PR, #1471.

**Comment by illwieckz** [comment] 2021-08-02 22:38
@necessarily-equal does this link work for you:
https://github.com/Unvanquished/Unvanquished/compare/master...necessarily-equal:more-fixes

**Comment by necessarily-equal** [comment] 2021-08-03 08:04
Ah, yes it works. I think I missed the "s" at the end when copying the link. Though GitHub wasn't explicit about the error either.

**Comment by slipher** [comment] 2021-08-20 22:23
Fixed by #1471.

**Closed by slipher** 2021-08-20 22:23 UTC
Labels: A-Gamelogic, T-Bug
