### ISSUE TITLE
unvanquish doesn't play sound & crash if some other app was playing sound when unv was started.

### ISSUE THREAD

**Issue by ckol** [Unvanquished/Unvanquished#724] opened 2015-05-14 22:36 UTC
Bug exists since unv 0.3xsomething.
Platform: Arch Linux 64bit, latest updates.
Desktop: xfce4

When some application (no matter if Audacity is playing something or VLC or Firefox is showing a YouTube Video) is playing Sound through a normal ALSA setup.
And if then unvanquished is started, unvanquished works, but doesn't play any sound.
The other application(s) keep playing audio.

When I want to leave unvanquished (by selecting Quit) it freezes.
I have to leave X with CTRL-ALT-Fx to a console and kill daemon as root.

unv 0.3x<~0.37 was just terminated.
Starting with unv 0.37(or so) it takes an additional ~30s or so until unv gets killed
and cleaned up from X. It seems like it has to detect the kill first, showing an old
fashioned Message Box with: "Error: Forcing shutdown from signal: Terminated."

Reproducable: always.

**Comment by Kangz** [comment] 2015-05-15 00:50
That sounds related to OpenAL, I'll see with KittyCat if it is a known problem

**Comment by Kangz** [comment] 2015-05-15 01:06
KittyCat's comments:

    [15|03:05:17] <+KittyCat> I've heard similar problems before, yeah. usually caused by mixing sound systems (e.g. one app using alsa, another using puleaudio or oss)
    [15|03:08:36] <+KittyCat> openal on linux will normally attempt to use pulseaudio first if it's installed, so if another app is explicitly told to use alsa with openal trying to use pulseaudio, that could be the problem
    [15|03:12:48] <+KittyCat> pulseaudio tries to take ownership of the audio device
    [15|03:13:33] <+KittyCat> usually, with pulseaudio installed, alsa is configured to use pulseaudio (so it goes alsa_plugin->pulseaudio->alsa_hardware), but people sometimes disable that
    [15|03:13:59] <+KittyCat> or they may be missing the plugin

It seems the a configuration problem of ALSA / PulseAudio could be the problem, how is it configured on your system?

**Comment by ckol** [comment] 2015-05-15 02:02
Yes, my system is using ALSA as well as Pulseaudio (as well as Jack, but that was not active at the time of bug).
I would not worry if just sound stops to work.
Unv could issue a clear warning, but not crash on quit.

**Comment by illwieckz** [comment] 2017-10-23 05:37
This bug i the same issue than #1031 “_The game does not start if there is no sound card at all_”. By the way, even if the Dæmon engine is known to not be able to launch if no sound card is available, if you have PulseAudio installed but Audacity/VLC/Firefox/Flash Player is taking ownership of the alsa card, it's either a bug in these softwares, either a bug in your distro, either an user misconfiguration. If PulseAudio is installed but applications workaround it, it's a bug in the setup itself.

Dæmon must be able to start without sound card available, but it's not Dæmon's fault if a media player or a web browser requests soundcard exclusivity to alsa on a PulseAudio setup, bypassing PulseAudio itself which is precisely a software made to multiplex multiple audio stream on a single soundcard without having each app locking others. So I close this bug and the issue will be treated in #1031.

**Closed by illwieckz** 2017-10-23 05:37 UTC
Labels: A-Audio, T-Bug
