### ISSUE TITLE
New nickname colour system doesn't report properly to gametracker

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#859] opened 2015-12-19 19:24 UTC
When I join with my coloured nick, this is how it looks on our GameTracker page:
http://www.gametracker.com/server_info/188.226.246.237:27960/
![screenshot](https://cloud.githubusercontent.com/assets/13281185/11914899/0346df36-a686-11e5-96eb-156b37cd01f0.png)

**Comment by Viech** [comment] 2015-12-19 19:26
Isn't that the problem of the tracker not parsing the name string properly? Or do you want it to be stripped to an uncolored string before being send out?

**Comment by cu-kai** [comment] 2015-12-19 19:28
I assume that's how Tremulous does it (and how Unv did it before)

**Comment by mbasaglia** [comment] 2015-12-19 20:20
It shows up as a Quake 3 server, aren't things bound to break if it isn't an actual quake 3 server?

Anyway, I'd guess it uses getstatus, which is supposed to stuff as they appear on the server, so it seems something they should fix on their side (that name is completely messed up, if they parsed the status properly is should show up with the ^color^codes).

Does the in-game server list show anything funny if a server has the new colors on its name? That should be from getstatus too (or getinfo).

**Comment by Viech** [comment] 2016-06-24 10:31
I think this is nothing we can fix as we require `getstatus` to support our new color system. If an external application considers us to be Quake 3, things may break of course. If anything we could make `getstatus` a legacy-support command and switch to a new command that supports colors. I'd wait for some more input on this but I'm tending towards closing the issue.

**Comment by illwieckz** [comment] 2016-10-22 23:25
Having the legacy `getstatus` response retrocompatible would be nice, it means easy retrocompatibility with tons of third party stuff out there, could be nice to have a modern alternative for _those who knows™_. I think the code already have a color code filter (for logging purpose), if there is a legacy `getstatus` call and a new one for newer stuff, I guess all special stuff can be dropped for the legacy one.

@mbasaglia do you know if there is similar issues with server names?

**Comment by mbasaglia** [comment] 2016-10-23 07:46
This would only result into proliferation of commands and responses.
Unvanquished currently has several color formats:
* Standard ^0 - ^7
* Extended ^8 - ^p
* Darkplaces-like ^xfff
* Full RBG ^#ffffff
Different tools would support different subsets.

I don't think we need to be backward compatible with tools intended for old Quake games, because even if they parsed colors correctly they might break in other ways.

**Comment by DolceTriade** [comment] 2016-10-23 08:08
Agree with mbasaglia.

**Comment by cu-kai** [comment] 2016-11-10 12:21
Our server name appears fine on our gametracker. I have a feeling gametracker just doesn't like the new Darkplaces/RGB colour codes, as the standard/extended ones don't cause any issues.

**Comment by Viech** [comment] 2016-12-11 15:05
Closing since
1. the issue is not quite in our power to fix and
2. the workaround of maintaining backwards compatibility with `getstatus` was turned down by @mbasaglia and @DolceTriade.

**Closed by Viech** 2016-12-11 15:05 UTC
Labels: A-Server, T-Question
