### ISSUE TITLE
Segfault after "primus: fatal: failed to acquire direct rendering context".

### ISSUE THREAD

**Issue by Xodetaetl** [Unvanquished/Unvanquished#712] opened 2015-04-30 09:46 UTC
Tried Unvanquished for the first time with 0.38.0, crash at launch, [log here](http://hastebin.com/unuqeqelof.vbs).

Using primusrun with discreet Geforce GTX 660M, proprietary drivers v331.113
Looks like a problem with primus ?

**Comment by Viech** [comment] 2015-04-30 11:33
Do other OpenGL games run with your primus setup?

**Comment by Xodetaetl** [comment] 2015-04-30 12:05
Yes, I just tried Tremulous, Warsow, Open Dungeons, Open Arena, Mutant Factions.
Only AssaultCube has a segfault with primus (but works fine on the Intel chipset), with this error message: `Segmentation fault (core dumped). To run AssaultCube, please ensure X11 libraries are installed.`

**Comment by Viech** [comment] 2015-04-30 13:22
Thank you, so this seems to be a bug on our end indeed. Did you compile from source? If yes, can you provide a backtrace, too? Does `optirun` work? Otherwise I'd refer this one to either @gimhael or @Kangz. Also if I remember correctly @DolceTriade had a primus-capable GPU.

Since this is a common setup and the bug is preventing client execution, I'm adding it to the state of emergency milestone.

**Comment by gavlig** [comment] 2015-04-30 13:32
i use primusrun for games. It used to work for unv, but i'll check again later today.

**Comment by Xodetaetl** [comment] 2015-04-30 13:36
Ah, it's working with `optirun`! :)
I used the universal zip, didn't compile it.

**Comment by Amanieu** [comment] 2015-04-30 13:49
Does the game work if you run it without primus, running only on the Intel
GPU?

**Comment by Xodetaetl** [comment] 2015-04-30 13:52
No, it says 
```
...WARNING: OpenGL too old 
 Error: Couldn't load a renderer```

**Comment by gavlig** [comment] 2015-04-30 13:55
if our universal zip has x86 bin and you are trying to launch it in x86_64 os and not all lib32 packages were installed for optirun this could happen

**Comment by Xodetaetl** [comment] 2015-04-30 13:58
No there's only a 64-bit linux binary in your universal archive

**Comment by Viech** [comment] 2015-04-30 13:58
Also someone on #optirun-dev proposed to build the latest primus [from source](https://github.com/amonakov/primus).

**Comment by DolceTriade** [comment] 2015-04-30 22:28
Unv works fine with primusrun for me, including the universal zip on Arch Linux.

**Comment by Viech** [comment] 2015-05-01 10:36
@amonakov said in amonakov/primus#168 that the cause is that we include "an incompatible version of `libglapi.so`" in the release.

**Comment by amonakov** [comment] 2015-05-01 12:00
I've downloaded linux64.zip and looked what's there. Apart from libglapi, libdrm should not be shipped either. Overall the collection of bundled libraries looks ... odd — why is libX11 there for instance?

**Comment by DolceTriade** [comment] 2015-05-01 21:37
Those libs were assembled using a highly specific process: All libraries were copied from the output of ```ldd daemon``` and then libraries were systematically deleted until Unv launched.

**Comment by Xodetaetl** [comment] 2015-05-02 08:29
By the way, it does works by removing the bundle libglapi.
I recommend you follow [these instructions](https://www.reddit.com/r/gamedev/comments/291rth/how_to_deploy_a_game_on_linux/cii6gm8) – by Sulix who ported many games to Linux – to build your universal zip.

**Comment by Viech** [comment] 2015-05-02 11:39
@Xodetaetl thank you for the reference! @DolceTriade could you follow these instructions for the coming release? This may get rid of additional bugs and crashes not yet reported, too.

**Comment by Xodetaetl** [comment] 2015-05-02 12:12
You're welcome.
Contrary to the post I linked above though, I'd still advise to provide the libs returned by `ldd` and not just objdump. But get rid at least of the libgcc_s and GL libs, as well as the PulseAudio and Alsa libs after getting a build of SDL that doesn't require them. 
There's a list of base libraries in the [LBS specs](https://refspecs.linuxfoundation.org/LSB_1.3.0/gLSB/gLSB.txt), too. I don't know how safe it is to not provide any of these.

**Comment by DolceTriade** [comment] 2015-05-03 10:13
Thanks for the link. I'll see what I can rework for the universal zip.

**Comment by DolceTriade** [comment] 2015-05-03 12:45
https://unvanquished.net/~modi/linux64.zip

Requires the newest glsl shaders however.

**Comment by amonakov** [comment] 2015-05-03 13:34
Now the `daemon` executable embeds copies of several libraries, libX11 included, and exposes dynamic symbols of those libraries (so the external libraries will link against symbols in the executable, not in their dependencies).

I'm curious how you produced this executable (did you deliberately use `-rdynamic`?), and how the decision to statically link libX11, of all things, was arrived to.

**Comment by DolceTriade** [comment] 2015-05-03 19:43
That one was my fault. In my build system, I had it pick the static libs of everything it could, but I didn't really check all the libs it selected. As for -rdynamic, I think CMake adds it by default.

**Comment by DolceTriade** [comment] 2015-05-05 22:32
Closing because root cause has been identified and will be fixed in the next release.

**Closed by DolceTriade** 2015-05-05 22:32 UTC
Labels: A-Distribution, A-Renderer, T-Bug
