### ISSUE TITLE
High CPU load in main menu

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#359] opened 2014-07-20 19:05 UTC
When idling in the main menu or downloading a missing pk3, I find that one of my CPU cores is running at 100% load using an Alpha 29 client or current master (4f0a365) on Arch Linux 64 bit. My CPU is an overclocked Intel i7-3770.

**Comment by Viech** [comment] 2015-01-01 23:12
The main menu still runs a single CPU core at 100%.

**Comment by Amanieu** [comment] 2015-02-04 17:15
Does this only happen on debug builds or on release builds as well? Debug builds are known to be very slow at the moment, but that is a separate issue.

**Comment by Kangz** [comment] 2015-02-04 21:49
Do we throttle the FPS when in the main menu? If not it would make sense that the CPU is at 100%: we are rendering little and librocket consumes some CPU so we get CPU bound.

**Comment by Viech** [comment] 2015-02-05 14:58
Assigning to test whether this affects both release and debug builds.

**Comment by DolceTriade** [comment] 2015-02-07 10:06
It should affect both builds. We do not throttle CPU when in the menu.

**Comment by Viech** [comment] 2015-02-15 16:59
There's also high CPU load while downloading missing files.

**Comment by DolceTriade** [comment] 2015-02-16 03:14
I really don't know what to do here. Maybe moving librocket to the cgame will help here because we can avoid some of the relayouting, which is quite CPU intensive.

**Comment by Viech** [comment] 2015-02-16 17:22
What about a frame rate limit?

**Comment by neumond** [comment] 2015-03-05 13:09
Some info using <ctime> clock()

CL_CheckUserinfo 1 
CL_CheckTimeout 37 
CL_SendCmd 24 
CL_CheckForResend 23 
CL_SetCGameTime 23 
Rocket_Update 988 
SCR_UpdateScreen 14913 
Audio::Update 125 
CL_UpdateMumble 26 
SCR_RunCinematic 24 
Con_RunConsole 118 
Full CL_Frame time 16327

**Comment by neumond** [comment] 2015-03-05 14:25
Narrowed down the problem. With glFinish called just before swapbuffers it loads CPU 100%. Without ~30%. Still confused.

**Comment by Viech** [comment] 2015-03-05 17:44
30% is still quite a load for idling in menu, it should be close to 0% on any significantly recent CPU. Also the commit isn't on `master` or a `for-*` branch yet, so I'll reopen for now.

**Comment by Viech** [comment] 2015-03-05 23:22
Nevermind, the commit is on `master`. I'll leave the issue open to discuss the remaining CPU load anyway. Any idea why it stresses the CPU at all?

**Comment by Veyrdite** [comment] 2015-11-17 04:13
Something in the nacl thread seems to be doing it:

http://i.imgur.com/nqOOZTx.png

I'm on a low end 4 year old processor without having any issues.  Is it worth keeping this bug open for discussion?

**Comment by Viech** [comment] 2015-11-17 11:44
If @Kangz and @Amanieu don't have any input I'd close this.

**Comment by DolceTriade** [comment] 2015-11-17 17:10
Well, librocket is in nacl now, so it would be something in the nacl thread I think.

**Comment by bmorel** [comment] 2021-09-27 08:14
I believe this is fixed (can't reproduce here), but confirmation would be welcome.

**Comment by illwieckz** [comment] 2021-09-27 08:51
Assuming what said neumond and Viech at the time, the CPU load would have dropped from 100% to 30%

> **neumond**:
> Narrowed down the problem. With glFinish called just before swapbuffers it loads CPU 100%. Without ~30%. Still confused.

- neumond added a commit that referenced this issue on Mar 5, 2015: Fix high CPU load caused by glFinish #359 

> **Viech**: Nevermind, the commit is on master. I'll leave the issue open to discuss the remaining CPU load anyway. Any idea why it stresses the CPU at all?

The CPU usage of our libRocket main menu is still a bit high but it's not a big concern anymore (it would still be good to get more performance), the big concern was this main menu was also rendered when not displayed and it affected game performance (#1318), but this is now fixed in #1319.

The libRocket version we use is subject to some bugs anyway (like #1152) and is expected to be replaced by RmlUI (see #1200). Any improvement related to libRocket/RmlUI is considered postponed for after the move to RmlUI.

**Comment by illwieckz** [comment] 2021-09-27 09:05
According to this comment: https://github.com/Unvanquished/Unvanquished/issues/1318#issue-806337744

> **illwieckz**: I also noticed the Unvanquished main menu was able to get 850fps

I get not-that-bad performance on main menu when displayed alone. That does not mean the CPU usage is not high anyway.

The big problem that was remaining until recently was that doing main menu rendering plus world rendering at the same time hurt performance a lot, but now when doing only the main menu or only the world render, it's _not that bad_. People can still get significant frame drop when opening the main menu in game with a map rendered behind, but CPU usage is not as crazy as when the issue was opened.

For now I consider this issue fixed. It's possible remaining performance improvements are expected to be done in libRocket itself. I recommend reconsidering UI performance after RmlUI merge if it's bad enough to be noticed. If a specific performance UI issue is noticed and is related to our own code (the way we interact with libRocket/RmlUI for example), please open a new issue.

**Closed by illwieckz** 2021-09-27 09:05 UTC
Labels: A-UI, A-Client, T-Performance, old-needcheck
