### ISSUE TITLE
Medi animation obstructs view

### ISSUE THREAD

**Issue by VReaperV** [Unvanquished/Unvanquished#2394] opened 2023-01-30 14:03 UTC
Medi animation when someone is healing on it largely obstructs view of anything behind/on it, and everywhere if you're standing on it.

**Comment by necessarily-equal** [comment] 2023-01-30 17:12
I'll close this because this is a duplicate of https://github.com/Unvanquished/Unvanquished/issues/1326. Still thanks for reporting (better some duplicated bugs than missed bugs)

**Closed by necessarily-equal** 2023-01-30 17:12 UTC
