### ISSUE TITLE
Icons in build menu are not updated

### ISSUE THREAD

**Issue by mole99** [Unvanquished/Unvanquished#1375] opened 2021-04-15 15:03 UTC
When having less than the needed build points for a building its icon is grayed out.

![Bildschirmfoto von 2021-04-13 10-28-39](https://user-images.githubusercontent.com/3877395/114891255-04aa5500-9e0c-11eb-8049-0a8ac2acc0e7.png)

If you then wait for enough build points, the icons are not refreshed.

![Bildschirmfoto von 2021-04-13 10-29-32](https://user-images.githubusercontent.com/3877395/114891260-05db8200-9e0c-11eb-9bad-de8cd537e8a1.png)

Closing and opening the build menu refreshes the icons.

**Comment by illwieckz** [comment] 2021-04-15 15:10
Yeah same with buy menu and evolve menu. I would be surprised if there is not already an issue about this but I did not find it yet. 😁

**Comment by Gireen** [comment] 2021-04-15 20:55
I'm sure i read it somewhere, but cant find the issue 😐
With slipher's recent rewrite of the circle menu it might be possible to update the menu in short intervals or when credits/bp change.

**Comment by Gireen** [comment] 2021-11-07 13:15
fount it 😄 
duplicate of #364

**Closed by Gireen** 2021-11-07 13:15 UTC
