### ISSUE TITLE
Shotgun and SMG, no sound effect when reloading

### ISSUE THREAD

**Issue by AWxxx** [Unvanquished/Unvanquished#3175] opened 2024-11-01 08:05 UTC
Shoutgun and smg have no sound effect when reloading gun.

**Comment by slipher** [comment] 2024-11-01 16:55
Is there *any* gun that has a reloading sound?

**Comment by VReaperV** [comment] 2024-11-01 19:22
I don't think so.

**Comment by DolceTriade** [comment] 2024-11-01 19:29
But certainly something we should add

**Comment by Gireen** [comment] 2024-11-01 20:58
duplicate of #1164

**Closed** 2024-11-01 21:04 UTC
