### ISSUE TITLE
0.38 flickering UI and moving walls still happens

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#700] opened 2015-04-12 00:11 UTC
see issue #698 and also see this video still happens on master:

http://unvtraining.pw/breathing2.mp4
I will add that it happens less frequently maybe.

**Comment by DolceTriade** [comment] 2015-04-12 00:40
It would be awesome if you could get an apitrace of this and attach it here. I don't know if there is a pacakge for i but you can get the source here: https://github.com/apitrace/apitrace

Then run 
```apitrace trace <how you run unv>```

It should output a file like daemon.trace or something. Attach that here. If you can reproduce on a lower resolution, that should help decrease the filesize.

**Comment by Viech** [comment] 2015-04-12 14:18
Please re-open the original issue in case it wasn't fixed.

Also make sure your master is up to date and has the commit referenced there (`git log`).

Closed as a duplicate of #698.

**Closed by Viech** 2015-04-12 14:18 UTC
