### ISSUE TITLE
Spectating someone makes the client act as if playing instead of that player

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1636] opened 2021-12-18 19:34 UTC
This is directly linked to #1399, but have more implications which were not mentioned:

1. it is impossible to use any cheat command while spectating (in /devmap mode, ofc)
2. when spectating without joining a team, only the teammates of the spectated player have detailed infos in the scoreboard

2nd point could actually be thought about as a feature to avoid spying, but considering how trivial it is to spectate other team anyway, it don't think it's really worth it.

**Comment by Gireen** [comment] 2021-12-18 20:03
1. which commands? 
2. is not a bug

**Comment by bmorel** [comment] 2021-12-18 20:16
1. Which commands... well, there's several. The one I know the most is of course the `navedit` one, and I can't remember others from top of my head. As I said, it's about cheat commands, so it's not that important.

2. I explained what I think about this behavior. Well, if this behaviors does not requires code to run, then it's fine, but if some special code or weird hack suck as faking identity is required, then I think it's not worth it, especially considering how easy it is to just un-spectate to see all info and then go back at spectating. Basically, I'd say I can not see any benefit for this behavior.

**Comment by bmorel** [comment] 2021-12-30 16:40
About 2nd point "when spectating without joining a team, only the teammates of the spectated player have detailed infos in the scoreboard", there's another detail there: when you spectate, you don't see the other team's equipment in scoreboard, *but* you see their team chat, including the name of the room messages are emitted from.
There is also #1399 which is related to that

**Comment by necessarily-equal** [comment] 2022-01-09 20:18
This issue seems fairly vague.

For the number 2 issue, I think we can just say it's not an issue because it sounds annoying to fix :P

For the number 1 issue, I've personnally tried with `/give momentum`, and it complains that I didn't join a team — so it looks like it's working as intended. If you have examples of commands that don't work, then we can move this forward (except `/navedit` I guess, because there isn't much point in that in the current state of things IMHO).

**Comment by necessarily-equal** [comment] 2022-07-03 01:14
I'm going to close this as NOTABUG WONTFIX, please open another one for specific cheat command that may be broken. Or only `/navedit` if this the only command you noted to do that.

**Closed by necessarily-equal** 2022-07-03 01:14 UTC
Labels: A-Client, T-Bug
