### ISSUE TITLE
parsing 78 arenas makes gamelogic crash

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1980] opened 2022-07-26 16:55 UTC
To reproduce: ensure you have at least 78 different maps installed, join either nightly builds server or a SKx server, invoke menu, click on "change map".
After a small lag, you will be back at menu.
Logs say:

```
Warn: [skipnotify]78 arenas parsed
 
Warn: IPC: Failed to receive message: Resource temporarily unavailable 
```

I tested with 0.52 client.

I originally had much more files than that in my pkg folder, I removed everything, and got back things chunk per chunk until finding this number.

Issue is 100% reproducible.

Needless to say, removing a map "fixes" the problem.
Also:

```
~/.local/unvanquished/pkg% ls -1 map-*.dpk | wc -l
88
```

I tried with several maps, same result. Not sure all have a `.arena` file, but it's very likely.

**Comment by illwieckz** [comment] 2022-07-26 17:02
If I remember correctly the `0.53.0/branch` doesn't read `.arena` files when listing maps so it may workaround the issue even if that was not on purpose, though we may want to know what makes the game crash.

**Comment by bmorel** [comment] 2022-07-26 17:03
There is no actual proof the problem comes from the arena file. The only reason I used this title is because of the log messages.

**Comment by bmorel** [comment] 2022-07-26 17:12
I insist that the crash can be reproduced on *nightly server* which does not have many maps. It's enough to have those maps installed *locally*.

**Comment by necessarily-equal** [comment] 2022-07-26 17:15
So the problem is that if you have 78 maps on your computer and you try to connect to any server, the client crashes?

**Comment by bmorel** [comment] 2022-07-26 17:16
> join either nightly builds server or a SKx server

**Comment by DolceTriade** [comment] 2022-07-26 20:43
To be clear, a regression is something that used to work but doesn't work anymore. Did this used to work on previous alphas?

**Comment by bmorel** [comment] 2022-07-26 20:44
This crash only appear when connecting to a server which is more recent than 0.52.

**Comment by DolceTriade** [comment] 2022-07-29 08:18
This code is impossible to hit after https://github.com/DaemonEngine/Daemon/issues/557 was closed. I will close this as not reproducible.

If you disagree feel free to re-open.

**Comment by DolceTriade** [comment] 2022-07-29 08:19
Specifically

```
Warn: [skipnotify]78 arenas parsed
```

was deleted here d02336d738aff8f62677f62ebff4552464732a68

**Closed by DolceTriade** 2022-07-29 08:18 UTC
Labels: A-Gamelogic, A-Client, T-Bug, T-Regression
