### ISSUE TITLE
Scoreboard doesn't disappear in game

### ISSUE THREAD

**Issue by ckol** [Unvanquished/Unvanquished#734] opened 2015-05-18 18:22 UTC
Unv 0.39
Before 0.39 the scoreboard as well as the weapons dialog didn't show up every
once in a while - you had to restart unv to get it back.
Now it's stuck every once in a while while even in normal game mode.
I suggest to fix it properly.

Screenshot available. How/where to upload?

**Comment by DolceTriade** [comment] 2015-05-19 02:20
imgur.

**Comment by Viech** [comment] 2015-06-18 14:07
I don't see how a screenshot would help if there aren't any visual anomalies in addition to what was reported. I can confirm that sometimes the scoreboard remains open when I release the associated key, though pressing and releasing that key once more closes it for me.

**Comment by ckol** [comment] 2015-06-18 14:30
Hello, Viech!

It's somehow difficult to show something which is not present.
Imagine the screen with the rectangular scoreboard in the center
just without showing the scoreboard. :-)

The same or a similar issue was reported with the round in-game
weapon selection dialog. It re-appears after restarting unvanquished
(daemon) and re-login again. Off course that kills the game-play.

Greets,

ckol

**Comment by Viech** [comment] 2015-06-18 23:18
@ckol, oh, I misunderstood the issue. That's nothing I've seen so far with the scoreboard but I'll leave the *verified* marker preset since it may indeed be the same issue as with the build menu.

**Comment by illwieckz** [comment] 2022-08-18 07:07
Quoting myself from https://github.com/Unvanquished/Unvanquished/issues/1102#issuecomment-450492267 so I can close duplicate #1102 without losing that information:

> `2018-12-10 01:24 <+illwieckz>` interesting, if end of game occurs while map is still downloading, the scoreboard will be displayed once the nextmap is loaded

**Comment by illwieckz** [comment] 2022-08-18 07:10
Hmm, maybe that was not exactly a duplicate, if this is not a duplicate the original issue hasn't been reported since.

**Comment by illwieckz** [comment] 2022-08-18 07:13
So I close this one. For some reasons I don't fully understand the description of this bug. But I believe I can close it because:

- If this is a duplicate of https://github.com/Unvanquished/Unvanquished/issues/1102 then we have an open issue with a description I better understand.
- If this is not a duplicate of https://github.com/Unvanquished/Unvanquished/issues/1102 then no one reported it again since 7 years.

**Closed by illwieckz** 2022-08-18 07:13 UTC
Labels: A-UI, S-Verified, T-Bug
