### ISSUE TITLE
0.54 welcome screen: no mouse cursor is available

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2393] opened 2023-01-30 13:28 UTC
While working on updating Bunker to 0.54, I have discovered that while the welcome screen is displayed, you cannot interact with it because there is no mouse cursor. The player is left to guess that they must press ESC to close the window.

**Comment by necessarily-equal** [comment] 2023-01-30 13:42
Is this similar to https://github.com/Unvanquished/Unvanquished/issues/1887?

**Comment by cu-kai** [comment] 2023-01-30 13:43
It could well be. I replaced the default welcome.rml with the custom changelog I wrote for Bunker and mysteriously, the cursor appears by itself again.

**Comment by necessarily-equal** [comment] 2023-01-30 13:50
You said it happens on wayland and that the cursor appears if you move your mouse around. I think this is a duplicate of https://github.com/Unvanquished/Unvanquished/issues/1887

**Closed by necessarily-equal** 2023-01-30 13:50 UTC
