### ISSUE TITLE
Health shown when mousing-over teammates does not update

### ISSUE THREAD

**Issue by Veyrdite** [Unvanquished/Unvanquished#285] opened 2014-01-17 01:59 UTC
Name and health text shown on centre of hud when mousing over teammates: health value does not change even if the teammate is healing or being attacked.  

The only way to force an update is to look away from your teammate, wait, and then look back again.

![Uploading mouseover_health.jpeg . . .]()

**Comment by Viech** [comment] 2015-01-04 00:24
I'll investigate this soonish.

**Comment by Viech** [comment] 2015-02-04 15:21
After having had a quick look, I now assume that this is either an UI or engine bug, as health is retrieved from the team overlay data which is sent via configstrings (atleast I very much assume it is). Unassigning and poking @DolceTriade and @Kangz to give input. (If I remember correctly, @Kangz has been working on configstrings a while ago and there's #473 which also seemed to be configstring related when I briefly looked into it, so that's why I consider the second possibility.)

**Comment by Kangz** [comment] 2015-02-04 21:45
I don't know about how this works, but if it is using configstrings we should change that to use entities instead as config strings are not delta compressed in the netcode.

**Comment by Viech** [comment] 2015-02-05 15:02
The team overlay wasn't even re-implemented in the UI so I think we can safely drop all the configstring code surrounding it. To fix this issue and also if we want the team overlay back, both could be done with the beacons that are already transmitted for every teammate regardless of vis. @enneract and I (unpublished code) have been working on beacon status displays recently, so I'll assign to also replace the health information with them.

**Comment by bmorel** [comment] 2022-01-04 22:43
I can not reproduce on 0.52.1, it's likely fixed.

**Comment by bmorel** [comment] 2022-07-06 12:21
No answer since months, I guess it can be closed?

**Comment by bmorel** [comment] 2022-07-16 00:43
I'm closing this, because if I understand correctly the bug, then it was fixed someday, and nobody answered in more than 6 months.

**Closed by bmorel** 2022-07-16 00:43 UTC
Labels: A-Gamelogic, S-Verified, T-Bug, S-Old-Needs-Check
