### ISSUE TITLE
"CM_InlineModel: bad number" when joining a team on plat23 locally

### ISSUE THREAD

**Issue by MZ-Alex** [Unvanquished/Unvanquished#460] opened 2014-10-12 21:21 UTC
platform: windows 7 64 bits - ATI 4670
release: unvanquished 0.23

I delete my profile (%mydocuments%\my games\unvanquished)
/map plat23
join any team and the following error appears:
![unvanquished_2014-10-12_181150_000](https://cloud.githubusercontent.com/assets/8269820/4607593/ae2b863a-5255-11e4-8bbf-56505d365d12.jpg)

**Comment by Viech** [comment] 2015-01-01 23:08
So, close this? Or can anyone still reproduce?

**Comment by DolceTriade** [comment] 2015-01-02 07:12
Yeah, these commits were the cause and the revert was intrtoduced in alpha 34.

**Closed by DolceTriade** 2015-01-02 07:12 UTC
Labels: A-Gamelogic, T-Bug
