### ISSUE TITLE
Provided linux build reported to not work on NixOS

### ISSUE THREAD

**Issue by davidak** [Unvanquished/Unvanquished#1302] opened 2021-01-29 13:41 UTC
The provided linux version don't work on NixOS. I'm not sure if it's worth packaging.

It would be great if there was a AppImage or Flatpak build that works on any linux.

That would also bring more players to the game and make it more fun for everyone.

Since this is probably not the first request (but i haven't found an issue), what is the status and opinion on this topic?

**Comment by illwieckz** [comment] 2021-01-29 14:14
From what I see AppImage suffers the same problem we have with our own builds, I see no chance an AppImage works where our own build does'nt work, and if it works, it means we can apply the same fix to our own build. AppImage solves distribution issues, not compatibility issues _that much_. And by experience I have seen many appimages that are _less cross-distribution_ than our own build.

For flatpak, why not, but that's yet another thing to take care about. At some point we would care about one distribution platform per player. So basically the problem is always manpower.

Note that the easiest way for us to make a flatpak would be to… ship our own build as is in a flatpak, so that may not solve your issue. If doing a flatpak this way would solve your issue it would mean what solves the issue would be the flatpak-provided runtime, meaning the issue would be NixOS provided environment and your working distro would be flatpak instead and that NixOS would be at fault… 

What is the version you try to run? The 0.51.1 version is known to be buggy (see #1215). Can you check you use our latest updater ([0.1.0](https://github.com/Unvanquished/updater/releases/tag/v0.1.0)) or latest release if you use the zip one ([0.51.2](https://github.com/Unvanquished/Unvanquished/releases/tag/v0.51.2)), and if you use the zip archives, can you make sure that, once you extracted the engine, it sits right next to the `pkg/` directory (not in a `linux-amd64` directory created by your archive-manager)?

I rename this issue to track your issue with NixOS. Flatpak is tracked in #1099.

**Comment by davidak** [comment] 2021-01-29 18:50
>meaning the issue would be NixOS provided environment and your working distro would be flatpak instead and that NixOS would be at fault…

yes. exactly that is the case. in nixos, packaged software has only access to defined dependencies. the "provided environment" is pretty much empty. so using flatpak as environment would solve many issues.

when i try to just run your updater, i get this error:

```
[davidak@gaming:~/Downloads]$ ./UnvanquishedUpdater
bash: ./UnvanquishedUpdater: No such file or directory
```

we have a basic FHS environment for running external software like steam games. with that i can run the updater and install the game, but it crashes on start, because it's need special dependencies

```
[davidak@gaming:~/Downloads]$ steam-run ./UnvanquishedUpdater
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Windows, Fusion
Git version: v0.1.0
3 stored settings:
 - "settings/commandLineParameters" = "%command%"
 - "settings/currentVersion" = "0.51.2"
 - "settings/installPath" = "/home/davidak/.local/share/unvanquished/base"
Testing exception handling...
Exception handling works
QFontDatabase: Cannot find font directory /qt/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
CurrentVersionFetcher: fetched versions: updater = "v0.1.0" game = "0.51.2"
Previously-installed game version: "0.51.2"
Starting game with command line: "\"/home/davidak/.local/share/unvanquished/base/daemon\""
Unvanquished 0.51 Linux x86_64 Dec  5 2018
cmdline:
[FS] Lib path: /home/davidak/.local/share/unvanquished/base 
[FS] Home path: /home/davidak/.local/share/unvanquished 
[FS] Pak search path: /home/davidak/.local/share/unvanquished/base/pkg 
[FS] Pak search path: /home/davidak/.local/share/unvanquished/pkg 
Starting crash logging server 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/unvanquished_0.51.1.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/tex-common_2.1.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-players_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-weapons_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-buildables_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-voices_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-soundtrack_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-legacy_0.51.dpk'... 
execing 'default.cfg' 
Warn: Couldn't read conhistory: No such file or directory 
----- Client Initialization ----- 
Loading RSA keys from pubkey 
Daemon RSA public-key found. 
----- Client Initialization Complete ----- 
Calling GetRefAPI… 
SDL_Init( SDL_INIT_VIDEO )...  
Using SDL Version 2.0.3 
SDL using driver "x11" 
Initializing OpenGL display 
Display aspect: 1.778 
...setting mode -2: 
 2560 1440 
The change will take effect after restart. 
The change will take effect after restart. 
Warn: GLEW version < 2.0.0 doesn't support GL core profiles 
Using 24 Color bits, 24 depth, 8 stencil display. 
Using GLEW 1.12.0 
Using enhanced (GL3) Renderer in GL 3.x mode... 
Available modes: '1280x720 1920x1080 2560x1440 2048x1080 1280x800 1440x900 1680x1050 1920x1200 720x480 640x480 ' 
GL_RENDERER: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.39.0, 5.9.16, LLVM 9.0.1) 
Detected graphics driver class 'OpenGL 3+' 
Detected graphics hardware class 'ATI Radeon' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...found shading language version 450 
...using GL_ARB_half_float_pixel 
...using GL_ARB_texture_float 
...using GL_EXT_gpu_shader4 
...using GL_EXT_texture_integer 
...using GL_ARB_texture_rg 
...using GL_ARB_texture_gather 
...using GL_EXT_texture_filter_anisotropic 
...using GL_ARB_half_float_vertex 
...using GL_ARB_framebuffer_object 
...using GL_ARB_get_program_binary 
...using GL_ARB_buffer_storage 
...using GL_ARB_uniform_buffer_object 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
glsl shaders took 413 msec to build 
GL_VENDOR: X.Org 
GL_RENDERER: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.39.0, 5.9.16, LLVM 9.0.1) 
GL_VERSION: 4.5 (Compatibility Profile) Mesa 19.3.3 
GL_SHADING_LANGUAGE_VERSION: 4.50 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 16384 
Using OpenGL 3.x context 
Using GPU vertex skinning with max 256 bones in a single pass 
Extracting VM module cgame-x86_64.nexe from /home/davidak/.local/share/unvanquished/base/pkg/unvanquished_0.51.1.dpk...
 
Loading VM module cgame-x86_64.nexe... 
]/home/davidak/.local/share/unvanquished/base/nacl_loader: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Warn: Error during initialization: IPC: Socket closed by remote end 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/unvanquished_0.51.1.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/tex-common_2.1.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-players_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-weapons_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-buildables_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-voices_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-soundtrack_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-legacy_0.51.dpk'... 
terminate called after throwing an instance of 'Sys::DropErr'
  what():  IPC: Failed to send message: Broken pipe
```

i don't know if it would make sense to include libstdc++ in your build, but adding it would fix this issue. maybe after that come more... i could also add it to the steam-run environment, but a proper solution would be to package it for nixos.

there was some issue packaging 0.43.0 in the past, so the package was removed. https://github.com/NixOS/nixpkgs/issues/9781 the situation might be better now or we can figure it out together. the benefit would be that the package would work on any linux distro, since the nix package manager does

thanks for the fast response. i will also do further debugging to see what is missing to get it running

**Comment by illwieckz** [comment] 2021-01-29 19:07
Hmmm, shipping libstdc++ would be calling for troubles for everyone but Nix users… Given what you said, repackaging our current build as a flatpak may fix the issue because your issue seems to only be the lack of a proper environement, what can provide flatpak.

Note that if you want to make a nix pkg (or any other distro package) the only software you need to build is the [Dæmon Engine](https://github.com/DaemonEngine/Daemon), then you just ship the `.dpk` files with it and that's all.

[Here you can find some scripts](https://github.com/Unvanquished/Unvanquished/tree/master/dist/scripts) that are thought to be reusable and cross distro, given you provide a file named `/etc/unvanquished/paths.conf` that sets the paths according to the special hierarchy of the distro ([here is an example for Debian](https://github.com/Unvanquished/Unvanquished/blob/master/debian/paths.conf)).

**Comment by illwieckz** [comment] 2021-01-29 19:11
> when i try to just run your updater, i get this error:
> ```
> [davidak@gaming:~/Downloads]$ ./UnvanquishedUpdater
> bash: ./UnvanquishedUpdater: No such file or directory
> ```

Can you do this:

```sh
ldd UnvanquishedUpdater
```

And report the output?

**Comment by davidak** [comment] 2021-01-29 19:23
```
[davidak@gaming:~/Downloads]$ ldd ./UnvanquishedUpdater
	linux-vdso.so.1 (0x00007ffeb0948000)
	libxcb-glx.so.0 => not found
	libX11-xcb.so.1 => not found
	libxcb.so.1 => not found
	libXext.so.6 => not found
	libX11.so.6 => not found
	libxkbcommon.so.0 => not found
	librt.so.1 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/librt.so.1 (0x00007f47bbbb6000)
	libz.so.1 => not found
	libdl.so.2 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libdl.so.2 (0x00007f47bbbb1000)
	libGL.so.1 => not found
	libpthread.so.0 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libpthread.so.0 (0x00007f47bbb90000)
	libstdc++.so.6 => not found
	libm.so.6 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libm.so.6 (0x00007f47bba4d000)
	libgcc_s.so.1 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libgcc_s.so.1 (0x00007f47bba33000)
	libc.so.6 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libc.so.6 (0x00007f47bb874000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib64/ld-linux-x86-64.so.2 (0x00007f47bbbc4000)
```

in this environment all exist, interesting. so the problem might be that the updater executable starts another one
```
[davidak@gaming:~/Downloads]$ steam-run ldd ./UnvanquishedUpdater
	linux-vdso.so.1 (0x00007fff67399000)
	libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0x00007fa9ed0bb000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007fa9ed0b6000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fa9ed08b000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fa9ed076000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fa9ecf32000)
	libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x00007fa9eceef000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007fa9ecee3000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fa9ecec6000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fa9ecec1000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007fa9ece33000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fa9ece12000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fa9ecc31000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fa9ecaee000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fa9ecad4000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fa9ec915000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/4x7cr4gj12gccmkv6z1p76c1255rky1n-glibc-multi-2.31/lib/ld-linux-x86-64.so.2 (0x00007fa9ed0db000)
	libXau.so.6 => /nix/store/ibfc2cx2mb935h58djiiw0vhbd685ih6-libXau-1.0.9/lib/libXau.so.6 (0x00007fa9ec910000)
	libXdmcp.so.6 => /nix/store/9kk0k68mcf75b5jlw46lhxnjnal9nl7w-libXdmcp-1.1.3/lib/libXdmcp.so.6 (0x00007fa9ec908000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007fa9ec8d2000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007fa9ec819000)
```

**Comment by illwieckz** [comment] 2021-01-29 19:51
With `steam-run`, does the updater run and download the game?

**Comment by davidak** [comment] 2021-01-30 10:15
>With steam-run, does the updater run and download the game?

yes. but the game fail to start. see previous posted terminal output

**Comment by illwieckz** [comment] 2021-01-30 11:07
I guess the main issue is there:

```
/home/davidak/.local/share/unvanquished/base/nacl_loader: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

Can you do this?

```sh
ldd /home/davidak/.local/share/unvanquished/base/nacl_loader
```

**Comment by illwieckz** [comment] 2021-01-30 11:09
What if you try to run the game this way?

```
steam-run ~/.local/share/unvanquished/base/daemon
```

**Comment by davidak** [comment] 2021-01-30 11:14
```
[davidak@gaming:~/Downloads]$ ldd ~/.local/share/unvanquished/base/nacl_loader
	linux-vdso.so.1 (0x00007fff5154d000)
	librt.so.1 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/librt.so.1 (0x00007f8a8ea14000)
	libpthread.so.0 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libpthread.so.0 (0x00007f8a8e9f3000)
	libstdc++.so.6 => not found
	libc.so.6 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libc.so.6 (0x00007f8a8e834000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib64/ld-linux-x86-64.so.2 (0x00007f8a8eb9a000)

[davidak@gaming:~/Downloads]$ steam-run ldd ~/.local/share/unvanquished/base/nacl_loader
	linux-vdso.so.1 (0x00007ffc9e158000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f8d9016c000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f8d9014b000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f8d8ff6a000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f8d8fdab000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/4x7cr4gj12gccmkv6z1p76c1255rky1n-glibc-multi-2.31/lib/ld-linux-x86-64.so.2 (0x00007f8d902f2000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f8d8fc6a000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f8d8fc50000)
```

>What if you try to run the game this way?

I would have guessed that it works, but i get the same error.

```
davidak@gaming:~/Downloads]$ steam-run ~/.local/share/unvanquished/base/daemon
Unvanquished 0.51 Linux x86_64 Dec  5 2018
cmdline:
[FS] Lib path: /home/davidak/.local/share/unvanquished/base 
[FS] Home path: /home/davidak/.local/share/unvanquished 
[FS] Pak search path: /home/davidak/.local/share/unvanquished/base/pkg 
[FS] Pak search path: /home/davidak/.local/share/unvanquished/pkg 
Starting crash logging server 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/unvanquished_0.51.1.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/tex-common_2.1.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-players_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-weapons_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-buildables_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-voices_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-soundtrack_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-legacy_0.51.dpk'... 
execing 'default.cfg' 
Warn: Couldn't read conhistory: No such file or directory 
----- Client Initialization ----- 
Loading RSA keys from pubkey 
Daemon RSA public-key found. 
----- Client Initialization Complete ----- 
Calling GetRefAPI… 
SDL_Init( SDL_INIT_VIDEO )...  
Using SDL Version 2.0.3 
SDL using driver "x11" 
Initializing OpenGL display 
Display aspect: 1.778 
...setting mode -2: 
 2560 1440 
The change will take effect after restart. 
The change will take effect after restart. 
Warn: GLEW version < 2.0.0 doesn't support GL core profiles 
Using 24 Color bits, 24 depth, 8 stencil display. 
Using GLEW 1.12.0 
Using enhanced (GL3) Renderer in GL 3.x mode... 
Available modes: '1280x720 1920x1080 2560x1440 2048x1080 1280x800 1440x900 1680x1050 1920x1200 720x480 640x480 ' 
GL_RENDERER: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.39.0, 5.9.16, LLVM 9.0.1) 
Detected graphics driver class 'OpenGL 3+' 
Detected graphics hardware class 'ATI Radeon' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...found shading language version 450 
...using GL_ARB_half_float_pixel 
...using GL_ARB_texture_float 
...using GL_EXT_gpu_shader4 
...using GL_EXT_texture_integer 
...using GL_ARB_texture_rg 
...using GL_ARB_texture_gather 
...using GL_EXT_texture_filter_anisotropic 
...using GL_ARB_half_float_vertex 
...using GL_ARB_framebuffer_object 
...using GL_ARB_get_program_binary 
...using GL_ARB_buffer_storage 
...using GL_ARB_uniform_buffer_object 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
glsl shaders took 433 msec to build 
GL_VENDOR: X.Org 
GL_RENDERER: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.39.0, 5.9.16, LLVM 9.0.1) 
GL_VERSION: 4.5 (Compatibility Profile) Mesa 19.3.3 
GL_SHADING_LANGUAGE_VERSION: 4.50 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 16384 
Using OpenGL 3.x context 
Using GPU vertex skinning with max 256 bones in a single pass 
Extracting VM module cgame-x86_64.nexe from /home/davidak/.local/share/unvanquished/base/pkg/unvanquished_0.51.1.dpk...
 
Loading VM module cgame-x86_64.nexe... 
]/home/davidak/.local/share/unvanquished/base/nacl_loader: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Warn: Error during initialization: IPC: Socket closed by remote end 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/unvanquished_0.51.1.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/tex-common_2.1.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-players_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-weapons_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-buildables_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-voices_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-soundtrack_0.51.dpk'... 
[FS] Loading pak '/home/davidak/.local/share/unvanquished/base/pkg/res-legacy_0.51.dpk'... 
terminate called after throwing an instance of 'Sys::DropErr'
  what():  IPC: Failed to send message: Broken pipe
```

![Screenshot from 2021-01-30 12-11-39](https://user-images.githubusercontent.com/91113/106354769-776b6000-62f4-11eb-94f8-4f1dd5bddf3a.png)

**Comment by illwieckz** [comment] 2021-01-30 11:29
I'm not sure that's an issue on our end if the updater finds the libstdc++, the engine finds it too, but a child process can't…

What happens if you do?

```
steam-run ~/.local/share/unvanquished/base/nacl_loader ~/.local/share/unvanquished/cgame-x86_64.nexe
```

**Comment by davidak** [comment] 2021-01-30 11:39
```
[davidak@gaming:~/Downloads]$ steam-run ~/.local/share/unvanquished/base/nacl_loader ~/.local/share/unvanquished/cgame-x86_64.nexe
[2,803710848:12:39:10.142683] Native Client module will be loaded at base address 0x0000555100000000

** Signal 4 from untrusted code: pc=5551004b2100
```

**Comment by illwieckz** [comment] 2021-01-30 11:42
So this time it finds the library… weird.

What does `steam-run`? Do you have a link to its code somewhere?

**Comment by davidak** [comment] 2021-01-30 12:14
It runs a command in an environment with these dependencies available: https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/games/steam/fhsenv.nix

The code is at the end.

**Comment by davidak** [comment] 2021-01-30 12:49
>Flatpak uses a helper called flatpak-bwrap (borrowed from project atomic's bubblewrap) to set up the sandbox.

so flatpak might have the same issue

i'm not sure if you could fix this issue, or if it's on nixos or bubblewrap side. Do you have any idea what the issue is?

**Comment by davidak** [comment] 2021-02-09 19:01
So the issue is:

> nacl_loader: error while loading shared libraries: libstdc++.so.6: cannot open shared object file

The file does exist in `/lib/libstdc++.so.6` (which is a symlink to `/nix/store/ywqi2p2f7zda34avpnxgy72rggfhbxck-steam-run-usr-target/lib/libstdc++.so.6`).

@illwieckz Where does it search for it?

**Comment by illwieckz** [comment] 2021-02-09 19:09
I have no idea about what's happening unfortunately. The fact both the updater, the daemon engine and nacl_loader relies on libstdc++.so.6 and both the updater and the daemon engine loads it properly but the nacle_load does not is very mysterious…

**Comment by davidak** [comment] 2021-02-09 19:20
I run it with strace:

It does find it here:

```
openat(AT_FDCWD, "/lib32/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\3\0\0\0\0\0\0\0\0\3\0\3\0\1\0\0\0\0\20\10\0004\0\0\0"..., 832) = 832
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220\37\n\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0555, st_size=1952240, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5a0efea000
mmap(NULL, 1967712, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f5a0ee09000
mmap(0x7f5a0eea7000, 950272, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x9e000) = 0x7f5a0eea7000
mmap(0x7f5a0ef8f000, 303104, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x186000) = 0x7f5a0ef8f000
mmap(0x7f5a0efd9000, 57344, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1cf000) = 0x7f5a0efd9000
mmap(0x7f5a0efe7000, 9824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f5a0efe7000
close(3)       
```

and here is the point where it fails:

```
[pid   100] openat(AT_FDCWD, "/nix/store/q53f5birhik4dxg3q3r2g5f324n7r5mc-glibc-2.31-74/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   100] writev(2, [{iov_base="/home/davidak/.local/share/unvan"..., iov_len=56}, {iov_base=": ", iov_len=2}, {iov_base="error while loading shared libra"..., iov_len=36}, {iov_base=": ", iov_len=2}, {iov_base="libstdc++.so.6", iov_len=14}, {iov_base=": ", iov_len=2}, {iov_base="cannot open shared object file", iov_len=30}, {iov_base=": ", iov_len=2}, {iov_base="No such file or directory", iov_len=25}, {iov_base="\n", iov_len=1}], 10/home/davidak/.local/share/unvanquished/base/nacl_loader: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
) = 170
```

And `/nix/store/q53f5birhik4dxg3q3r2g5f324n7r5mc-glibc-2.31-74/lib/libstdc++.so.6` does indeed not exist. I investigate more.

**Comment by necessarily-equal** [comment] 2021-04-09 17:55
Hi, I'm not sure it was worth creating a package either, but fixing it properly accounted to making one.

So, huh, here it is https://github.com/NixOS/nixpkgs/pull/118921 😄️

**Comment by necessarily-equal** [comment] 2022-03-11 15:14
Now that it has been packaged on NixOS, that the package is even on stable; and taking into account that the problem would be really annoying to fix and that we would like to drop the tech that creates this problem, I'll close this issue.

Feel free to reopen if there is anything new

**Closed by necessarily-equal** 2022-03-11 15:14 UTC
Labels: OS-Linux, T-Bug
