### ISSUE TITLE
Alpha 51: Missing md3 models warnings.

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#1042] opened 2017-11-03 06:20 UTC
```
Warn: couldn't load 'models/weapons/shells/rifle-shell.md3' 
Warn: couldn't load 'models/players/human_base/jetpack_flash.md3'
 ```

**Comment by illwieckz** [comment] 2017-11-03 11:59
The first one (rifle shell) was renamed to unify the file organisation of shells. But unless I'm missing something I took care of renaming it everywhere according to the new name. Are you sure you are using the last revision of every repository?

For the second one (jetpack flash), isn't it an old model from the old tremulous jetpack? (or was it reused for the new model too)?

**Comment by DolceTriade** [comment] 2017-11-03 18:21
Not sure. I was debugging something else and left this for record keeping. I will investigate both. Either these are missing models or bad code.

**Comment by illwieckz** [comment] 2017-11-04 14:49
I'm not able to reproduce these warnings, and I confirm the jetpack_flash is part of the old tremulous model and not needed anymore.

Btw I confirm the jetpack smoke is gone, but I don't get warnings either… I don't know where to investigate.

**Comment by illwieckz** [comment] 2017-11-04 14:51
Hmm, I found the issue for the jetpack_flash, it's just we have to remove one file more:

```
cat src/res-players_src.dpkdir/scripts/human_base.shader
models/players/human_base/jetpack_flash
{
	sort additive
	{
		map	models/players/human_base/jetpack_flash
		blendfunc GL_ONE GL_ONE
		tcMod scroll 10.0 0.0
	}
}
```

**Comment by illwieckz** [comment] 2017-11-04 14:52
And for the rifle-shell, that's because the turret is also using it (in buildables, not in weapons), nice catch!

**Comment by illwieckz** [comment] 2017-11-04 16:49
it's now fixed on repositories

**Closed by illwieckz** 2017-11-04 16:49 UTC
