### ISSUE TITLE
Luci cannon overload even after mouse release

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#715] opened 2015-05-02 19:46 UTC
In a busy room getting 40FPS, lucifer cannon charging, I let go of mouse button but luci cannon kept charging until it exploded on me.

**Comment by Viech** [comment] 2015-05-03 19:15
So apparently the mouse-up event was missed server side. How long did it charge after you released the mouse button? If the duration was really short, it may have been due to a short network outage or congestion that prevented the key states to arrive at the server in time, though this is just a guess.

**Comment by overvolting** [comment] 2015-05-03 20:11
It charged for about 1 second more.

**Comment by Viech** [comment] 2015-05-03 21:35
Sounds like a bug then. Unfortunately, this sounds like one that can't be easily reproduced…

**Comment by overvolting** [comment] 2015-05-08 00:03
I'll see if it happens again while I record a demo.

**Comment by Veyrdite** [comment] 2015-11-17 06:19
I'm going to be a bastard on an issue-closing tirade and close this for now.

Overvolting: if you record this then please feel free to post/reopen.  It does sound a lot like a transient lag/network issue.

**Closed by Veyrdite** 2015-11-17 06:19 UTC
Labels: A-Engine, A-Network, T-Bug
