### ISSUE TITLE
bots orientation are not affected by granger's lock blob

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#1775] opened 2022-02-25 08:04 UTC
When locking a bot with adv granger's lock blob (or slow, don't know which one it is), they can no longer acquire velocity, but can still rotate.

To reproduce:

* /devmap plat23
* /team h
* /give momentum 150
* /g_bot_infinite_funds 1
* /devteam a
* /give momentum; give all; god
* /bot add * h

Then go meet the human, blob them, turn around then. Human players are not able to rotate, bots will do so without any problem.
I think this may be related to #1303 somehow, but still have no clue on what is happening.

**Comment by bmorel** [comment] 2022-02-25 08:59
Note that I am unsure about how exactly are the blobs meant to work, but I suspect this same problem might apply to trappers, making them even less usable than usual when there are bots around, since they will always see the trappers (as long as above their navmesh) except if one uses a spawn to lure them, since trappers have an enemyScore of 0.8 versus 0.9 (the maximum).

**Comment by bmorel** [comment] 2022-02-27 19:06
Since I forgot the track I had in mind few days ago and it took me a while to got it anew, I suspect [those](https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_bot_util.cpp#L1419) [lines](https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_bot_util.cpp#L1444) to be directly related to the problems.

**Comment by bmorel** [comment] 2023-03-24 18:27
While this is no longer  easy to reproduce because granger no longer is able to lock enemies, the problem is still there, as it also affects the trapper

**Comment by sweet235** [comment] 2023-03-25 06:45
I think a bot's rotation _is_ impeded when hit by a trapper. But if the trapper misses the bot, the bot will kill the trapper instantly.

**Comment by slipher** [comment] 2024-12-30 15:39
Granger locking doesn’t exist any more but the general issue was fixed by #3057.

**Closed by slipher** 2024-12-30 15:39 UTC
Labels: A-Bots, T-Bug, D-Medium, D-Hard
