### ISSUE TITLE
Running a /devmap disables cheat protection for the next game you join

### ISSUE THREAD

**Issue by Veyrdite** [Unvanquished/Unvanquished#314] opened 2014-06-11 03:50 UTC
EDIT: Severely edited since first report

The game keeps track of whether or not you have permission to cheat and edit cheating variables.  This is determined by whether or not you start a /map or a /devmap
## Current behaviour

If the first match you play is non-cheating, then all successive matches (even with /devmap) will not allow you to properly cheat.
If the first match you play is cheating, then all successive matches (even online) can be cheated in.

This bug only seems to apply to cheat-protected variables (like r_showskeleton) and not commands (noclip, god)
## Reproduction

Forcing cheat perms on:
- start the game
- /devmap parpax
- /map parpax
- note that you can change cheat-protected variables
- join an online match
- note that you can change cheat-protected variables

Forcing cheat perms off:
- start the game
- /map parpax
- /devmap parpax
- note that you can NOT change cheat-protected vars
- repeat, etc

![utcs](https://cloud.githubusercontent.com/assets/6168874/3240034/81a6ae8c-f11b-11e3-9622-7ba257d37649.jpeg)

**Comment by Viech** [comment] 2015-01-02 17:52
@Kangz `sv_pure` defaults to `0` and as far as I know the pure check has been removed in the new filesystem. So if clients are loading the wrong pk3s that should (technically) be a different problem. Are you still on this by the way?

**Comment by Amanieu** [comment] 2015-02-04 17:38
I cannot reproduce the pure issue, closing.

**Comment by Viech** [comment] 2015-03-12 22:06
@caldazar-at wrote on IRC:
> I noticed that sometimes debug cvars (cg_thirdpersion, cg_drawbbox) are still active after joining a server. and then you can't reset them because of cheat protection. is that a known bug?
I think this is basically the same issue: Cvars that can only be enabled in devmap mode stay set on the next non-devmap match and cannot even be disabled.

**Comment by caldazar-at** [comment] 2015-03-12 22:26
I found a way to reproduce that bug:
1) start unvanquished (duh!)
2) /devmap plat23
3) /cg_thirdperson 1
4) /cg_drawbbox 1
5) /quit (/disconnect is not enough)
6) start unvanquished againdaa6cd8
7) /map plat23 (or connect to a server): now you can see bboxes and use 3rd persion without cheatmode
8) /map plat23 this solves the problem.

All that happened on current master branch (commit daa6cd8) with pak from alpha 37.
![Uploading debug_cvars.jpg . . .]()

**Comment by Calinou** [comment] 2015-07-22 17:53
I was able to join a server in third person mode. Using Alpha 38, on 64-bit Debian testing.

Steps to reproduce:

1. Launch Unvanquished, type `/devmap parpax`
2. Enter game, type `/cg_thirdperson 1`
3. Quit game
4. Restart game, join a multiplayer server

**Comment by illwieckz** [comment] 2021-09-27 10:47
I'm not able to reproduce this anymore.

**Closed by illwieckz** 2021-09-27 10:47 UTC
Labels: S-Verified, A-Client, T-Bug, old-needcheck
