### ISSUE TITLE
Circle menu loses keyevent after multiple mouse clicks

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1551] opened 2021-10-24 22:07 UTC
To reproduce buy sell Light armor a few times with mouse.
After that the circlemenu doesn't react to key inputs anymore in this case 0-9 and ESC

This doesn't happen if keys are uses to buy and sell.

**Comment by Gireen** [comment] 2021-11-07 13:08
it seems to also happen with other circle menus but with the armory its easiest to reproduce

**Comment by bmorel** [comment] 2021-11-07 13:13
Actually, I suspect this concerns the whole game: sometimes, I stop moving for no reason. I can't reproduce nor imagine any set of condition to do so, though.

**Comment by superdupont-fr** [comment] 2021-11-18 19:50
To me, but since few weeks only. Sometimes I'm stuck for short time. I will try to take care about it.

**Comment by slipher** [comment] 2022-01-06 09:33
It's caused by a libRocket bug where sometimes an element that no longer exists (because it was replaced by the Lua script rewriting the RML) is selected as the focused element. Subsequent events are sent to this element and they don't propagate correctly because the element is detached from the tree.

I tried a hack of forcibly setting the focus element to something that exists, but then uncovered a similar bug where the *hover* element pointer references a deleted element, which causes it to crash. (Hard to tell whether it's caused by the hack as this bug is fairly difficult to reproduce.)

The dangling element bugs with both the focus and hover elements are fixed in RmlUi.

**Closed** 2022-07-24 06:11 UTC
Labels: A-UI, T-Bug, A-Input
