### ISSUE TITLE
Old versions of Unvanquished fail unintelligently when trying to load up-to-date pk3s

### ISSUE THREAD

**Issue by Faelian** [Unvanquished/Unvanquished#841] opened 2015-11-17 17:55 UTC
I haven't play for a while so I decided to do a little game and I have encounter the following problem.

At first launch I have gone to the server list, connect to gg.illwieckz.net and unvanquished has start downloading files (probably a map since I haven't play for month).
Then the game has crash with the following error
![unvanquished-crash](https://cloud.githubusercontent.com/assets/4268373/11219705/2f2b40bc-8d5c-11e5-89d5-e4ddc030a746.png)

And I have it everytime I restart the game now (I don't get to the home screen, it crashes before).

log from terminal :
http://0bin.net/paste/vuNSgEuwRAd1YMZu#prj7l9Vp-LUKzu2aMG+SMhudJ3u1iUxtljX3+bO9pg4

I am running elementary OS freya, on the stable repository, and Unvanquished is installed with the getdeb ppa.

Others :
$ unvanquished --version
Unvanquished 0.44 Linux x86_64 Oct  5 2015
cmdline: -pakpath /var/games/unvanquished/pkg/ --version
Unvanquished 0.44

Graphic Card :
Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)

**Comment by mbasaglia** [comment] 2015-11-17 18:05
Unvanquished 0.44 but it's loading /home/olivier/.unvanquished/pkg/unvanquished_0.45.0.pk3 could that be the cause?

**Comment by Kangz** [comment] 2015-11-17 20:31
Most definitely, especially since we broke VM compat for that release.

@Faelian please update the game to the latest version (0.45), it should fix your problem.

We should really increment the syscall abi number on each release that changes it and have a descriptive error message when the numbers don't match. This will remove 99% of the CGame VM: Reader: problems.

**Comment by DolceTriade** [comment] 2015-11-18 03:16
Yes, I didn't know that existed. Will do for this release.

**Comment by Kangz** [comment] 2015-11-18 20:45
Awesome, thanks, should we close this? I'm very confident updating will fix the problem.

**Comment by mbasaglia** [comment] 2015-11-18 20:56
I think we should keep it open, having mismatched data files should not be a reason to fail horribly

**Comment by Viech** [comment] 2015-11-19 09:35
We need to ensure the syscall ABI number is being updated at latest every release if necessary. Maybe some sort of detection could be added to `update-version-number.sh`?

**Comment by DolceTriade** [comment] 2015-11-20 01:51
It could. it depends on how much we care to be intelligent. For instance, not every release need to break compat anymore.

**Comment by mbasaglia** [comment] 2015-11-20 08:03
BTW, why does unvanquished works fine from git master between releases but fails once the release is made if you don't have the pk3?

**Comment by Kangz** [comment] 2015-11-20 15:28
We try not to merge incompatible changes in master until a week before the release, so that we can still play the game with the master branch.

**Comment by Viech** [comment] 2015-11-20 17:10
Ideally, we don't merge in master until release day. :stuck_out_tongue: 

(There are `for-*` branches to test the release before it's made.)

**Comment by mbasaglia** [comment] 2015-11-20 18:15
I would understand if the game crashed when connecting to a server, but here it crashes during the menu...

**Comment by Kangz** [comment] 2015-11-20 20:07
The menu is in the cgame VM, so unless you use a vm.*.type that loads a VM you just compiled, the engine will want to use the VMs found in the pk3s, which might not be compatible.

**Comment by DolceTriade** [comment] 2015-11-23 06:41
This is no longer an issue if we increment the system release abi

**Closed by DolceTriade** 2015-11-23 06:41 UTC
Labels: A-Engine, T-Verbosity

**Comment by mbasaglia** [comment] 2015-11-23 08:04
Could give a more useful error message, like "Unvanquished 0.45 is incompatible with Daemon 0.44"

**Comment by Viech** [comment] 2015-11-23 14:12
I would get even more descriptive with such an error: `The version of the gamelogic (Unvanquished v0.45.0) is significantly newer than the version of the engine (Dæmon v0.44.0).` Note that there can be insignificant differences of less than a full version (mods) that are also less likely to cause any trouble. Also see [this comment](https://github.com/Unvanquished/Unvanquished/issues/726#issuecomment-149640800) (in #726).
