### ISSUE TITLE
regression: roq videos are not supported

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2798] opened 2023-10-04 05:51 UTC
some tremulous maps used roq videos. Example: map-nova. This screen: 
![ica](https://github.com/Unvanquished/Unvanquished/assets/1316300/a1c7d6ac-0736-452b-b393-e34b6969a06e)

Probably does, as can be seen in the screenshots [from the author](https://github.com/Masmblr/ioQuake3-Tremulous-Maps/blob/main/map-Nova_src/meta/preview_levelshots/1.jpg) which are likely taken from unvanquished, perhaps with a better engine (ioquake3?) but in that case, it means unvanquished lags behind the competition for maps it was designed to load, as nova was definitely built for tremulous.

To have this screen working "that well" you need to fix the regression from 2013 I pointed at in a very recent issue.

**Comment by slipher** [comment] 2023-10-04 06:16
This one isn't a bug. ROQ videos were removed on purpose

**Comment by bmorel** [comment] 2023-10-04 06:42
I would be curious to know the reason to break compatibility.

**Comment by slipher** [comment] 2023-10-04 06:49
Because it's not worth it to implement a whole video codec for the sake of a decorative feature in one or two old maps. Unvanquished is not a museum or archive for historical Tremulous content.

**Comment by illwieckz** [comment] 2023-10-04 12:03
I'm in favor of keeping RoQ video if it works and maps rely on it.

I was only OK with removing it because I believed it was only used by Tremulous startup screen, something we don't do.

**Comment by sweet235** [comment] 2023-10-04 12:09
> This one isn't a bug. ROQ videos were removed on purpose

> it's not worth it to implement a whole video codec for the sake of a decorative feature in one or two old maps

I agree. Video codecs are a nasty thing to support indefinitely. But dropping support for features that used to be taken for granted is walking on thin ice.

> Unvanquished is not a museum or archive for historical Tremulous content

But what is it then? Time has shown that this attitude will not make any content creator take the risk of relying on the volatile and undocumented changes that were made. Can we blame them? We are not even able to render our 11 official maps without obvious errors. And the refactoring is going on and on.

**Comment by illwieckz** [comment] 2023-10-04 12:21
I didn't remember if I was there when RoQ was removed, anyway I know I was OK with removing broken OGM support with theora because that was not OGG and OGM with theora lived in an alternate reality.

But I consider we could keep compatibility with idtech3 formats, that includes things like RoQ and TGA.

I would even not be against reintegrating Theroa (but with OGG) if someone has a need for it.

I consider supporting RoQ is like supporting portal blending: not supporting it is a regression from Tremulous, and we should support it.

**Comment by sweet235** [comment] 2023-10-04 12:22
Or we support some other video codec. One would be enough. If a map's license does not allow us to convert a video, so be it.

**Comment by illwieckz** [comment] 2023-10-04 12:26
I really don't like when we remove things that were used and worked before. Like you said, it was considered granted.

**Comment by slipher** [comment] 2023-10-31 17:39
For the record Nova actually uses the (now fixed) shader replacement entities, not a video file. `videoMap` and ROQ support are purely engine-side, so closing this in favor of https://github.com/DaemonEngine/Daemon/issues/936.

**Closed by slipher** 2023-10-31 17:39 UTC
