### ISSUE TITLE
NaCl VMs not working in OpenSUSE.

### ISSUE THREAD

**Issue by Sherif89** [Unvanquished/Unvanquished#512] opened 2015-01-02 11:14 UTC
Hi, I installed Unvanquished for OpenSUSE 13.2 by 1 Click Install. Game packages seems to be installed correctly, including unvanquished-maps, but when I try to start a LAN game, I can't find any map to select.
I found .pk3 files in /usr/shar/unvanquished like map-archnid2_trem.pk3, tex-tech_1.0.pk3 and unvanquished_0.33.1.pk3. Do maps need to be unpacked?

**Comment by Viech** [comment] 2015-01-02 13:07
No, the pk3 format doesn't need to be unpacked. This sounds more like a UI issue to me. Can you start a map via the console (`SHIFT`+`ESC`) by entering for example `map plat23`?

**Comment by Sherif89** [comment] 2015-01-02 13:42
I saw ERROR! windows. VM: Failed to exec: No such file or directory.
I saw in console, after the error:
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3'...
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3'...
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3'...
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3'...
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3'...
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3'...
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3'...
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3'...
Calling GetRefAPI...
...

**Comment by Viech** [comment] 2015-01-02 13:47
Try to start the game from a terminal emulator with `+reset vm.game.type`. If this doesn't work, try to run it with `+set vm.game.type n`, where `n` is `0`, `2`, `4` and `5`. Whatever value works for you you can then store to configuration by replacing `set` with `seta`. Please report back what value worked for you. Also, are you sure you're on 0.33.1? The log excerpt shows unvanquished_0.32.0.pk3 as the latest pk3.

**Comment by DolceTriade** [comment] 2015-01-02 19:45
Also, suse packages are out of date. I recommend grabbing the universal zip from our downloads page at https://unvanquished.net/downloads

**Comment by Sherif89** [comment] 2015-01-03 03:01
Do you mean like: +reset vm.game.type for example? If yes, non of them made maps available in list of maps and all of them gave the same error

**Comment by Sherif89** [comment] 2015-01-03 03:14
Sorry, I closed it accidently.

**Comment by Viech** [comment] 2015-01-06 16:48
I don't really see what's going on there. Please try whether the multi-platform package (aka universal zip) works for you (you can find it in our [download section](https://www.unvanquished.net/?page_id=318)).

**Comment by Sherif89** [comment] 2015-01-06 20:29
The universal zip worked. I could see the list of maps, while creating a LAN game.
But I get the same VM: Failed to exec, unles I start the game by ./daemon +set vm.game.type 4 then I can play.
Notes:
1. I saw game loading screen and loading bar this time.
2. If I select a map and close the window then open it again, the selected map picture still appears, but the name isn't on the list and the map isn't selected. If I click the start button nothing happens. See:
![bug](https://cloud.githubusercontent.com/assets/8778976/5635623/607a1d16-95f3-11e4-97c1-5c9ba6fa6b94.jpg)

**Comment by Viech** [comment] 2015-01-07 00:41
Are you on windows by any chance?

**Comment by Sherif89** [comment] 2015-01-07 18:36
I'm on Linux and the game was in full screen.

**Comment by Viech** [comment] 2015-01-08 12:07
I had hoped the fact that only `vm.game.type 4` works was windows-related (and thus a duplicate of #513). Maybe binary stripping destroyed some relevant files? Did you use the `unvanquished-git` package on Arch Linux by any chance? (If yes, upgrading to its latest version should fix the default of `vm.game.type 0`).

The UI bug is likely unrelated to the more critical `VM: Failed to exec` issue. Maybe @DolceTriade wants to have a look at it so that we can focus on the VM issue here.

**Comment by Sherif89** [comment] 2015-01-09 15:21
Unvanquished and SDK (I don't remember which version) were updated today from OpenSUSE. I openned the game and found the list of maps, but the VM: Failed to exec issue remains.
I opened download-pk3.sh in universal zip few days before the update and it started downloading, but I remember I maynot have let it complete its downlading. I don't know if it's because of the update or this script.

**Comment by Viech** [comment] 2015-01-09 16:11
If you consider that your assets are broken you should install `aria2c` and run `download-pk3-torrent.sh` instead of `download-pk3.sh`. It uses roughly the same syntax. The difference is that the torret version of the script will repair broken pk3s (and is faster, too).

Alternatively, compare your assets with the following md5sums for Unvanquished 0.35.1 (note that 0.35.0 is equivalent for non-Windows-users):

    6ad66c59d834d74efb54d8dbf5ddc70f  map-antares_a03+1.pk3
    1d8a69d8901270f82e56bee53db86d25  map-chasm_b1+2.pk3
    3c15a9a21cf2e9f3867c00fc7e09920d  map-forlorn_a10.pk3
    2fe84e10a4c801465e4394df1c6d836a  map-parpax_d04.pk3
    6d8d7c32722243ddfe5c1f81eff33158  map-perseus_b5a+1.pk3
    f01b70d04cf2a7d1e9562eaa88982339  map-plat23_b13+1.pk3
    d96e2aaeae25dcb90fe73327c96b1ae6  map-spacetracks_1.0+1.pk3
    de178d6f7f45e6b81f7d74694cb150d8  map-station15_1.0.pk3
    270355a42a82e635a4b1e7183b486b7b  map-thunder_b3+2.pk3
    2e3818edd84d1b33fc2aafb901295eea  map-yocto_b2c+1.pk3
    e28e7ead4187e786f1cafc4a765971aa  tex-all_2.0.pk3
    04136672b783da8855e4f191b76484e7  tex-common_2.0.pk3
    59cc6d2d6ca77f51e67ac2424dd3a125  tex-ej01-clean_1.0.pk3
    13abd57860460e552517f8f9e3684409  tex-ej01-common_1.0.pk3
    ed91a6ea485d56908da34c68dac3c9da  tex-ej01-ice_1.0.pk3
    248fcdd89e53bf0289e3070735eab899  tex-ex_1.0.pk3
    5d85c59e2f6a158976769a6a6d68d267  tex-exm_1.0.pk3
    f8a3b608f5e01d90ec157217a7986802  tex-pk01_1.0.pk3
    adf56abd49e011ff33ff5067d8837ce5  tex-pk02_1.0.pk3
    8fe7468546648cad116440d2def794b2  tex-space_1.0.pk3
    42d12f6e9c3179002a0172abfcdcf59c  tex-tech_1.0.pk3
    62d9f83b7310612bc73af1732c3496ae  tex-trak5_1.0.pk3
    3b6f35a877e7af231f0337795036a740  unvanquished_0.25.0.pk3
    291cbc0379cd084aefa02e9964518961  unvanquished_0.26.0.pk3
    93866375b77361ddf73abd36a8244d8e  unvanquished_0.27.0.pk3
    60627d510c3db5c3585273c9196781d2  unvanquished_0.28.0.pk3
    74dcb97934fdb81a013ffdd0b9c45b6a  unvanquished_0.29.0.pk3
    5d034dfca9c94a83e70b1d11436ff8ae  unvanquished_0.30.0.pk3
    ded43067baf43d89bbd14df75e8676f7  unvanquished_0.31.0.pk3
    83e9b5c011e5542a246b6e483188ec51  unvanquished_0.32.0.pk3
    2f5b8b3a3ab8291ba78b16ebf6af363b  unvanquished_0.33.0.pk3
    6a28cc132148cc87bbd61af6b08d81d1  unvanquished_0.34.0.pk3
    86207b54245886697983841c5c5ad3eb  unvanquished_0.35.0.pk3
    e491c5140395f44f78ebb7bd9fec19bb  unvanquished_0.35.1.pk3

In case this isn't your issue I'm pinging @Kangz and @Amanieu, one of them should be able to guide you through the process of why `vm.game.type 0` doesn't work. It may be that the OpenSUSE package uses binary stripping that damages some of the files (this happened on Arch Linux). You could test if the multi-platform package (see our [download section](https://www.unvanquished.net/?page_id=318)) works for you.

**Comment by Amanieu** [comment] 2015-01-09 17:34
Check if sel_ldr is present, it is required to load the NaCl VMs.

**Comment by Viech** [comment] 2015-01-11 15:58
#515 seems to be a duplicate of this.

**Comment by Sherif89** [comment] 2015-01-13 21:23
I ran this script unintentionally.
I downloaded alpha 0.35.1 today and the game worked without +set vm.game.type 4.

**Comment by Viech** [comment] 2015-01-13 21:58
@Sherif89 could you provide a list of the files inside the OpenSUSE package?

**Comment by Sherif89** [comment] 2015-01-13 22:06
I guess this is all.

In usr/share/unvanquished/pkg:
file:///usr/share/unvanquished/pkg/map-arachnid2_trem.pk3
file:///usr/share/unvanquished/pkg/map-chasm_b1.pk3
file:///usr/share/unvanquished/pkg/map-forlorn_a4.pk3
file:///usr/share/unvanquished/pkg/map-karith_trem.pk3
file:///usr/share/unvanquished/pkg/map-methane-beta1_trem.pk3
file:///usr/share/unvanquished/pkg/map-nano_trem.pk3
file:///usr/share/unvanquished/pkg/map-nexus6_trem.pk3
file:///usr/share/unvanquished/pkg/map-niveus_trem.pk3
file:///usr/share/unvanquished/pkg/map-orion_trem.pk3
file:///usr/share/unvanquished/pkg/map-parpax_d02d.pk3
file:///usr/share/unvanquished/pkg/map-perseus_b4d.pk3
file:///usr/share/unvanquished/pkg/map-plat23_b11.pk3
file:///usr/share/unvanquished/pkg/map-spacetracks-r1_trem.pk3
file:///usr/share/unvanquished/pkg/map-station15-r1_trem.pk3
file:///usr/share/unvanquished/pkg/map-thunder_b3.pk3
file:///usr/share/unvanquished/pkg/map-tremor_trem.pk3
file:///usr/share/unvanquished/pkg/map-UTCS_trem.pk3
file:///usr/share/unvanquished/pkg/map-yocto_b2a.pk3
file:///usr/share/unvanquished/pkg/tex-all_1.0.pk3
file:///usr/share/unvanquished/pkg/tex-common_2.0.pk3
file:///usr/share/unvanquished/pkg/tex-ex_1.0.pk3
file:///usr/share/unvanquished/pkg/tex-exm_1.0.pk3
file:///usr/share/unvanquished/pkg/tex-pk01_1.0.pk3
file:///usr/share/unvanquished/pkg/tex-pk02_1.0.pk3
file:///usr/share/unvanquished/pkg/tex-space_1.0.pk3
file:///usr/share/unvanquished/pkg/tex-tech_1.0.pk3
file:///usr/share/unvanquished/pkg/tex-trak5_1.0.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.33.0.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.33.1.pk3
file:///usr/share/unvanquished/pkg/unvanquished_0.34.0.pk3

In /usr/share/doc/packages/unvanquished: COPYING.txt and GPL.txt.

In /usr/lib64/unvanquished:
file:///usr/lib64/unvanquished/cgame-qvm-native.so
file:///usr/lib64/unvanquished/daemon
file:///usr/lib64/unvanquished/daemonded
file:///usr/lib64/unvanquished/game-nacl-native-dll.so

**Comment by Sherif89** [comment] 2015-01-13 22:07
I forgot. How to check if sel_ldr is present?

**Comment by Viech** [comment] 2015-01-13 23:51
It seems to be missing: According to your listing `/usr/lib64/unvanquished` only has the engine binaries and the shared object versions of the gamelogic. If your listing is complete, we need to:

1. Contact the OpenSUSE package maintainer and tell them to include the missing files.
2. Give the binaries proper names so that people have a remote idea what they could be needed for:
    *  I learned that `sel_ldr` really means "NaCl loader" as "sel" is the french word for salt and NaCl happens to be its chemical formula…
    * The `-exe` is nonstandard and thus confusing. Posix style executables don't have any ending or suffix.
    * Our naming scheme as found in the engine's file system uses `-` as a whitespace and `_` as a version seperator, we should use this for our binaries, too.
3. Maintain a wiki page that explains how to create an Unvanquished distribution, including information on what the files that need to be shipped do, so that we can just link package maintainers to it.

**Comment by guillaume-uH57J9** [comment] 2015-03-15 16:27
I encounter the same error on Debian 8, using the packages provided by:

```
deb http://debs.unvanquished.net testing main
```

**Comment by Viech** [comment] 2015-03-15 19:00
@dsalt ↑

**Comment by FuzzyToothpaste** [comment] 2015-03-30 19:30
The Ubuntu 14.04 packages are also incomplete. I just realized that everyone that is having this problem is on an x86_64 machine. I don't suppose that could have anything to do with it, could it?

**Comment by guillaume-uH57J9** [comment] 2015-04-05 14:07
Debian packages are still affected by this blocking bug. 

So please consider adding a note to redirect users to the universal zip instead of suggesting packages, while this get resolved. 
https://wiki.unvanquished.net/index.php?title=Downloading_%26_Installing

Currently, would be Debian/Ubuntu players are advised to install a package that does not work. This is not a good thing for the game popularity amongst Linux users. 
I tried registering and updating the wiki but that page appear protected. 

Guillaume

**Comment by hunternet93** [comment] 2015-04-26 03:09
I just ran into this bug on Jessie, seems to be a missing dependency on `unv-nacl-runtime`. While installing that fixed the missing link, I get a different error when trying to start Unvanquished.

**Comment by Viech** [comment] 2015-04-26 13:56
@hunternet93 please try to contact the package maintainers about this. @Amanieu is there a way to not require certain mount parameters?

**Comment by Amanieu** [comment] 2015-04-26 13:57
Yes, compile a custom nacl-loader and make it use /tmp instead of /dev/shm

**Comment by Amanieu** [comment] 2015-05-09 20:20
This is no longer necessary since newer versions of NaCl now works around the lack of exec permissions on /dev/shm.

**Closed by Amanieu** 2015-05-09 20:20 UTC
Labels: A-Distribution, OS-Linux, T-Bug
