### ISSUE TITLE
Couldn't compile vertex shader: deformVertexes and Couldn't compile fragment shader: depthtile1 

### ISSUE THREAD

**Issue by Incognito4nonymous** [Unvanquished/Unvanquished#971] opened 2016-10-28 12:36 UTC
Hello everyone, I have browsed the github unvanquished issues and as it seems I am not the only one facing that issue, I'm like the third guy.
I have an Alienware M11x R2 with a Nvidia GForce GT335M and an Intel Core i5
I run Windows 7 64 and Slackware64 14.2 as OSes.
Back in September I asked a friend to download me Unvanquished cause I really got interested by the engine's capacity.
He downloaded the /pkg folder as a Zip, and gave it to me on a flashdisk.
on my side I downloaded the precompiled executables and launched the daemon.exe file from windows, only to see it didn't ran, to see the error
`Couldn't compile fragment shader: depthtile1`
So I rebooted my pc ond Slackware and I ran Unvanquished, same, so I downloaded the Slaackbuild of the game, (which is basically a compilation script that makes the build automatic) and the build was successful.
I launched the game from the console, first normally and here is the output : 

```
Unvanquished 0.50 Linux x86_64 Sep 19 2016
cmdline: -libpath /usr/lib64/unvanquished -pakpath /usr/share/games/unvanquished/pkg
[FS] Lib path: /usr/lib64/unvanquished 
[FS] Home path: /home/incognito/.unvanquished 
[FS] Pak search path: /usr/share/games/unvanquished/pkg 
[FS] Pak search path: /home/incognito/.unvanquished/pkg 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.50.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.49.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.48.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.47.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.46.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.45.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.44.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.43.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.42.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.41.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.40.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.39.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.38.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.37.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.36.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.35.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.34.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.33.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.32.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.31.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.30.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.29.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.28.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.27.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.26.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.25.0.pk3'... 
execing 'default.cfg' 
Warn: Couldn't read conhistory: No such file or directory 
----- Client Initialization ----- 
Loading RSA keys from pubkey 
Daemon RSA public-key found. 
----- Client Initialization Complete ----- 
Calling GetRefAPI… 
SDL_Init( SDL_INIT_VIDEO )...  
Using SDL Version 2.0.4 
]ATTENTION: default value of option force_s3tc_enable overridden by environment.
SDL using driver "x11" 
Initializing OpenGL display 
Display aspect: 1.779 
...setting mode -2: 
 1366 768 
The change will take effect after restart. 
The change will take effect after restart. 
Warn: GLEW version < 2.0.0 doesn't support GL core profiles 
Using 24 Color bits, 24 depth, 8 stencil display. 
Using GLEW 1.13.0 
Using enhanced (GL3) Renderer in GL 2.x mode... 
Available modes: '720x405 1366x768 800x600 1024x768 ' 
GL_RENDERER: Mesa DRI Intel(R) Ironlake Mobile  
Detected graphics driver class 'Mesa' 
Detected graphics hardware class 'generic' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...found shading language version 120 
...using GL_ARB_half_float_pixel 
...using GL_ARB_texture_float 
...using GL_EXT_texture_integer 
...using GL_ARB_texture_rg 
...using GL_EXT_texture_filter_anisotropic 
...using GL_ARB_half_float_vertex 
...using GL_ARB_framebuffer_object 
...GL_ARB_get_program_binary found, but with no binary formats 
...using GL_ARB_buffer_storage 
...GL_ARB_uniform_buffer_object not found 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
Warn: Source for shader program deformVertexes:
# version 120
# extension GL_EXT_texture_integer : require
# define HAVE_EXT_texture_integer 1
# define DEFORM_STEPS
# line 0
# /*

Copyright (C) 2009-2011 Robert Beckebans trebor_7@users.sourceforge.net

This file is part of XreaL source code.

XreaL source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

XreaL source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with XreaL source code; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/
// deformVertexes_vp.glsl - Quake 3 deformVertexes semantic

float waveSin(float x) {
    return sin( radians( 360.0 \* x ) );
}

float waveSquare(float x) {
    return sign( waveSin( x ) );
}

float waveTriangle(float x)
{
    return 1.0 - abs( 4.0 \* fract( x + 0.25 ) - 2.0 );
}

float waveSawtooth(float x)
{
    return fract( x );
}
# if 0

// --------------------------------------------------------------------
ivec4 permute(ivec4 x) {
    return ((62 \* x + 1905) \* x) % 961;
}

float grad(int idx, vec4 p) {
    int i = idx & 31;
    float u = i < 24 ? p.x : p.y;
    float v = i < 16 ? p.y : p.z;
    float w = i < 8  ? p.z : p.w;

```
return ((i & 4) != 0 ? -u : u)
     + ((i & 2) != 0 ? -v : v)
     + ((i & 1) != 0 ? -w : w);
```

}

vec4 fade(in vec4 t) {
    return t \* t \* t \* (t \* (t \* 6.0 - 15.0) + 10.0);
}

vec4 pnoise(vec4 v) {
    ivec4 iv = ivec4(floor(v));
    vec4 rv = fract(v);
    vec4 f[2];

```
f[0] = fade(rv);
f[1] = 1.0 - f[0];

vec4 value = vec4(0.0);
for(int idx = 0; idx < 16; idx++) {
    ivec4 offs = ivec4( idx & 1, (idx & 2) >> 1, (idx & 4) >> 2, (idx & 8) >> 3 );
    float w = f[offs.x].x * f[offs.y].y * f[offs.z].z * f[offs.w].w;
    ivec4 p = permute(iv + offs);

    value.x += w * grad(p.x, rv);
    value.y += w * grad(p.y, rv);
    value.z += w * grad(p.z, rv);
    value.w += w * grad(p.w, rv);
}
return value;
```

}
// --------------------------------------------------------------------
# endif

void DeformVertex( inout vec4 pos,
           inout vec3 normal,
           inout vec2 st,
           inout vec4 color,
           in    float time)
{
    vec4 work = vec4(0.0);

// spread provides some variation on location
# define spread (dot(work.xyz, vec3(1.0)))
# define DSTEP_LOAD_POS(X,Y,Z)     work.xyz = pos.xyz \* vec3(X,Y,Z);
# define DSTEP_LOAD_NORM(X,Y,Z)    work.xyz = normal.xyz \* vec3(X,Y,Z);
# define DSTEP_LOAD_COLOR(X,Y,Z)   work.xyz = color.xyz \* vec3(X,Y,Z);
# define DSTEP_LOAD_TC(X,Y,Z)      work.xyz = vec3(st, 1.0) \* vec3(X,Y,Z);
# define DSTEP_LOAD_VEC(X,Y,Z)     work.xyz = vec3(X,Y,Z);
# define DSTEP_MODIFY_POS(X,Y,Z)   pos.xyz += (X + Y \* work.a) \* work.xyz;
# define DSTEP_MODIFY_NORM(X,Y,Z)  normal.xyz += (X + Y \* work.a) \* work.xyz; \

```
              normal = normalize(normal);
```
# define DSTEP_MODIFY_COLOR(X,Y,Z) color.xyz += (X + Y \* work.a) \* work.xyz;
# define DSTEP_SIN(X,Y,Z)          work.a = waveSin( X + Y \* spread + Z \* time );
# define DSTEP_SQUARE(X,Y,Z)       work.a = waveSquare( X + Y \* spread + Z \* time);
# define DSTEP_TRIANGLE(X,Y,Z)     work.a = waveTriangle( X + Y \* spread + Z \* time);
# define DSTEP_SAWTOOTH(X,Y,Z)     work.a = waveSawtooth( X + Y \* spread + Z \* time);
# define DSTEP_INV_SAWTOOTH(X,Y,Z) work.a = 1.0 - waveSawtooth( X + Y \* spread + Z \* time);
# define DSTEP_NOISE(X,Y,Z)        work = noise4(vec4( Y \* work.xyz, Z \* time));
# define DSTEP_ROTGROW(X,Y,Z)      if(work.z > X \* time) { work.a = 0.0; } else { work.a = Y \* atan(pos.y, pos.x) + Z \* time; work.a = 0.5 \* sin(work.a) + 0.5; }

```
// this macro has to be #defined by the shader compiler
DEFORM_STEPS
```

}

Warn: Compile log:
0:2(12): error: extension `GL_EXT_texture_integer' unsupported in vertex shader

Warn: Built-in shaders failed: Couldn't compile vertex shader: deformVertexes`

After I thought it was due to the lack of power of my Intel Core, so I launched it with my GPU using Primusrun, here is the output :

`[FS] Lib path: /usr/lib64/unvanquished 
[FS] Home path: /home/incognito/.unvanquished 
[FS] Pak search path: /usr/share/games/unvanquished/pkg 
[FS] Pak search path: /home/incognito/.unvanquished/pkg 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.50.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.49.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.48.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.47.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.46.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.45.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.44.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.43.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.42.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.41.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.40.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.39.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.38.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.37.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.36.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.35.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.34.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.33.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.32.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.31.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.30.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.29.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.28.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.27.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.26.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.25.0.pk3'... 
execing 'default.cfg' 
Warn: Couldn't read conhistory: No such file or directory 
----- Client Initialization ----- 
Loading RSA keys from pubkey 
Daemon RSA public-key found. 
----- Client Initialization Complete ----- 
Calling GetRefAPI… 
SDL_Init( SDL_INIT_VIDEO )...  
Using SDL Version 2.0.4 
]ATTENTION: default value of option force_s3tc_enable overridden by environment.
SDL using driver "x11" 
Initializing OpenGL display 
Display aspect: 1.779 
...setting mode -2: 
 1366 768 
The change will take effect after restart. 
The change will take effect after restart. 
Warn: GLEW version < 2.0.0 doesn't support GL core profiles 
Using 24 Color bits, 24 depth, 8 stencil display. 
Using GLEW 1.13.0 
Using enhanced (GL3) Renderer in GL 3.x mode... 
Available modes: '720x405 1366x768 800x600 1024x768 ' 
GL_RENDERER: GeForce GT 335M/PCIe/SSE2 
Detected graphics driver class 'OpenGL 3+' 
Detected graphics hardware class 'generic' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...found shading language version 330 
...using GL_ARB_half_float_pixel 
...using GL_ARB_texture_float 
...using GL_EXT_texture_integer 
...using GL_ARB_texture_rg 
...using GL_EXT_packed_depth_stencil 
...using GL_EXT_texture_filter_anisotropic 
...using GL_ARB_half_float_vertex 
...using GL_ARB_framebuffer_object 
...using GL_ARB_get_program_binary 
...GL_ARB_buffer_storage not found 
...using GL_ARB_uniform_buffer_object 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
Warn: Source for shader program depthtile1:
# version 330 compatibility
# extension GL_ARB_texture_gather : require
# define HAVE_ARB_texture_gather 1
# define HAVE_EXT_texture_integer 1
# define HAVE_EXT_gpu_shader4 1
# define HAVE_ARB_uniform_buffer_object 1
# define varying in
# define textureCube texture
# define texture2D texture
# define texture2DProj textureProj
# define texture3D texture
# ifndef TEXTURE_RG
# define TEXTURE_RG 1
# endif
# ifndef UNIFORM_BUFFER_OBJECT
# define UNIFORM_BUFFER_OBJECT 1
# endif
# ifndef TEXTURE_INTEGER
# define TEXTURE_INTEGER 1
# endif
# ifndef r_AmbientScale
# define r_AmbientScale 1.000000
# endif
# ifndef r_SpecularScale
# define r_SpecularScale 1.000000
# endif
# ifndef r_NormalScale
# define r_NormalScale 1.000000
# endif
# ifndef r_zNear
# define r_zNear 3.000000
# endif
# ifndef M_PI
# define M_PI 3.141593
# endif
# ifndef MAX_SHADOWMAPS
# define MAX_SHADOWMAPS 5
# endif
# ifndef MAX_REF_LIGHTS
# define MAX_REF_LIGHTS 1024
# endif
# ifndef TILE_SIZE
# define TILE_SIZE 16
# endif
# ifndef r_FBufScale
# define r_FBufScale vec2(0.000732, 0.001302)
# endif
# ifndef r_tileStep
# define r_tileStep vec2(0.011713, 0.020833)
# endif
# ifndef r_precomputedLighting
# define r_precomputedLighting 1
# endif
# ifndef r_VertexSkinning
# define r_VertexSkinning 1
# endif
# ifndef MAX_GLSL_BONES
# define MAX_GLSL_BONES 233
# endif
# ifndef r_WrapAroundLighting
# define r_WrapAroundLighting 0.700000
# endif
# ifndef r_HalfLambertLighting
# define r_HalfLambertLighting 1
# endif
# line 0
# /*

Copyright (C) 2006-2011 Robert Beckebans trebor_7@users.sourceforge.net

This file is part of XreaL source code.

XreaL source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

XreaL source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with XreaL source code; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/

/\* depthtile1_fp.glsl */

uniform sampler2D u_DepthMap;
varying vec3 unprojectionParams;

uniform vec3 u_zFar;

const vec2 pixelScale = r_FBufScale;
# if **VERSION** > 120

out vec4 outputColor;
# else
# define outputColor gl_FragColor
# endif

vec4 depthToZ(in vec4 depth) {
  return unprojectionParams.x / ( unprojectionParams.y \* depth - unprojectionParams.z );
}

float max16(in vec4 data0, in vec4 data1, in vec4 data2, in vec4 data3) {
  vec4 max01 = max(data0, data1);
  vec4 max23 = max(data2, data3);
  vec4 max4 = max(max01, max23);
  vec2 max2 = max(max4.xy, max4.zw);
  return max(max2.x, max2.y);
}

void    main()
{
  vec2 st = gl_FragCoord.st \* 4.0 \* pixelScale;
  vec4 depth[4], mask[4];
# ifdef HAVE_ARB_texture_gather

  depth[0] = textureGather( u_DepthMap, st + vec2(-1.0, -1.0) \* pixelScale );
  depth[1] = textureGather( u_DepthMap, st + vec2(-1.0,  1.0) \* pixelScale );
  depth[2] = textureGather( u_DepthMap, st + vec2( 1.0,  1.0) \* pixelScale );
  depth[3] = textureGather( u_DepthMap, st + vec2( 1.0, -1.0) \* pixelScale );
# else

  depth[0] = vec4(texture2D( u_DepthMap, st + vec2(-1.5, -1.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2(-1.5, -0.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2(-0.5, -0.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2(-0.5, -1.5) \* pixelScale ).x);
  depth[1] = vec4(texture2D( u_DepthMap, st + vec2( 0.5, -1.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2( 0.5, -0.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2( 1.5, -0.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2( 1.5, -1.5) \* pixelScale ).x);
  depth[2] = vec4(texture2D( u_DepthMap, st + vec2( 0.5,  0.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2( 0.5,  1.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2( 1.5,  1.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2( 1.5,  0.5) \* pixelScale ).x);
  depth[3] = vec4(texture2D( u_DepthMap, st + vec2(-1.5,  0.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2(-1.5,  1.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2(-0.5,  1.5) \* pixelScale ).x,
          texture2D( u_DepthMap, st + vec2(-0.5,  0.5) \* pixelScale ).x);
# endif

  mask[0] = 1.0 - step(1.0, depth[0]);
  mask[1] = 1.0 - step(1.0, depth[1]);
  mask[2] = 1.0 - step(1.0, depth[2]);
  mask[3] = 1.0 - step(1.0, depth[3]);

  float samples = dot( mask[0] + mask[1] + mask[2] + mask[3], vec4(1.0) );
  if ( samples > 0.0 ) {
    samples = 1.0 / samples;

```
depth[0] = depthToZ(depth[0]);
depth[1] = depthToZ(depth[1]);
depth[2] = depthToZ(depth[2]);
depth[3] = depthToZ(depth[3]);

float minDepth = - max16( mask[0] * (-depth[0]),
              mask[1] * (-depth[1]),
              mask[2] * (-depth[2]),
              mask[3] * (-depth[3]) );

depth[0] *= mask[0];
depth[1] *= mask[1];
depth[2] *= mask[2];
depth[3] *= mask[3];

float maxDepth = max16( depth[0], depth[1], depth[2], depth[3] );

float avgDepth = dot( depth[0] + depth[1] + depth[2] + depth[3],
          vec4( samples ) );

depth[0] -= avgDepth * mask[0];
depth[1] -= avgDepth * mask[1];
depth[2] -= avgDepth * mask[2];
depth[3] -= avgDepth * mask[3];

float variance = dot( depth[0], depth[0] ) + dot( depth[1], depth[1] ) +
  dot( depth[2], depth[2] ) + dot( depth[3], depth[3] );
variance *= samples;
outputColor = vec4( maxDepth, minDepth, avgDepth, sqrt( variance ) );
```

  } else {
    // found just sky pixels
    outputColor = vec4( 99999.0, 99999.0, 99999.0, 0.0 );
  }
}

Warn: Compile log:
(0) : error C7011: implicit cast from "int" to "ivec2"

Warn: Built-in shaders failed: Couldn't compile fragment shader: depthtile1 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.50.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.49.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.48.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.47.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.46.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.45.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.44.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.43.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.42.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.41.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.40.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.39.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.38.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.37.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.36.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.35.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.34.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.33.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.32.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.31.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.30.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.29.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.28.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.27.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.26.0.pk3'... 
[FS] Loading pak '/home/incognito/.unvanquished/pkg/unvanquished_0.25.0.pk3'...
```

**Comment by Incognito4nonymous** [comment] 2016-11-02 16:49
Solved by downloading the game from Moddb.

**Comment by Viech** [comment] 2016-11-06 14:01
The version on ModDB is severly outdated though. Your error seems to be `extension 'GL_EXT_texture_integer' unsupported in vertex shader`. What's your GPU @Incognito4nonymous?

**Comment by gimhael** [comment] 2016-11-06 21:06
This is not a driver issue, the OpenGL extension GL_EXT_texture_integer defines just the *OpenGL* functions to work with integer textures, but the *GLSL* functions for integer textures are defined in GL_ext_gpu_shader4 (what a mess!). The GL_EXT_texture_integer GLSL extension simply doesn't exist. Some drivers don't complain and ignore it, others (correctly) fail to compile the shader.

This has been fixed in the sources with commit https://github.com/Unvanquished/Unvanquished/commit/1095f1719dc8ae4d17761a676a9ae1774367d42b, we just have to provide newer binaries.

**Comment by Incognito4nonymous** [comment] 2016-11-06 21:32
OH, YEAH !
I have a GeForce GT 335 M as stated above ;)

**Comment by illwieckz** [comment] 2016-11-06 22:35
There is an updater: https://github.com/Unvanquished/updater/releases (downloads only missing and can use torrent too)

**Comment by Incognito4nonymous** [comment] 2016-11-12 22:26
I'll just await for a new archive then. :)

**Comment by illwieckz** [comment] 2020-09-04 22:10
I reproduced the bug with a Quadro NVS 300. We currently test for the `Geforce` string to apply the workaround and then `NVS` does not match. I noticed both GPU are using the `340` version of the driver, it may be better to look for it instead.

**Comment by illwieckz** [comment] 2020-09-05 00:06
Closing this because it is reopened on Dæmon's side instead, see https://github.com/DaemonEngine/Daemon/issues/368.

**Closed** 2020-09-29 21:11 UTC
Labels: A-Renderer
