### ISSUE TITLE
unv lacks visual clarity

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1656] opened 2021-12-31 02:33 UTC
Quotes from IRC:

```
IMHO UNv lacks clarity. Super hard to make out enemies on the background... it's all a mush. And the different sizes of the aliens does not help with that either.
...
I don't thing the HUD is a problem, although buying upgrades could be a bit more intuitive
...
like the tabs for weapons and armor is confusing, and the entire "why can I buy upgrades or not" is not reallt self-evident
```

**Comment by Gireen** [comment] 2022-01-01 15:04
What is the purpose of this issue? 
One might say this issue lacks clarity. 😜

We have a dedicated forum for feedback which i think you are aware of. 
If random players leave feedback on the issue tracker it might be acceptable.
But developers and contributors should know that there is a better place for this.

To address this issue.
The art style of unv is supposed to be realistic 
the rest is more or less a duplicate of your own issues #1467 and #1491 which you might have forgotten 🤨

**Comment by bmorel** [comment] 2022-01-01 15:07
The purpose of this issue it to try to bring some activity on that topic, to get more ideas on the actual problem that I didn't explained because I can not define it, and much more.
The forum exists, and yes, I'm aware about it, but stuff in forum can't be referenced to issues or PRs.

**Comment by Gireen** [comment] 2022-01-01 15:28
> The purpose of this issue it to try to bring some activity on that topic, to get more ideas on the actual problem that I didn't explained because I can not define it, and much more.

Thats exactly what a forum is about. 

>  The forum exists, and yes, I'm aware about it, but stuff in forum can't be referenced to issues or PRs.

Sure. You can create an issue if you have found what the problem should be and link to the detailed forum discussion.

**Comment by bmorel** [comment] 2022-01-01 15:31
One of the problems is the lack of outline around icons and generally the HUD items.Let's make this issue about "just" that.

**Comment by Gireen** [comment] 2022-01-01 15:35
Thats literally no where in your quote.
And duplicate of 
#1300 #559

**Comment by necessarily-equal** [comment] 2022-01-05 14:08
I mean, I think everybody agrees on that, but this issue is totally not actionable. This means it's really hard to know what to do next or to consider it done — and thus this kind of issue tend to stay open forever. I'm quite tempted to close it for this reason.

**Closed** 2022-01-05 20:09 UTC
