### ISSUE TITLE
Floor fires burn infinitely.

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#844] opened 2015-11-20 01:48 UTC
Hi, I was surprised to see an unvanquished process eating 80% of one core on my game server, I joined, and I found a game running since more than 1400 hours, with bots stucks.

The server was not stalled, but I found something very strange. In three places, there was fire on ground burning.

Look at those awesome shots:

![burn!](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_021832_000.jpg)
![burn!](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_021850_000.jpg)
![burn!](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_021915_000.jpg)
![burn!](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_022705_000.jpg)
![burn!](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_022729_000.jpg)

Look at that awesome log:

```
 29:38 ClientDisconnect: 7 [---------------] (--------------------------------) "Enbaldur"
 29:51 Die: 0 4 MOD_BURN 1 2: Enbaldur killed [bot] Soizic; [bot] Malo assisted
 29:56 Die: 0 5 MOD_BURN 1 2: Enbaldur killed [bot] Nolwen; [bot] Malo assisted
 30:14 Die: 0 5 MOD_BURN 1 2: Enbaldur killed [bot] Nolwen; [bot] Malo assisted
 30:46 Die: 0 5 MOD_BURN 1 2: Enbaldur killed [bot] Nolwen; [bot] Malo assisted
 31:16 Die: 0 5 MOD_BURN 1 2: Enbaldur killed [bot] Nolwen; [bot] Malo assisted
 31:57 Die: 0 4 MOD_BURN 1 2: Enbaldur killed [bot] Soizic; [bot] Malo assisted
 32:25 Die: 0 4 MOD_BURN 1 2: Enbaldur killed [bot] Soizic; [bot] Malo assisted
 32:38 Die: 0 4 MOD_BURN 1 2: Enbaldur killed [bot] Soizic; [bot] Malo assisted
 33:16 Die: 0 4 MOD_BURN 1 2: Enbaldur killed [bot] Soizic; [bot] Malo assisted
 33:34 Die: 0 5 MOD_BURN 1 2: Enbaldur killed [bot] Nolwen; [bot] Malo assisted
 34:03 Die: 0 5 MOD_BURN 1 2: Enbaldur killed [bot] Nolwen; [bot] Malo assisted
 34:25 Die: 0 4 MOD_BURN 1 2: Enbaldur killed [bot] Soizic; [bot] Malo assisted
 35:43 Die: 0 6 MOD_BURN 1 2: Enbaldur killed [bot] Lena; [bot] Malo assisted
 38:21 Die: 0 6 MOD_BURN 1 2: Enbaldur killed [bot] Lena; [bot] Malo assisted
 40:28 Die: 0 5 MOD_BURN 1 2: Enbaldur killed [bot] Nolwen; [bot] Malo assisted
 41:19 Die: 0 4 MOD_BURN 1 2: Enbaldur killed [bot] Soizic; [bot] Malo assisted
 42:46 Die: 0 6 MOD_BURN 1 2: Enbaldur killed [bot] Lena; [bot] Malo assisted
 42:48 Die: 0 5 MOD_BURN 1 2: Enbaldur killed [bot] Nolwen; [bot] Malo assisted
 43:01 Die: 0 5 MOD_BURN 1 2: Enbaldur killed [bot] Nolwen; [bot] Malo assisted
```

Yes, Enbladur killed 19 bots _after he quits_, and the last one _14 minutes after he quits_.

And Yes, first flames were thrown before the first 10 minute of game time, so while I'm typing, the fire is virtually burning since more than 1440 hours (but burning my CPU for real).

**Comment by illwieckz** [comment] 2015-11-20 02:23
It looks like the fire slowly reduce then…
![fire!](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_032045_000.jpg)

boom!
![fire!](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_032155_000.jpg)

**Comment by illwieckz** [comment] 2015-11-20 03:18
I also noticed that some fire effect on some bullet impact (unrelated to the weapon itself), and around the player, but the fire on impact and around the player is safe.

![fire](http://dl.illwieckz.net/b/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_033622_000.jpg)
![fire](http://dl.illwieckz.net/b/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_033710_000.jpg)
![fire](http://dl.illwieckz.net/b/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_033733_000.jpg)
![fire](http://dl.illwieckz.net/b/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_033812_000.jpg)
![fire](http://dl.illwieckz.net/b/unvanquished/bugs/infinite-fire/unvanquished_2015-11-20_033852_000.jpg)

**Comment by illwieckz** [comment] 2015-11-20 04:17
It looks like the surrounding fire and the impact fire are related to the fact I walked on fire before.

**Comment by Kangz** [comment] 2015-11-20 15:27
It seems like it might be reusing entities and not clearing them properly. As for the infinite fire bug, this is unfortunate, maybe we should have a max lifetime for the pieces of fire?

**Comment by Viech** [comment] 2015-11-20 17:27
This looks like three dependent bugs.

1. The **fire not going out** (and dealing more damage than usual) likely means that fires now stacks on top of each other, which they aren't supposed to do. There should be a minimum distance between fire entities. This is a regression in the CBSE merge, most likely. Note that, if fire entities are close to each other, they reduce each others chances of going out. Hence stacking fires explain infinite fires.

2. The visual bug where **fire effects appear where they shouldn't** may be triggered by the sheer amount of fire entities on the map. Could be server side bug where entity slots aren't reset properly when they're reused. Could also be a client side particle system overflow. Either way this would need to get fixed independently of (1).

3. The **fire not showing** for a while then suddenly reappearing could either be explained with client side problems as (2) or it could be a server side bug more closely related to (3): Maybe the floor fires in question actually went off but were re-ignited (which shouldn't be possible as floor fires that go out should be removed entirely). Note that there is no code that would allow floor fires to actually *spawn* other floor fires.

I'll shorten the log above a bit for readability.

**Closed** 2015-11-27 13:16 UTC
Labels: A-Client, A-Gamelogic, A-Renderer, S-Verified, T-Bug

**Comment by Viech** [comment] 2015-11-27 13:18
As the commit says, this *might* fix the issue. Please reopen if you can still reproduce.
