### ISSUE TITLE
Infinite scoreboard

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2099] opened 2022-08-24 21:02 UTC
If a game ends while a player is still downloading packages for it, this player is stuck with the scoreboard shown infinitely on the next map, until doing /reconnect. This happens regularly and I suspect it happens every time.

**Comment by illwieckz** [comment] 2022-08-24 21:06
I believe this is a duplicate of:

- https://github.com/Unvanquished/Unvanquished/issues/1102

And yes the bug is old, it's sad we didn't fixed it yet. 🤭️

**Comment by DolceTriade** [comment] 2022-08-28 03:24
Were you already in the end game when this happened? Did you load the same map again after?

**Comment by DolceTriade** [comment] 2022-09-14 10:05
Closing in favor of #1102

**Closed by DolceTriade** 2022-09-14 10:05 UTC
Labels: A-UI, S-Duplicate
