### ISSUE TITLE
Building over eggs / telenodes destroys building

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#564] opened 2015-02-04 02:14 UTC
Building over eggs / telenodes destroys building, you lose the buildpoints and you have to wait your timer.
Can be a little frustrating when you're trying to squeeze an unorthodox base into a tight space.

**Comment by Viech** [comment] 2015-02-04 14:03
This is a duplicate of #286.

**Closed by Viech** 2015-02-04 14:03 UTC
