### ISSUE TITLE
Weapon ready sound still plays if weapon out of ammo.

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#611] opened 2015-02-17 03:10 UTC
Nothing serious, just strange.

**Comment by Viech** [comment] 2015-02-17 10:53
Looked into it but found no easy/non-hackish way to solve this as the client shouldn't know whether an enemy is out of ammo for weapons that do not have a ready sound and the server doesn't load the configuration that would tell it whether a ready sound exists for the given weapon.

**Comment by bmorel** [comment] 2021-09-27 11:16
Would be nice to have a way to reproduce this (ideally, alone, written in text or some way which won't disappear with time)

**Comment by illwieckz** [comment] 2021-09-27 11:23
Get a lucifer cannon, fire everything. Listen to the sound it still makes.

On the other hand I don't find this problematic. The weapon not having ammo does not necessarily mean it is offline. I always heard that sound as the generic idle noise of the weapon machinery, without it being related to having ammo or not.

**Comment by bmorel** [comment] 2021-09-28 16:53
Wait, this was about the humming of the luci, which I never noticed before you described it and put all sound at max (I didn't noticed the name changing)?!?
If yes, I agree that it is not a bug. The bug would rather be the fact that I never noticed it :D

I also think that idle sound of weapons (which only affect luci so far?) should not be disabled when out of ammo.
I think we should close this, or tag as won't fix, not sure?

**Comment by illwieckz** [comment] 2021-09-28 17:26
We may reopen the issue if someone genuinely asks it again thinking it's wrong. We can even set in lore that the lucifer cannon needs its own energy to operate, not relying on the energy used for the projectile to drive its own operation. And even the blaster can get energy from thin air so… We may assume the lucifer cannon being on and the lucifer cannon having ammo are to different things.

**Closed** 2021-09-28 17:26 UTC
Labels: A-Gamelogic, T-Bug
