### ISSUE TITLE
missing texture but no warning message

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#776] opened 2015-07-25 23:15 UTC
**Edit: the example above was a false positive. See [this comment](https://github.com/Unvanquished/Unvanquished/issues/776#issuecomment-151153560) to get real use cases instead.**

For history, this message was:

> Sometime, some textures are missings, like in this screenshot:
> 
> ![missing texture](http://dl.illwieckz.net/b/unvanquished/bugs/unvanquished_2015-07-26_004818_000.jpg)
> But in some case (like in this screenshot), uvnanquished does not complain at all.
> 
> I don't know yet where is the problem, perhaps it's a shader issue. I've experienced many similar issues in my attempt to port tremulous maps, many missing textures are not reported.
> 
> I will investigate more to find in which case it is happening.

**Comment by illwieckz** [comment] 2015-07-29 21:50
Hmm, this screenshot is a false positive, this one seems to be a lightmap issue. But I have sometime some real missing textures without message (perhaps textures called by shaders or models, not directly called by the bsp).

**Comment by DolceTriade** [comment] 2015-07-29 22:24
Are you sure it isn't the same issue. If it is, it would probably require a debugger to step through the loading process to see where it returns early.

**Comment by illwieckz** [comment] 2015-07-29 22:41
I'm not sure since I've not found the good lightmap, but I think this weird pattern is in a lightmap itself, it looks like a shadow and it does not appear when I load the map without lightmaps.

But I agree about the debugger, I have an issue on a map where Unvanquished complains about a missing shader that is not missing: http://forums.unvanquished.net/viewtopic.php?f=9&t=1782 . Sometime Unvanquished complains about missing textures that are not missing, and sometime it does not complains about missings textures that are missing. But I don"t know how to trace it properly.

**Comment by Viech** [comment] 2015-10-23 14:35
Is this a duplicate of #782?

**Comment by illwieckz** [comment] 2015-10-26 14:23
They are definitely not.

Just one thing, the missing texture in initial post was a false positive (the problem was a bad generated lightmap, so the problem was at build time, not at run time, see [this forum post](http://forums.unvanquished.net/viewtopic.php?f=9&t=1888#p16287)).

But this bug is about real issues that have wrong, meaningless or missing error message like.

You can see:

* #799 `“some pending renderer regressions introduced in alpha 38 and alpha 40”`
* #780 `“Some fire/smoke effect broken since alpha 30 (vertexpack merge)”`
* #806 `“R_FindShader looks unnecessarily for filenames that does not exist then abort”` (and the related [forum post](http://forums.unvanquished.net/viewtopic.php?f=9&t=1782))

Apart they all are different bugs, these three issues reveals wrong, meaning less or missing feedback.

The #782 issue `“Internal lightmaps have blending issue and light spill out #”` is about lightmap issue too and is close to other bugs, but in this case there is no problem about wrong, meaningless or missing error message, which is the current issue.

**Comment by slipher** [comment] 2023-12-08 09:50
Well, all the above bugs have their own issues and only one of them is still open so I guess we can close this.

**Closed by slipher** 2023-12-08 09:50 UTC
Labels: A-Renderer, T-Verbosity
