### ISSUE TITLE
Fail to load VM when starting local game

### ISSUE THREAD

**Issue by theharlockglitch** [Unvanquished/Unvanquished#515] opened 2015-01-10 09:23 UTC
On Ubuntu 14.04 LTS, amd64 running on a Intel Pentium Dual Core T3200, with 3GB of RAM. I think the info on the log about my Graphics Card & Drivers would be more accurate than I could provide.

```
user@u-notebook:~$ LANG=C unvanquished +nocurses
Unvanquished 0.35.0 Linux x86_64 Jan  5 2015
+set fs_libpath /usr/lib/games/unvanquished +set fs_basepath /var/games/unvanquished  
Home path: /home/gnubik/.unvanquished 
Pak path: /var/games/unvanquished/pkg 
Pak path: /home/gnubik/.unvanquished/pkg 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
Loaded 9 languages 
execing 'default.cfg' 
execing 'autogen.cfg' 
execing 'keybindings.cfg' 
Set language to Spanish 
----- Client Initialization ----- 
----- Client Initialization Complete ----- 
Calling GetRefAPI… 
SDL_Init( SDL_INIT_VIDEO )...  
Using SDL Version 2.0.2 
SDL using driver "x11" 
Initializing OpenGL display 
Display aspect: 1.600 
...setting mode -1: 
 1280 800 
Using 24 Color bits, 24 depth, 8 stencil display. 
Using GLEW 1.10.0 
Using enhanced (GL3) Renderer in GL 3.x mode... 
Available modes: '1280x800 ' 
GL_RENDERER: GeForce 9200M GS/PCIe/SSE2 
Detected graphics driver class 'OpenGL 3+' 
Detected graphics hardware class 'generic' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...using GL_ARB_fragment_shader 
...using GL_ARB_vertex_shader 
...using GL_ARB_shading_language_100 
...found shading language version 330 
...using GL_ARB_depth_texture 
...using GL_ARB_texture_cube_map 
...using GL_ARB_half_float_pixel 
...using GL_ARB_texture_float 
...using GL_ARB_texture_rg 
...using GL_EXT_packed_depth_stencil 
...ignoring GL_ARB_texture_compression 
...ignoring GL_EXT_texture_compression_s3tc 
...using GL_ARB_texture_non_power_of_two 
...using GL_SGIS_generate_mipmap 
...ignoring GL_EXT_texture_filter_anisotropic 
...using GL_ARB_vertex_buffer_object 
...using GL_ARB_half_float_vertex 
...using GL_EXT_framebuffer_object 
...using GL_EXT_framebuffer_blit 
...using GL_ARB_shader_objects 
...using GL_ARB_occlusion_query 
...using GL_ARB_draw_buffers 
...GL_GREMEDY_string_marker not found 
...using GL_ARB_get_program_binary 
...GL_ARB_buffer_storage not found 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
 
GL_VENDOR: NVIDIA Corporation 
GL_RENDERER: GeForce 9200M GS/PCIe/SSE2 
GL_VERSION: 3.3.0 NVIDIA 331.113 
GL_SHADING_LANGUAGE_VERSION: 3.30 NVIDIA via Cg compiler 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 4096 
Using OpenGL 3.x context 
Using GPU vertex skinning with max 128 bones in a single pass 
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf). 
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf). 
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf). 
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf). 
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf). 
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf). 
--- Common Initialization Complete --- 
Loaded GeoIP data: IPv4 IPv6 
IP: 127.0.0.1 
IP: 192.168.0.100 
IP6: ::1 
IP6: fe80::221:ff:fe83:1209%wlan0 
Opening IP6 socket: [::]:* 
Opening IP socket: 0.0.0.0:* 
Loading pak '/var/games/unvanquished/pkg/map-yocto_b2c+1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-all_2.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-common_2.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-ej01-clean_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-ej01-common_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-ej01-ice_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-ex_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-exm_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-pk01_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-pk02_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-space_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-tech_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-trak5_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/map-station15_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/map-thunder_b3+2.pk3'... 
Loading pak '/var/games/unvanquished/pkg/map-perseus_b5a+1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/map-spacetracks_1.0+1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/map-parpax_d04.pk3'... 
Loading pak '/var/games/unvanquished/pkg/map-chasm_b1+2.pk3'... 
Loading pak '/var/games/unvanquished/pkg/map-plat23_b13+1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/map-forlorn_a10.pk3'... 
Loading pak '/var/games/unvanquished/pkg/map-antares_a03+1.pk3'... 
[skipnotify]10 arenas parsed 
----- Server Initialization ----- 
Server: antares 
Calling GetRefAPI… 
 
GL_VENDOR: NVIDIA Corporation 
GL_RENDERER: GeForce 9200M GS/PCIe/SSE2 
GL_VERSION: 3.3.0 NVIDIA 331.113 
GL_SHADING_LANGUAGE_VERSION: 3.30 NVIDIA via Cg compiler 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 4096 
Using OpenGL 3.x context 
Using GPU vertex skinning with max 128 bones in a single pass 
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf). 
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf). 
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf). 
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf). 
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf). 
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf). 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
Loading RSA keys from pubkey 
Daemon RSA public-key found. 
IP: 127.0.0.1 
IP: 192.168.0.100 
IP6: ::1 
IP6: fe80::221:ff:fe83:1209%wlan0 
Opening IP6 socket: [::]:27960 
Opening IP socket: 0.0.0.0:27960 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/map-antares_a03+1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-all_2.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-common_2.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-ej01-clean_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-ej01-common_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-ej01-ice_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-ex_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-exm_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-pk01_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-pk02_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-space_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-tech_1.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/tex-trak5_1.0.pk3'... 
Loading VM module game-x86_64.nexe... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
VM: Failed to exec: No such file or directory 
----- Server Shutdown ----- 
IP: 127.0.0.1 
IP: 192.168.0.100 
IP6: ::1 
IP6: fe80::221:ff:fe83:1209%wlan0 
Opening IP6 socket: [::]:* 
Opening IP socket: 0.0.0.0:* 
--------------------------- 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
Calling GetRefAPI… 
 
GL_VENDOR: NVIDIA Corporation 
GL_RENDERER: GeForce 9200M GS/PCIe/SSE2 
GL_VERSION: 3.3.0 NVIDIA 331.113 
GL_SHADING_LANGUAGE_VERSION: 3.30 NVIDIA via Cg compiler 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 4096 
Using OpenGL 3.x context 
Using GPU vertex skinning with max 128 bones in a single pass 
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf). 
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf). 
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf). 
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf). 
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf). 
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf). 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.1.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
user@u-notebook:~$
```

Note that the 'VM: Failed to exec: No such file or directory ' Is the error given by the game, in a window title, when fails to start the local game.

After updating to 35, I manually downloaded 35.1.pkg and put it on the right folder. Any problems when playing online. Just tryied to start local game yesterday and noticed the issue.

**Comment by illwieckz** [comment] 2015-01-10 11:53
I got the same problem while trying to host a dedicated server.

0.35.0 ubuntu package + 0.35.1 pk3 does'nt launch and fails with this error, but brand new "universal zip" 0.35.1 installation runs well.

I Didn't tried "universal zip" 0.35.1 locally (ubuntu package + pk3 here).

**Comment by Viech** [comment] 2015-01-11 15:57
> 0.35.0 ubuntu package + 0.35.1 pk3 does'nt launch and fails with this error, but brand new "universal zip" 0.35.1 installation runs well.

The 0.35.1 multi-platform package is really just the 0.35.0 version with `unvanquished_0.35.1.pk3` added:

    % diff -r unvanquished_0.35.0/ unvanquished_0.35.1/ 
    Only in unvanquished_0.35.0/pkg: md5sums0.35
    Only in unvanquished_0.35.1/pkg: md5sums0.35.1
    Only in unvanquished_0.35.1/pkg: unvanquished_0.35.1.pk3

So it seems to be an OpenSUSE build/package issue. This issue is probably a duplicate of #512, where @Amanieu asked:

> Check if sel_ldr is present, it is required to load the NaCl VMs.

**Comment by Viech** [comment] 2015-04-27 11:44
I'm closing this in favor of #512 since it's likely a duplicate and no further input was provided here.

**Closed by Viech** 2015-04-27 11:44 UTC
Labels: A-Distribution, OS-Linux, S-Needs-Input, T-Bug
