### ISSUE TITLE
Unvanquished 0.53.1 release thread

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2029] opened 2022-08-04 00:14 UTC
## PRs to merge

- launcher PRs
  * [x] https://github.com/Unvanquished/updater/pull/103
- game PRs
  * [x] https://github.com/Unvanquished/RmlUi/pull/3
  * [x] commit RmlUi submodule
  * [x] https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/145

## Release process

- [x] Write a short blog post
- Build launcher release
  * [x] rebuild and package Linux build
  * [x] rebuild and package Window build
  * [x] rebuild and package macOS build
- Build game release
  * [x] rebuild `nexe`
  * [x] repackage `unvanquished_src.dpkdir`
  * [x] repackage unizip: merge unvanquiqhed dpk and new nexe symbols to 0.53.0 unizip and name it 0.53.1
  * [x] tag every submodule of Unvanquished and UnvanquishedAssets with `unvanquished/0.53.0`
  * [x] tag Urcheon
  * [x] update flatpak
- Set up launcher distribution
  * [x] push v0.2.0 updater tag
  * [x] create GitHub draft release
  * [x] Upload to GitHub as draft release
  * [x] publish the GitHub release
  * [x] Preconfigure updater version as 0.2.0
- Set up game distribution
  * [x] Upload unizip to dl.unvanquished.net
  * [x] Run script to convert unizip to torrent in cdn.unvanquished.net
  * [x] Run script to publish torrent
  * [x] Make sure CDN mirrors mirrored
  * [x] push v0.53.1 Unvanquished tag
  * [x] create GitHub draft release
  * [x] Upload to GitHub as draft release
  * [x] Preconfigure game version as 0.53.1
- Server update
  * [x] copy 0.53.1 .dpk files to `dl.unvanquished.net/pkg`
  * update US unvanquished.net server
    - [x] unzip unvanquished_0.53.1.zip
    - [x] unzip linux-amd64.zip
    - [x] set unvanquished_0.53.1 as default
    - [x] edit hostname to set 0.53.1 version
    - [x] restart game server
  * update EU gg.illwieckz.net server
    - [x] unzip unvanquished_0.53.1.zip
    - [x] unzip linux-amd64.zip
    - [x] set unvanquished_0.53.1 as default
    - [x] edit hostname to set 0.53.1 version
    - [x] restart game server
- Announce the update
  * [x] publish the GitHub game release
  * [x] publish the GitHub launcher release
  * [x] Run script to set default downloads according to preconfigured versions
  * [x] Publish blog post
  * [x] `@everyone` message on chat

## Game post-release things

- [x] Social medias
  * [x] Write and publish Facebook post
  * [x] Write and publish Twitter post
  * [x] Write and publish Reddit post
- [x] Paste social media posts as a comment under the blog post
- [x] Tell FOSS Torrents about the release
- mirror the downloads
  * [x] Upload launcher to SourceForge.net as a backup
  * [x] Set new launcher as default download on SourceForge.net
  * [x] Upload game to SourceForge.net as a backup
  * [x] Upload launcher to IndieDB as a backup
  * [x] Pin new launcher on top of IndieDB download page
  * [x] Upload game to IndieDB as a backup

## Unneeded things

- No need to copy blog post to IndieDB as the 0.53.0 isn't copied yet, we will just copy 0.53.0 blog post and link 0.53.1 download.
- No need to write a french article for LinuxFr.org as 0.53.0 isn't published yet, we will just publish the 0.53.0 one with link to 0.53.1 download.

**Comment by necessarily-equal** [comment] 2022-08-04 10:12
* @bmorel would like to include https://github.com/Unvanquished/Unvanquished/pull/1979
* not a bugfix, but @bmorel would like the position hud thing to be merged
* I'd like to include the first commit from https://github.com/Unvanquished/Unvanquished/pull/1955 because it fixes a memory unsafe read.
* I'd like to include https://github.com/Unvanquished/Unvanquished/pull/2032 because it is embarassing :S
* If we do a daemon release too, I think we should include https://github.com/DaemonEngine/Daemon/pull/674. @DaVinciCode2 did fix the bug and did us the courtesy of creating a GitHub account despite not wanting to because it made things easier for us.

**Comment by illwieckz** [comment] 2022-08-04 17:04
This is already approved and small so why not:

- https://github.com/Unvanquished/Unvanquished/pull/1979

If that's really annoying, why not:

- https://github.com/Unvanquished/Unvanquished/pull/2034

This sounds legit:

- First commit from https://github.com/Unvanquished/Unvanquished/pull/1955 because it fixes a memory unsafe read.

Everything else can be postponed. I also assume @DaVinciCode2 can build his own engine and then can run it.

We can make a point release for things like position hud, engine rebuild, etc. on September 4th (yay, monthly release!)

**Comment by slipher** [comment] 2022-08-04 18:46
We need to disable the oxygen bar because the algorithm for computing it is still wrong after https://github.com/Unvanquished/Unvanquished/pull/2034. It only uses surfacing or submerging events, which means it doesn't take into account:
- dying while underwater
- switching followed player while spectating
- leaving the team

**Comment by DaVinciCode2** [comment] 2022-08-04 20:58
> Everything else can be postponed. I also assume @DaVinciCode2 can build his own engine and then can run it.

i already tested it yes. it's a small network bug who divide the ports range by 2.

**Comment by illwieckz** [comment] 2022-08-04 21:47
I meant I assume you don't need us to release a new engine build for you to build and use the new engine with your fix, so we can merge your fix without making it an urge to repackage an engine.

**Comment by bmorel** [comment] 2022-08-04 21:49
While this is true, I wonder if a workaround could be found to limit @DaVinciCode2 's problems. He's likely not the only one suffering them, only the only one reporting them

**Comment by DaVinciCode2** [comment] 2022-08-04 22:56
> I meant I assume you don't need us to release a new engine build for you to build and use the new engine with your fix, so we can merge your fix without making it an urge to repackage an engine.

@illwieckz if it was so simple yes, but this code fix is also for the client, who use the daemon code, if server parse/manipulate port number the good way but not the client, it don't work at all (debug printf showed me that the signedness of swap16 gave the same value for all port's numbers higher to 2**15 as if integers were on 15 bits, so clients would try to connect to a bad port number). This fix is not to play alone (if players of the community want to play some modded party with me, if it works without lag, etc)


> While this is true, I wonder if a workaround could be found to limit @DaVinciCode2 's problems. He's likely not the only one suffering them, only the only one reporting them
> 
> [edit] And FIXING them!

in fact, it's worse than that, the documentation for port change and ipv6 is hard to find, (a lot of try and error to discover the need to use net_restart, and i found the var (set net_enabled 2) to activate ipv6 in an old server.cfg in a forgotten repository). The bug is after all that. Users just need a documentation before finding the bug.

postpone if you need time for testing, reviewing or editing the code. (i'm just a player of the game, my fix duplicate some function's code to be safe and avoid the fear of some maintainers to break the engine. But the good way of doing it, is to change all signature of swap16/swap32/swap64 for unsigned types, because, these functions are just broken as i said, endianness is untyped/unsigned concept as much as i know ...).

**Comment by illwieckz** [comment] 2022-08-04 23:24
> if server parse/manipulate port number the good way but not the client, it don't work at all

Ah… damn, sorry @DaVinciCode2 then, the 0.53.1 is already packaged. 😕️
I thought only fixing the engine for the server was enough…

I want the next release to be done on September 4th (in one month). So be sure your patch will be part of it! 👍️

**Comment by DaVinciCode2** [comment] 2022-08-04 23:54
you have the fix, now i can remove this github account (bye bye micro$oft), see you in game guys, and long life to unvanquished ;)

**Comment by illwieckz** [comment] 2022-08-04 23:57
> you have the fix, now i can remove this github account (bye bye micro$oft), see you in game guys, and long life to unvanquished ;)

One question though, do the email address you used was a real one or a dummy one?

**Comment by bmorel** [comment] 2022-08-05 11:16
to close or not to close, that is the question?

**Closed** 2022-08-11 06:06 UTC
Labels: T-Task

**Comment by illwieckz** [comment] 2022-08-14 08:17
The updater upload was not complete, we needed to also upload non-zipped `UnvanquishedUpdater.exe`.

- [x] `UnvUpdaterLinux.zip`
- [x] `UnvUpdaterOSX.zip`
- [x] `UnvUpdaterWin.zip`
- [x] `UnvanquishedUpdater.exe`

Now fixed, see:

- https://github.com/Unvanquished/updater/issues/107

**Comment by DolceTriade** [comment] 2022-08-14 08:20
Oops, thanks for fixing!

**Comment by illwieckz** [comment] 2022-08-14 08:20
We got i broken for 9 days, and it was reported on Facebook since a week and I didn't get a notice. What a failure! 😥️
