### ISSUE TITLE
Text color / alpha hard to read

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#559] opened 2015-02-04 01:35 UTC
Text is often impossible to read because it's small & it's gray on gray or gray alpha over gray etc.

See screenshots.
http://share.pho.to/8m9WP

I bet no one can read these things:
votes
buildpoints per minute
How many spawns are left!!
and lots more I can't remember.

And before you ask yes, all those screenshots are supposed to contain text!

**Comment by Viech** [comment] 2015-02-04 14:13
Part of the issue is your extreme gamma setting that reduces contrast but I agree that this needs to be improved.

**Comment by Veyrdite** [comment] 2015-11-17 05:34
Should we make gamma affect the UI?

**Comment by Viech** [comment] 2015-11-17 11:38
That's no good solution to a bad UI design.

**Comment by DolceTriade** [comment] 2015-11-17 17:11
Need to clean up UI or add borders/backgrounds to UI text.

**Comment by bmorel** [comment] 2021-09-27 11:04
freetype have support for outlines IIRC, but this would only solve the problems with text, many GUI elements suffer from this problem.

**Comment by bmorel** [comment] 2021-12-19 17:35
Another solution to outlines would be to print text on a semi-transparent rectangle which would be of opposite color (compared to text).
Note that this problem (and this solution?) also affects the bars, like the momentum/weapon charge bar, the poison capacity, etc etc

**Comment by necessarily-equal** [comment] 2022-06-16 23:10
I'll start working on the rest of this once https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/113 is merged.

**Closed** 2023-03-09 16:06 UTC
Labels: A-UI, T-Accessibility
