### ISSUE TITLE
Segmentation fault when hearing gun sounds on macOS

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#1228] opened 2020-10-11 11:12 UTC
There seems to be an issue where the game will crash with a segmentation fault when weapons are fired. The only way to reproduce this is to start a local game and fire the rifle. I am unable to join any of the three currently-online servers (illwieckz servers, and New EDGE) due to bots constantly shooting, and I get an immediate segfault upon joining the game.

OS: macOS Catalina 10.15.7

I have tried using a client built from git, and the release (0.51.1) builds.

**Comment by slipher** [comment] 2020-10-17 10:33
I reproduced the issue with a build based on the 0.52 branches. It occurs because GLEW provides null for the address of `glMapBufferRange`. I tried replacing the GLEW 1.12.0 dynamic library with a version 2.2 one, and this made the issue go away. So it should be solved by making a new external_deps package with a newer GLEW version.

**Comment by slipher** [comment] 2020-10-17 10:36
If you want to try it yourself, do `brew install glew` and replace the `libGLEW.1.12.0` file (in the same directory as `daemon`) with `/usr/local/Cellar/glew/2.2.0/lib/libGLEW.2.2.0.dylib` (you'll need to rename it to the same name as the original file).

**Comment by cu-kai** [comment] 2020-10-17 11:04
Yes, this worked for me, thank you @slipher!

It also means the game launches with an OpenGL 3.x context which I believe @illwieckz questioned on the discord.

**Comment by illwieckz** [comment] 2020-10-17 13:52
Oh, @cu-kai are you saying you get more than OpenGL 2 on the same macOS with that newer GLEW?

**Comment by cu-kai** [comment] 2020-10-17 20:35
Here is the `gfxinfo` output with the new GLEW...

![screenshot](https://media.discordapp.net/attachments/353835068139241483/766980924096905216/unknown.png)

**Comment by slipher** [comment] 2020-12-09 05:21
Fixed by #401 (on the 0.52 branch).

Make sure not to reuse an old cmake cache when building it.

**Closed by slipher** 2020-12-09 05:21 UTC
Labels: T-Bug
