### ISSUE TITLE
ROCKET_LIB compile errors

### ISSUE THREAD

**Issue by oyvindsaether** [Unvanquished/Unvanquished#1219] opened 2020-09-23 19:41 UTC
<pre>
[ 23%] Built target srclibs-minizip
[ 23%] Linking CXX executable cgame-native-exe
/usr/bin/ld: libROCKET_LIB.a(RocketContextsProxy.cpp.o): in function `Rocket::Core::Lua::LuaType<Rocket::Core::Context>::push(lua_State*, Rocket::Core::Context*, bool) [clone .isra.0]':
RocketContextsProxy.cpp:(.text+0x62): undefined reference to `lua_newuserdatauv'
/usr/bin/ld: libROCKET_LIB.a(Rocket.cpp.o): in function `Rocket::Core::Lua::LuaRocketGetAttrcontexts(lua_State*)':
Rocket.cpp:(.text+0xc8): undefined reference to `lua_newuserdatauv'
/usr/bin/ld: libROCKET_LIB.a(Rocket.cpp.o): in function `Rocket::Core::Lua::LuaRocketPushrocketGlobal(lua_State*)':
Rocket.cpp:(.text+0x194a): undefined reference to `lua_newuserdatauv'
/usr/bin/ld: libROCKET_LIB.a(Rocket.cpp.o): in function `Rocket::Core::Lua::LuaRocketCreateContext(lua_State*, Rocket::Core::Lua::LuaRocket*)':
Rocket.cpp:(.text+0x1bce): undefined reference to `lua_newuserdatauv'
/usr/bin/ld: libROCKET_LIB.a(Utilities.cpp.o): in function `Rocket::Core::Lua::PushVariant(lua_State*, Rocket::Core::Variant*)':
Utilities.cpp:(.text+0x800): undefined reference to `lua_newuserdatauv'
/usr/bin/ld: libROCKET_LIB.a(Utilities.cpp.o):Utilities.cpp:(.text+0xa6a): more undefined references to `lua_newuserdatauv' follow
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/cgame-native-exe.dir/build.make:1356: cgame-native-exe] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:180: CMakeFiles/cgame-native-exe.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2
</pre>

It doesn't get that far without fixing #1218 first.

**Comment by illwieckz** [comment] 2020-10-27 20:51
@slipher, is that fixed too?

**Comment by slipher** [comment] 2020-10-27 20:52
I didn't reproduce this one.

**Comment by bmorel** [comment] 2022-07-06 13:08
Will very likely be closed in 0.53 since no more librocket.

**Comment by necessarily-equal** [comment] 2022-07-18 20:17
I think we can assume that this issue has been fixed by $distro since then. If someone encounters this, please reopen or open another issue if the issue is similar but somewhat different.

**Closed by necessarily-equal** 2022-07-18 20:17 UTC
Labels: T-Bug, S-Old-Needs-Check
