### ISSUE TITLE
Rml migration: text too small in various places

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1833] opened 2022-06-07 13:32 UTC
Menu text is too small.
Chat text is too small.
Team selection and spawn selection texts are too small (not shown in following screenshots).
Alien build point counter is too small.
Human build point counter is normal.

There may be other stuff I've not noticed.

Screenshots from 0.52:

![2022-06-07-152508_1362x748_scrot](https://user-images.githubusercontent.com/1316300/172392800-0dab4155-2b80-4482-a03a-073624609eef.png)
![2022-06-07-152542_1362x748_scrot](https://user-images.githubusercontent.com/1316300/172392809-e6d2e730-654c-48e1-8314-16351b0b9111.png)
![2022-06-07-152549_1362x748_scrot](https://user-images.githubusercontent.com/1316300/172392812-8fa73afa-d579-4126-b192-2ab6b5163ee1.png)

Same, but for 0.53:

![2022-06-07-152759_1362x748_scrot](https://user-images.githubusercontent.com/1316300/172393012-2fa5af7b-bccd-40b2-8fe0-d0e7bad4f426.png)
![2022-06-07-152851_1362x748_scrot](https://user-images.githubusercontent.com/1316300/172393014-cbfbf659-426f-45b1-b5a9-d4d1e65bc907.png)
![2022-06-07-152914_1366x768_scrot](https://user-images.githubusercontent.com/1316300/172393015-b5926eb4-b5a5-4d27-b22e-12734127359b.png)

**Comment by necessarily-equal** [comment] 2022-06-07 21:59
Feels like a duplicate of https://github.com/Unvanquished/Unvanquished/issues/1819 to me. Maybe you want to copy-paste your message there

**Comment by bmorel** [comment] 2022-06-07 22:06
"default font size is too small" and "rml migration made text too small in *some* places" are different things to me.
The first one says the problem is everywhere, not related to rml (the title, at least, does not links to rml) while the 2nd makes it clear it's linked to rml, and that it does not affects everything.

**Comment by necessarily-equal** [comment] 2022-06-07 22:24
I'd say it's probably the same issue, because all the font sizes are 
relative, and then if rmlui changed the size by 12/16, then all the 
sizes have been affected. Now maybe some could use a… hum… "double 
fix", because they weren't that big in the first place.

**Comment by slipher** [comment] 2022-06-07 22:26
The size most certainly did not change by a constant factor. Some places the text size stayed about the same while in others it became extremely small.

**Comment by necessarily-equal** [comment] 2022-07-18 20:09
Fixed by https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/commit/895d11d11fe564980ccf9ca2e2c1c6b1b9893b92

**Closed by necessarily-equal** 2022-07-18 20:09 UTC
Labels: A-UI, T-Bug, T-Regression
