### ISSUE TITLE
implement a cvar to set default number of bots

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1923] opened 2022-07-19 10:15 UTC
Currently, to automatically fill maps with a number of bots, commands must be issued, and they must go in config/map/default.cfg or in one file per map, which is very tedious.

To have a CVar allowing to replace `/bot fill N` command, like, `g_bot_defaultFill` would allow to change this cvar's value directly in map rotation file, which is much less tedious, and allows to set this  number of bots depending on the number of players around.

**Comment by slipher** [comment] 2022-07-20 18:32
Duplicate of #1786.

If you want to put different numbers by setting a cvar, you can just make your own cvar and reference it in default.cfg. E.g. `set nbots 4` in the map rotation, and then `bot fill $nbots$` in default.cfg.

**Closed by slipher** 2022-07-20 18:32 UTC
Labels: A-Bots, T-Feature-Request

**Comment by bmorel** [comment] 2022-07-20 18:47
Agree on the duplicate.
About the config thing, does it means that we could also close the issue I duplicated by accident?
