### ISSUE TITLE
proposal  mesh networks

### ISSUE THREAD

**Issue by Pantyhose-X** [Unvanquished/Unvanquished#1809] opened 2022-05-28 06:54 UTC
I suggest using [mesh networks](https://en.wikipedia.org/wiki/Mesh_networking) to create a server. Unvanquished does not need to pay for the server
[yggdrasil](https://yggdrasil-network.github.io/)
[nebula](https://github.com/slackhq/nebula)
WebRTC p2p

**Comment by bmorel** [comment] 2022-05-28 06:56
Please describe a bit what a mesh network is, what are their technical requirements, and what it would provide to the game, so that people do not have to grep the internet to understand the basics of what you idea imply.

**Comment by Pantyhose-X** [comment] 2022-05-28 07:31
> Please describe a bit what a mesh network is, what are their technical requirements, and what it would provide to the game, so that people do not have to grep the internet to understand the basics of what you idea imply.

PRIMAVERA DE FILIPPI:

"An ad hoc network infrastructure that can be set up by anyone, mesh networks wirelessly connect computers and devices directly to each other without passing through any central authority or centralized organization (like a phone company or an ISP). They can automatically reconfigure themselves according to the availability and proximity of bandwidth, storage, and so on; this is what makes them resistant to disaster and other interference. Dynamic connections between nodes enable packets to use multiple routes to travel through the network, which makes these networks more robust.

Compared to more centralized network architectures, the only way to shut down a mesh network is to shut down every single node in the network.  [Reference](https://wiki.p2pfoundation.net/Mesh_Networks)

**Comment by Gireen** [comment] 2022-05-28 11:12
Anyone can host an Unvanquished servers, so there is no need for mesh networks.
~80% of the servers are currently provided by the community

**Comment by bmorel** [comment] 2022-05-28 11:25
I do not think anyone will be convinced to implement stuff by just 4 links and no description of the benefits it would bring.
Personally, I'm too lazy to go follow links on a random idea, my time contributing to unvanquished can be spent in much more useful ways, the mod I host on my servers can still use lot of work after all, and there, I know the direct benefit for players.

**Comment by Pantyhose-X** [comment] 2022-05-30 02:48
> I do not think anyone will be convinced to implement stuff by just 4 links and no description of the benefits it would bring. Imo, when someone asks for a feature, it's a minimum to write some text to explain how it would be of benefit to upstream. Linking to walls of texts on wikipedia or other sources is not really working.
> 
> Personally, I'm too lazy to go follow links on a random idea, my time contributing to unvanquished can be spent in much more useful ways, the mod I host on my servers can still use lot of work after all, and there, I know the direct benefit for players. Keep in mind that everything implemented in unvanquished and daemon is made by people giving their time to the community. This includes the handling of bugs, feature requests and even pull requests.

Everyone who installs unvanquished runs a mesh networks node,
Mesh networks node = server
Mesh networks node it can run an unvanquished server on a PC or a router

VPS is not required to run the server separately

**Comment by necessarily-equal** [comment] 2022-06-09 11:55
I don't think « mesh networks » are a suitable proposal in itself. Let me explain

1. We don't want more servers just for the sake of it. The only extra servers we may want are new mods like what Gireen or freem proposed, because they do provide new and interesting gameplay changes, or extra maps. Adding new flavorless servers in the list only makes the interesting servers less visible, so it's in average detrimental.
2. We don't pay anything extra for the servers that are running, and no matter if they servers are using mesh networking or not, you need to run them. So it's not so useful in that regard anyway. (And no I'm not going to run a server on my laptop, think of the terrible ping times and the extra battery use.)
3. The mesh network has to have great ping, because we are talking about a pretty nervous FPS. Anything that adds more than a few tens of ms of ping is a bad regression.
4. This raises a lot the complexity of the network setup, and the network setup is complex enough as is. It's already a pain to debug.
5. Both yggdrasil and nebula are apprently in Go, so we would need to add quite some dependencies to our dæmon engine to support it. This is not impossible, but this would need to be well-motivated as this would cause quite some work for everyone.
6. Most importantly, **yggdrasil and nebula are not libraries**. They are simply not meant to be added as part of another piece of software. You are supposed to set them up on your system like you would with a VPN, wireguard, tor or whatever other fancy network thingy.

So as a conclusion, **we probably don't want to add anything like "mesh network" inside the game or engine.** It should already work  if you did setup your system to use any of those. If  `unvanquished -connect $ip` doesn't already work with $fancy_network, it's probably a bug that may be fixed.

---

But I'd like to go back on WebRTC now. WebRTC is different because it's not a mesh network but merely a protocol that describes how one could do peer-to-peer video chat in a web browser. It was engineered around the fact that web browsers can't *receive* traffic because you would need to open ports in your firewall and typically setup NAT, which isn't something a web browser is allowed to do.

We definitely don't want to implement all of webRTC because we are a video game and not a video chat, but there is an interesting technology there that we can implement, [STUN](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Protocols#stun). That or we just implement UDP hole punching.

In all case, this could be useful to make it easier for anybody to host a quick WAN server, and this should be discussed in https://github.com/Unvanquished/Unvanquished/issues/1263.

I believe I addressed all the points here that aren't to be discussed in https://github.com/Unvanquished/Unvanquished/issues/1263, so I'm going to close this.

**Closed by necessarily-equal** 2022-06-09 11:55 UTC
Labels: T-Feature-Request
