### ISSUE TITLE
Maps load twice

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#583] opened 2015-02-09 23:43 UTC
Sometimes the map loads, and then it loads again.

**Comment by Viech** [comment] 2015-02-10 16:17
I can confirm that this happens client-side when connected to the Dev Server (didn't check others).

**Comment by Veyrdite** [comment] 2015-11-17 05:48
Does this still happen?  I've only encountered it when the server changes map/resets.

**Comment by DolceTriade** [comment] 2015-11-17 17:14
Probably, though I haven't seen it since Tremulous.

**Comment by Kangz** [comment] 2015-11-17 20:32
Closing as won't fix, as we don't have enough information.

**Closed by Kangz** 2015-11-17 20:32 UTC
Labels: A-Client, S-Verified, T-Bug
