### ISSUE TITLE
Standing on the Armory lets the player bounce slightly up and down

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1439] opened 2021-06-20 22:53 UTC

**Comment by slipher** [comment] 2021-06-21 01:30
Duplicate of https://github.com/Unvanquished/Unvanquished/issues/425. You can set `/cg_nopredict 1` and see that the player is not really bouncing on the server. It's funny how this happens even in a local game where prediction should hardly be needed...

**Comment by Gireen** [comment] 2021-06-21 12:36
Disabling prediction makes it go away indeed. But this effect only happens with the armory, and also only wen standing on it. The strength seems to vary over time.

**Comment by slipher** [comment] 2021-06-21 14:20
> But this effect only happens with the armory,

No it doesn't, I've also seen it with eggs and telenodes.

**Comment by slipher** [comment] 2021-07-29 19:30
OK, so the armory bug really is a different bug than the other one. The armory prediction bug happens standing anywhere on it, not only the edges. The armory bug is triggered by non-integer values for mins/maxs:
```
mins        -31 -31 -11.3
maxs        31 31 66.7
```

It's this code for getting the bounding box that only works for integers:
```
			// encoded bbox
			x = ( ent->solid & 255 );
			if (x == 255) x = 350;
			zd = ( ( ent->solid >> 8 ) & 255 );
			zu = ( ( ent->solid >> 16 ) & 255 ) - 32;

			bmins[ 0 ] = bmins[ 1 ] = -x;
			bmaxs[ 0 ] = bmaxs[ 1 ] = x;
			bmins[ 2 ] = -zd;
			bmaxs[ 2 ] = zu;
```

We could fix this by using `BG_BuildableBoundingBox` for buildables instead of the `solid` thing.

**Closed** 2021-08-20 22:22 UTC
Labels: T-Bug
