### ISSUE TITLE
cmake warning

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2155] opened 2022-09-04 22:53 UTC
With cmake 3.24.0, I have those warnings:

```
CMake Warning (dev) at /usr/share/cmake-3.24/Modules/CMakeDependentOption.cmake:89 (message):
  Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
  Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  daemon/CMakeLists.txt:120 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by necessarily-equal** [comment] 2022-11-18 18:17
I'm pushing this for 0.55 since this isn't a real problem, and the way to proceed isn't 100% clear.

I don't know much about cmake, but I think enabling this would mean that we need to bump `cmake_minimum_required(VERSION 3.12)` to `3.22`, and disabling this would mean that we silence a warning and make us rely on deprecated behavior.

@illwieckz what's the minimum version of cmake that we want to support?

**Comment by slipher** [comment] 2023-11-17 05:57
Duplicate of #1921.

**Closed by slipher** 2023-11-17 05:57 UTC
Labels: A-Build, T-Bug
