### ISSUE TITLE
FPS drops dramatically near human base

### ISSUE THREAD

**Issue by trinidado** [Unvanquished/Unvanquished#590] opened 2015-02-13 20:30 UTC
Hi,

Ever since I updated to 0.36, my fps has dropped to 5-10fps whenever I am around the human base. I have tried to turn all my graphics settings lower, but that has not helped, except to raise the fps in all other areas. I am running Mac OS X 10.10.1 on a 2010 Macbook pro with 8GB ram and a Nvidia 320m graphics card.

**Comment by Kangz** [comment] 2015-02-14 05:36
Thanks for the report, I have noticed the same problem recently on a similar configuration. We don't have a fix yet however.
Which is the latest alpha that worked for you? That'll save help us know when the problem has been introduced.

**Comment by trinidado** [comment] 2015-02-22 20:26
Hi Kangz, the latest alpha that worked for me was 0.35

Sorry for the delay in returning to your comment- I'm new to GitHub!

**Comment by trinidado** [comment] 2015-03-04 02:46
Hi Kangz, I updated to 0.37 and I still have the same problem. The fps drops most dramatically when I am looking at the reactor. Also, I noticed that it occurs when I shoot with the SMG (but not the blaster).

**Comment by Kangz** [comment] 2015-03-04 02:50
@trinidado thanks for the update, I have been to repro on alpha 0.37 but didn't have time to look at that closely yet. I will try to fix it before next alpha release and provide binary when I have it fixed, if you want them.

**Comment by Kangz** [comment] 2015-03-06 20:54
The problem is the increase of number of bones in e3dcb6a37da2907a524fc3bdce4b11b90c916789. Will investigate to understand why this causes this problem.

**Comment by trinidado** [comment] 2015-03-07 02:05
Thank-you for the update Kangz! I do not know how to compile the mac application but I look forward to playing again when the next alpha is released. (Is it difficult to compile the binary? If not, I may try compiling it myself.)

**Comment by Kangz** [comment] 2015-03-08 00:25
It isn't but compiling it won't fix the problem. We are using a huge amount of vertex uniforms so we should see how to reduce the amount, maybe with UBOs? Or just reducing to 192 and fixing the detection logic for the software fallback (it is currently broken). Pinging @gimhael.

**Comment by gimhael** [comment] 2015-03-08 08:16
Well, the renderer loads only tess.numBones bones into the uniforms, so the GL calls are identical before and after the change.

We copy the whole MAX_BONES in RE_AddRefEntityToScene through the VM barrier, so there's an additional 8k per call (extra 128 bones * 64 bytes per bone).

**Comment by Kangz** [comment] 2015-03-08 19:03
The bug is not related to NaCl as it appears on Alpha 36, and adding that data shouldn't divide the performance by 8 or so. Could it be that the computation of MAX_GLSL_BONES is slightyl off?

**Comment by Kangz** [comment] 2015-03-20 20:05
@trinidado It should be fixed, I can make a Mac build for you or you can wait for next release (or compile from sources).

**Closed** 2015-03-20 20:04 UTC
Labels: A-Renderer, GPU-Nvidia, OS-Mac, T-Bug, T-Performance
