### ISSUE TITLE
missiles can go through thin walls

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2433] opened 2023-02-08 00:12 UTC
Some players already told me about that, and that this was true in tremulous as well, but I have just found a map where the issue is easy to reproduce: `map-abyss_0+a5.dpk` from sweet's server, complete name in scoreboard is `Abyss Release 5`.

![2023-02-08](https://user-images.githubusercontent.com/1316300/217395825-4d412668-2397-4b33-89e8-fd4d85b810db.png)

This may be related to #1609

**Comment by slipher** [comment] 2023-02-08 04:29
Are you sure it's not intentional? I have a vague idea that there is some texture flag you can set to allowing shooting through (which makes sense here as you can see through it).

**Comment by bmorel** [comment] 2023-02-08 09:28
1. This place is not normally reachable;
2. it is impossible to build there without g_ignorenobuild (in the whole room). The idea here is to build a specific layout where OM can't be reached, though, so I'm intentionally disabling some rules;
3. OM can whip back all the time (this could use a different issue though) and missiles can sometimes, depending on angle and place, go through, but **not** weapons that use hitscan

So yes, I'm pretty sure it's a bug. According to @cu-kai this bug was already present in tremulous, in other maps with thin glasses.

**Comment by cu-kai** [comment] 2023-02-09 11:19
This is even possible in maps with thick glass, like deathrun. This one was definitely possible in Tremulous.

Here's an old screenshot of me proving this:
![unvanquished_2022-09-11_184857_000](https://user-images.githubusercontent.com/13281185/217798512-d2cde011-69d8-422a-898c-a2278e2968a6.jpg)

**Comment by necessarily-equal** [comment] 2023-02-09 11:22
Maybe the walls are defined to be passing by mistake sometimes? If something is transparent they may not have set `CONTENTS_SOLID`.

**Comment by bmorel** [comment] 2023-02-09 15:11
I think instead of explaining that this might be intended, testing shuold be done, especially since I think there are all elements needed to reproduce (on 2 maps even).

**Comment by sweet235** [comment] 2023-02-20 07:35
Here is another one, on nexus6:

![a](https://user-images.githubusercontent.com/110394607/220041719-a5c54d3d-832b-44b1-872e-70b37d38c482.jpg)

**Comment by cu-kai** [comment] 2023-03-15 00:11
I've encountered this on my new map, rush-station.

You can shoot through the patch mesh forcefields.

![unvanquished_2023-03-15_001003_000](https://user-images.githubusercontent.com/13281185/225170067-f89d4533-5185-45b9-b145-0227241e32a2.jpg)

**Comment by illwieckz** [comment] 2023-03-15 02:03
> 1. This place is not normally reachable;
> 2. it is impossible to build there without g_ignorenobuild (in the whole room). The idea here is to build a specific layout where OM can't be reached, though, so I'm intentionally disabling some rules;
> 3. OM can whip back all the time (this could use a different issue though) and missiles can sometimes, depending on angle and place, go through, but **not** weapons that use hitscan
> 
> So yes, I'm pretty sure it's a bug.

This can be a map bug, when the mapper applied a texture that only clip players and not weapons.

So there is two kind of bugs:

- map bugs
- game bugs

Bugs were weapons can go through thin walls actually exist, but usually it's a bit tricky to reproduce, like you need very specific angles or things like that.

If every weapon projectile go through without making any effort, it can be a map bug.

I'm myself reproduced some corner case were I was able to kill dretch bots through glass surfaces (I may have some screenshots somewhere) with a bit of determination, that is indeed a bug.

**Comment by illwieckz** [comment] 2023-03-15 02:06
> I think instead of explaining that this might be intended,

@slipher did not said it was intended by the mapper, but the texture used by the mapper probably was intended by the texture artist to behave this way. This is a grate, texture artist which is probably not the mapper very likely configured the texture to let weapon projectile pass through.

**Comment by illwieckz** [comment] 2023-03-15 02:25
On this specific abyss map it only passes through with some angles (some angles makes the projectile collide with the floor), so that looks like a game bug:

[![thin wall almost solid](https://dl.illwieckz.net/b/unvanquished/bugs/thin-wall-almost-solid/unvanquished_2023-03-15_031106_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/thin-wall-almost-solid/unvanquished_2023-03-15_031106_000.jpg)

[![thin wall almost solid](https://dl.illwieckz.net/b/unvanquished/bugs/thin-wall-almost-solid/unvanquished_2023-03-15_031108_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/thin-wall-almost-solid/unvanquished_2023-03-15_031108_000.jpg)

In the nexus6 map it is a map bug:

[![thin wall almost solid](https://dl.illwieckz.net/b/unvanquished/bugs/thin-wall-almost-solid/unvanquished_2023-03-15_031718_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/thin-wall-almost-solid/unvanquished_2023-03-15_031718_000.jpg)

The texture itself isn't configured to let projectile go through, but the other side of the brush uses `metalstep` textures and then the wholebrush inherit the `playerclip` surfaceparm that lets missile go through. Even grenades fall down.

**Comment by bmorel** [comment] 2023-03-15 08:48
Conclusion: there are 2 bugs. One might be on the map side (or on this inheritance thing, maybe it should not exist?) and the other is clearly in the game.

**Comment by slipher** [comment] 2023-11-17 22:42
I can reproduce on rush-station with 0.54.0 with `/sv_fps 26; devteam h; setviewpos -2027 342 48 -132 6` then `itemact blaster` and `+attack`. The bug was fixed by ab590255aa8acf0a72e131b9b928b273bd5f335e. Let it be remarked that sometimes refactoring does fix bugs.

**Closed by slipher** 2023-11-17 22:42 UTC
Labels: T-Bug

**Comment by cu-kai** [comment] 2023-11-17 22:43
> I can reproduce on rush-station with 0.54.0 with `/sv_fps 26; devteam h; setviewpos -2027 342 48 -132 6` then `itemact blaster` and `+attack`. The bug was fixed by [ab59025](https://github.com/Unvanquished/Unvanquished/commit/ab590255aa8acf0a72e131b9b928b273bd5f335e). Let it be remarked that sometimes refactoring does fix bugs.

_occasionally_!

I can confirm this is no longer an issue in either rush-station or deathrun.
