### ISSUE TITLE
Get disconnected 'CL_ParseGamestate: bad command byte'

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#573] opened 2015-02-06 04:42 UTC
map changes, got disconnected with message: 'CL_ParseGamestate: bad command byte'

Try to reconnect, get same message.
It has something to do with a layout that I made.

If i open the layout in the client, no problem.
If i run a dedicated server with the layout and try to connect, i get the error.

Would prefer to resolve without having to re-do the layout.

**Comment by Viech** [comment] 2015-02-06 17:23
I don't think this has anything to do with the layout. This sounds more like a client/server version mismatch to me. Check if both are running the latest alpha (36, currently).

**Comment by overvolting** [comment] 2015-02-06 18:36
They are the same version.
Every other map works, every other layout works.

If the server auto-changes map to spacetracks with the spacetracks1 layout that I made, I cannot connect. It's very repeatable.

The layout is large because spacetracks is large.

**Comment by Viech** [comment] 2015-02-06 18:46
Can you upload the layout somewhere so that we can have a look?

**Comment by overvolting** [comment] 2015-02-06 22:17
http://www.filedropper.com/spacetracks1

**Comment by overvolting** [comment] 2015-02-07 19:04
http://tremulous.net/forum/index.php?topic=7182.0

**Comment by overvolting** [comment] 2015-02-07 19:06
There's distinct difference between gamestate & the iwd name/sum mistmatch error.

Gamestate is limited in COD2 to 16k. In UO it was 32k.

Gamestate in a very basic nutshell is the amount of information that a server has to send to a client when they connect to the server. This information includes all the info about the map (brushes,entities, textures, effects) as well as the amount of players currently on the server.Mods affect the gamestate amount & having too many mod effects/features running will cause gamestate errors.

If this amount of info exceeds 16k then players will get a cl_parse gamestate error & be unable to join the server. Usually, when only one or two players on on a server the amount of information is minimal but the more players that connect then the amount of info increases thus the more chance that you'll exceed the 16k limit.

Gamestate is more complex issue than I've outlined but it is a basic guide.

**Comment by DolceTriade** [comment] 2015-02-07 22:42
Nice writeup.

**Comment by overvolting** [comment] 2015-02-07 22:46
So, if it were simple, it would be nice to double or tripple the gamestate budget.

**Comment by Viech** [comment] 2015-02-09 14:36
I'm not sure if it's a good thing to boost the limits, 260 buildables is a lot after all. Unfortunately we transfer two to three entities per buildable due to beacons. Either way, atleast the error reporting needs to be improved on this.

**Comment by overvolting** [comment] 2015-02-16 03:30
Well, can you please at least stop people from adding more buildables than we can support?

When someone tries to add too many, that's when the verbose warning should be given.
Also make sure to take into account all the other things that need to be in gamestate, like 24 clients etc.

**Comment by Viech** [comment] 2015-02-16 17:19
It's not that easy as not only buildables are entites. The spike of a spiker can be the one entity that's too much. Whether we crash or not, the game breaks in some way or the other once the limit is hit.

**Comment by overvolting** [comment] 2015-02-18 21:24
True, the game can break in other ways for the same reason. To make the error more descriptive is great, however I don't feel that it goes far enough. The way it breaks, because it's delayed and removed for the causes, can be very frustrating, even if the error message is correct. I would encourage to implement the improved error message but also keep looking for new ways to avoid the problem in the first place that might have a chance of being implemented.

**Comment by Kangz** [comment] 2015-02-18 21:45
TODO for the new netcode, when we get to doing that. SOON(tm)

**Comment by bmorel** [comment] 2021-09-27 11:11
Was netcode updated since this? I do not think there is now a limit to number of buildables, yet I've seen people placing a *lot* of buildables. Dunno how many, but still a lot.
Files are no longer accessible so I can't test.

**Comment by bmorel** [comment] 2022-07-16 00:57
I've build some pretty bloated layouts, up to 227 (alien). This takes lot of time, and I could not see any problem.
Another one have 194 buildings, 2nd higher I could do, which includes 33 rocket pods. Still no problem.
Original files referenced in this issue are now dead links.

Someone will need to build an even bigger layout to manage to verify this issue is still true, I guess.

**Comment by bmorel** [comment] 2022-08-29 23:46
As it turns out, someone did built layouts that reproduce the problem:

* https://github.com/bmorel/unvanquished-layouts/tree/main/layouts/hangar28
* https://github.com/bmorel/unvanquished-layouts/blob/main/layouts/spacetracks/humanpve1.dat

This is clearly related to layout, and interestingly enough the server is *still* running, only the client fails.

**Comment by necessarily-equal** [comment] 2022-11-19 12:03
So now the new layouts are dead links too. @bmorel do you happen to still have them? Are they hosted somewhere else?

**Comment by bmorel** [comment] 2023-01-13 12:16
I'm not at home, but I probably still have that stuff around. It is also probably hosted on my server. Or maybe I removed the buggy content? I do not remember.

**Comment by necessarily-equal** [comment] 2023-01-28 22:39
I tried to bump the MAX_MSGLEN constant in daemon like this, but I now get another error. It seems this isn't enough to fix it.

```patch
diff --git a/src/engine/qcommon/qcommon.h b/src/engine/qcommon/qcommon.h
index 064fb45c..c540b5a1 100644
--- a/src/engine/qcommon/qcommon.h
+++ b/src/engine/qcommon/qcommon.h
@@ -170,7 +170,7 @@ void       NET_LeaveMulticast6();
 void       NET_Sleep( int msec );
 
 //----(SA)  increased for larger submodel entity counts
-#define MAX_MSGLEN           32768 // max length of a message, which may
+#define MAX_MSGLEN           524288 // max length of a message, which may
 //#define   MAX_MSGLEN              16384       // max length of a message, which may
 // be fragmented into multiple packets
 #define MAX_DOWNLOAD_WINDOW  8 // max of eight download frames
```

**Comment by bmorel** [comment] 2023-01-28 23:41
FWIW the layouts I had are [there](https://codeberg.org/bmorel/unvanquished-layouts).

**Comment by bmorel** [comment] 2023-03-24 10:46
I have the problem with 
[this](https://github.com/Unvanquished/Unvanquished/files/11061172/eggs-master.default.dat.txt) layout. It applies to the map `eggs-master` 1.1 and reproduce the "bad command byte" problem with a success rate of 100%

**Comment by slipher** [comment] 2024-10-31 17:12
Closing in favor of #2124 which has more working links at least.

**Closed by slipher** 2024-10-31 17:12 UTC
Labels: S-Verified, T-Bug, A-Engine, T-Verbosity
