### ISSUE TITLE
Telenodes and eggs can spawn a player overlapping another

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#1368] opened 2021-04-13 05:37 UTC
When a human is standing at a certain spot on the telenode, another human may spawn with an overlapping bounding box with the first one. This renders both of them unable to move. It is pretty easy to reproduce like this:
- Have 1 telenode
- Stand in the middle of the telenode
- Add a human bot
- Walk slowly toward the edge of the node until the bot spawns

This happened to me twice while testing the 0.52 release candidate. But I was able to reproduce using my own 0.52/sync gamelogic with 0.51 assets.

Below are programmatic repro instructions, which I used with `map-forlorn_0.15.dpk`. You can conveniently run them by saving in a file `<homepath>/config/hspawnbug.cfg`, and typing `/exec hspawnbug.cfg` in the console.

```
devmap forlorn
delay 10f team h
delay 20f class rifle
delay 30f setviewpos 1879.062134 1602.956055 341.411255 -49.762573 8.412258
delay 40f bot fill 3 h
```

**Comment by necessarily-equal** [comment] 2021-04-13 15:23
This issue is also reproducible with aliens

**Comment by illwieckz** [comment] 2021-04-13 15:31
I believe there is a cvar to enable in order to push out people standing on a telenode, to prevent people blocking the spawn.
It probably does not pushes players from the other team though.

It would be better to fix the bug anyway.

**Comment by slipher** [comment] 2021-04-13 15:48
It also happens in 0.51

**Comment by Gireen** [comment] 2021-04-13 16:09
Duplicate of #1160 
Seems like the spawnblock area is neither high nor wide enough.
So far i couldn't find out how this area is defined.

**Comment by necessarily-equal** [comment] 2022-02-20 12:17
Some patch making the denial zone large enough for most cases:

```diff
diff --git a/src/sgame/components/EggComponent.cpp b/src/sgame/components/EggComponent.cpp
index d016879f9..9a0d59d81 100644
--- a/src/sgame/components/EggComponent.cpp
+++ b/src/sgame/components/EggComponent.cpp
@@ -27,11 +27,12 @@ bool EggComponent::CheckSpawnPoint(
 
 	// Method 1.
 	// This describes the worst case for any angle.
-	/*{
+	{
 		displacement = std::max(VectorLength(spawnerMins), VectorLength(spawnerMaxs)) +
 		               std::max(VectorLength(clientMins),  VectorLength(clientMaxs))  + 1.0f;
-	}*/
+	}
 
+#if 0
 	// Method 2
 	// For normals with equal X and Y component these results are optimal. Otherwise they are still
 	// better than naive worst-case calculations.
@@ -63,6 +64,7 @@ bool EggComponent::CheckSpawnPoint(
 		// optimal (closest possible) distance.
 		displacement = (1.0f - frac) * minDistance + frac * maxDistance + 1.0f;
 	}
+#endif
 
 	spawnPoint = spawnerOrigin + displacement * spawnerNormal;
 ```

**Closed** 2022-03-16 03:41 UTC
Labels: T-Bug
