### ISSUE TITLE
'missing' models in debug build

### ISSUE THREAD

**Issue by TimePath** [Unvanquished/Unvanquished#903] opened 2016-02-15 23:46 UTC
The following functions should check for file existence first:

* `CG_ParseWeaponFile`
* `CG_InitBuildables`
* `CG_RegisterClientModelname`

**Comment by mbasaglia** [comment] 2016-06-11 16:37
There's a merged pull request referencing this issue can it be closed?

**Comment by DolceTriade** [comment] 2016-06-11 23:11
I reverted that PR.

**Comment by jaytersen** [comment] 2016-06-30 10:01
It was only a partial revert, i believe the issue is fixed.

**Closed** 2016-06-30 12:40 UTC
Labels: A-Gamelogic, D-Easy, T-Cleanup
