### ISSUE TITLE
Human corpses don't retain their equipment

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#3220] opened 2024-12-02 13:54 UTC
When you die, although you retain your equipment while the death animation is playing, once that is finished, you have no equipment attached, for example the jetpack or the radar.

**Comment by slipher** [comment] 2024-12-03 03:54
Duplicate of https://github.com/Unvanquished/Unvanquished/issues/206.

**Closed by slipher** 2024-12-03 03:54 UTC
