### ISSUE TITLE
Allow players and spectators to build any kind of building in /devmap

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2128] opened 2022-08-30 18:02 UTC
This would ease the creation of map layouts.

This also requires implementing a HUD that would allow devmappers to see BPs of both teams.

**Comment by necessarily-equal** [comment] 2022-08-31 21:10
Downside: this explicitely makes UI different in devmap and thus makes the game harder to dev on.

**Comment by bmorel** [comment] 2022-08-31 22:41
I consider /devmap to be a modder tool. For debugging, you can still use the /map command.

**Comment by necessarily-equal** [comment] 2022-08-31 22:50
> I consider /devmap to be a modder tool.

I disagree. Say that you are working on the [firefighter grangers](https://github.com/Unvanquished/Unvanquished/pull/1880), you are using `/devmap` to unlock `/give momentum`. Say you are working on the thing that allows you to move away from [walls on evolve](https://github.com/Unvanquished/Unvanquished/pull/1484), you need free money and thus devmap. Say you are working on some bot BT and you want to use [some debug draw](https://github.com/Unvanquished/Unvanquished/pull/1916) to print distances, you need devmap too.

I think you need /devmap when developing. It also means you want to keep it close enough to the real experience.

I'm not sure what problem this issue is solving really. Is this about not needing to switch team to build things ? Is this about ignoring forbidden buildings (`/g_disabledBuildables`) ? tbh I find the current situation fine as is, and possibly less confusing

**Comment by bmorel** [comment] 2022-08-31 22:51
You're right, it's actually a duplicate of #2127 I think

**Comment by DolceTriade** [comment] 2022-09-01 00:00
Devmap is definitely not a modder-only tool. Devmap is extremely important for players who want to learn the game, get better, train, etc.

**Comment by bmorel** [comment] 2022-09-01 18:49
I don't really see why `/map` can't be used to learn the game, get better, train, etc, though?
The only difference between `/devmap` and `/map` AFAIK is that `/devmap` enables cheats.

**Comment by bmorel** [comment] 2022-09-01 18:51
Anyway, let's close this because: duplicate.

**Comment by necessarily-equal** [comment] 2022-09-01 19:08
Not sure https://github.com/Unvanquished/Unvanquished/issues/2128 is actually a duplicate as it would be about BP vs buildable types. But I mean I don't see the point in either case :S

**Comment by DolceTriade** [comment] 2022-09-01 19:34
They are not a duplicate.

**Comment by Gireen** [comment] 2022-09-01 20:31
I don't see much benefit in this. 
With `/devteam` you can already easily switch between alien and human builder on the spot.

**Comment by VReaperV** [comment] 2024-10-31 14:13
I don't see any point in this either. Especially since building layouts (i. e. pve) usually involves placing most buildings for one team, and only a few for the other.

**Comment by sweet235** [comment] 2024-10-31 14:31
> you are using /devmap to unlock /give momentum

You actually just have to toggle `g_cheats`.

**Comment by slipher** [comment] 2024-10-31 15:48
There seems to be a consensus that this does not bring much benefit and it would be too much trouble to implement. You'd even have to implement some sort of wallwalking or rotation for spectators if you wanted build alien buildings on walls/ceilings.

**Closed by slipher** 2024-10-31 15:48 UTC
Labels: T-Feature-Request, A-DevTools
