### ISSUE TITLE
Ready icon doesn't show

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#653] opened 2015-03-06 23:02 UTC
At the end of the game, since 0.37, nobody can ready-up.

**Comment by DolceTriade** [comment] 2015-03-07 00:03
So you must wait the full 30seconds to proceed to the next map or the "ready" icon doesn't show?

**Comment by overvolting** [comment] 2015-03-07 02:29
The ready icon doesn't show.

**Comment by Viech** [comment] 2015-03-08 15:02
Setting `A-Engine` since assignment implies that this may be NaCl related, though this pretty much looks like a UI bug.

**Comment by neumond** [comment] 2015-03-08 21:36
Please recheck this issue still affects you.

**Comment by Viech** [comment] 2015-03-09 22:15
@neumond, did you fix this? If yes please close the issue with a reference to the commit (you can do this from within the commit message, too, just add a line that says `This fixes #653.`). I didn't experience the issue during the dev game, which where held on

**Comment by neumond** [comment] 2015-03-09 23:08
I didn't fix it intentionally, just made cleanup of scoreboard updating code along with flickering issue. Time of opening this issue is a bit later of my commit push, I thought this issue caused by my changes. But since you and I don't experience any problems here, I'm closing this bug.

**Closed by neumond** 2015-03-09 23:08 UTC
Labels: A-Engine, A-Gamelogic, A-UI, S-Verified, T-Bug
