### ISSUE TITLE
Bots have navigation problems in complex parts of maps

### ISSUE THREAD

**Issue by Veyrdite** [Unvanquished/Unvanquished#310] opened 2014-06-10 03:52 UTC
# Problem

Bots sometimes either freeze or move around in tight circles/spasm.  They stay like this until provoked (sometimes they do not react at all) or pushed out of their little zone (commonly difficult, as they will want to move back).
- when most of a team becomes stuck, team balance suffers
- bots can camp on spawns, preventing them from working.  Bots are not 'kicked' away from spawns like players are.
# Steps to reproduce
- play on non bot-friendly maps like chasm or spacetracks
- wait for a bot to get stuck, or build a spawn up somewhere where a bot can't take a simple path to escape from.
# Examples

Dawdling on a high crate, spazzing in circles
![multiple](https://cloud.githubusercontent.com/assets/6168874/3225469/788e3a4c-f051-11e3-9586-db143abc8081.jpeg)
Stationary and non-reactive to everything, including attacks.  Blocks spawning
![overview](https://cloud.githubusercontent.com/assets/6168874/3225470/788f9770-f051-11e3-8414-2cff3613432e.jpeg)

Other known places:
- chasm: marauders circle on-top of the weather-sensor-thing in the outside area
- karith: crates on the mezzanine of the elevator room, near the vent
- spacetracks: opposite side of the wall the bar sits against in the cafeteria.  Bots like treadmilling this.

**Comment by illwieckz** [comment] 2018-12-10 07:44
Bots now know how to escape crates, see #984, but we can't guarantee it would not happen on special case. Can current implementation be considered as acceptable to close this issue?

**Comment by illwieckz** [comment] 2018-12-10 07:46
May be better to close this one, if needed anyone can open a new issue with documented  complex case instead of keeping this one open "in case of".

**Comment by t4im** [comment] 2018-12-10 08:42
We could try dynamically connecting entities with surroundings to specifically address disconnected player spawns. Not sure how much comes out of it, but might be worth looking into.

**Comment by bmorel** [comment] 2021-09-26 13:42
This bug is NOT closed, the issue is still there.

There are 3 possible fixes:

* either have mappers place AI-clip or alike on surfaces which are reachable by accident by bots, and have no navmesh generated for those (resulting in bot code implementing a "find nearest navmesh" and using it)
* or have them place one-way connections, this would be long, tedious and not doable in practice
* or have the daemonmap to do that. This is the best option, but also the most complex one to implement. It would require to stop considering daemonmap as a tool meant to disappear, but as the valuable and essential tool it currently really is, and give it some love.

**Comment by illwieckz** [comment] 2021-09-26 14:03
When I say daemonmap is meant to disappear, I mean it means do disappear as an external tool we have to ship with the editor, producing files we must ship in DPK. All the navmesh code in daemonmap is not meant to disappear and is lean to receive fix. This code is just meant to move somewhere else one day.

**Comment by bmorel** [comment] 2021-09-26 14:06
they the comment in the readme should be clarified, to not discourage people to improve it

**Comment by bmorel** [comment] 2021-09-28 16:44
The comment issue (unrelated to this repo) has been fixed, thanks. Could you, though, move this issue to daemonmap (I don't know how to do so, you can also prefer to explain me on IRC, there's a bunch of tickets I've seen that should be moved to more related repos/orgs), since currently the engine is not responsible for the navmesh generation?

**Comment by slipher** [comment] 2021-09-28 16:48
This repo (Unvanquished) can be considered as the top-level repo for issues regarding Unvanquished, in the case where they span multiple repos or the location of the bug is unknown. The navmesh generation contributes to the issue, but gamelogic and maps can also be part of the problem and solution, so it is better to keep the issue here.

**Comment by bmorel** [comment] 2021-09-28 16:58
I see.
You are right that this can currently be fixed in multiple places:

* in daemonmap by generating navmesh connections automatically (the ideal solution)
* in maps by removing those situations (ugly)
* in game by manually adding those connections (lot of boring work, process barely documented)

I still think it should at least be explicitly tagged that the primary and best solution is to implement in daemonmap, and maybe to have daemonmap referencing this bug, since this is a pretty annoying limitation of the our current navmesh tooling, which is one of the important roles of daemonmap AFAIK.

**Comment by illwieckz** [comment] 2021-09-28 17:16
There is also one point : at the time this issue was created those other repositories didn't existed. But for the reason already stated it's kind of global Unvanquished issue, so it's OK to not move the issue even if those other repositories exist, and GitHub does not make possible to transfer issues across organizations (only accross repositories of same organization), so, moving would be too much effort for something that is fine there. 😁

> in maps by removing those situations (ugly)

Tweaking maps to make the life easier for bot is not that ugly, it's part of level design. Of course it's welcome to reduce the constraints. I agree that we must focus on better navmesh (either generation and navigation) and better AI, especially since we can inherit many maps from Tremulous that are very unlikely to be edited.

For official maps, it's fine to do minor changes that makes bot easier (like adding some clips or things like that), but that must not be an excuse to not improve navigation and bot decision.

**Comment by bmorel** [comment] 2021-09-28 17:27
Well, you know that my position is more about improving AI than fixing maps, especially since we have more devs than mappers :)

Sure, sometimes, bot-traps are just useless details which add nothing to gameplay (I think about old parpax here, which had those nasty holes in which bots were stuck so often, parpax-mini fixed them, and latest parpax did it also, without the fixes changing map's interest, even making it easier to navigate for humans also).
But typically, the problem is that AI jump on crates, and gets stuck. The problem can be improved by triggering the unstuck behavior sooner (and it really does good) but the problem is just worked around, and I believe those add interest to the maps, as it's sometimes possible to use them to access other parts of the maps, or simply to get a better point of view.

**Comment by bmorel** [comment] 2021-12-20 22:05
Well, let's add a 5th solution, that I even have PoC for: generate navmeshes which consider that places one can reach by jump are connected. When bots hit geometry, they can jump... or crouch, or whatever they think is better to go through (thanks to traces).

Pros: this is completely automatic, no manual thing to do at all.

Cons: This does not allow the use of elevators or ladders. This also does not allow bots to connect navmeshes which are separated with a hole.

**Comment by bmorel** [comment] 2022-01-04 00:41
Another problem of that solution is that bots are dumb, and do not use navmesh while in fight.

Still, I believe this is part of the proper solution. Navcons will still need to be added to ladders, and this could probably be done automatically, same for elevators, I believe it's possible to handle them automatically, at least when they are simple enough (that means: unlike most spacetracks ones).

Manual navmesh connections are still mandatory, and worst, they need to be annotated somehow so that the bot knows the action to do.
In currently status, all the PoC I have made were about handling collisions against walls, instead of detecting the navmesh and do proper action. In short, they are *hacks*.
I still believe they would be a huge improvement if I can get them reliable enough.

**Comment by bmorel** [comment] 2022-01-12 18:50
Basically, "what is stuck?" is important if we want to fix the problem.

1st post shows bots stuck on small areas, and that was fixed by having a basic stuck recognition accompanied with a stuck dance, but this still fails in many, many situations, some being rather classic to have decent alien bases:

![2022-01-12-192210_1366x768_scrot](https://user-images.githubusercontent.com/1316300/149202342-d5834894-74fe-4312-a65a-664fc5e8d9eb.png)

Here, the goon is stuck on the pipes, and never notices that, because the area is too big. There's also yocto's "bot trap", or Tremor's underneaths.

I'm thinking, it would be possible to define "stuck" as: both ally and enemy team only have unreachable buildings. This way, the verification is way less fragile (if a bot can't reach any building because there's none, it's still possible to have stuck games, if the other team also have a bot but on another navmesh, but that situation is a lot less probable than current one).
As for the stuck dance, it would be possible to detect either the closest navmesh if one is not currently on a navmesh, or, if one is on a stuck navmesh (as per previous definition of stuck), find the point at which the distance between unstuck navmesh and stuck navmesh is the smaller, and try to navigate through the "out-navmesh" area.

I believe this could be doable, and would definitely fix this issue.

Opinions, everyone?

**Comment by Viech** [comment] 2022-01-12 19:07
Buildables are not a good reference, they could be build on ledges or platforms. I think a good indicator for being stuck would be that there has not been an enemy player character on the same navmesh for a while. Because as long as there is an enemy, the bot can potentially find and fight it, doing useful stuff (even if on an island).

Consider for example the alien high ground move location on thunder; alien bots spawn on the platform that contains their main base and they are happy to stay there as long as enemies also reach it. Otherwise they would get bored and try to leave.

**Comment by bmorel** [comment] 2022-01-12 19:34
> Buildables are not a good reference, they could be build on ledges or platforms

True, it's possible that *all* buildings are on edges, indeed, and in that case (which I mentioned) bots will be near useless anyway, like the typical situation on forlorn when humans build their base in there (mineral processing attic):

![2022-01-12-202605_1366x768_scrot](https://user-images.githubusercontent.com/1316300/149208495-cc02fd39-ae8f-4637-809d-db6b7eaace9f.png)

where aliens endlessly roam on ground, unable to do anything useful or interesting.
That situation can't be handled automatically in current status, instead it requires manually placed "navcon" (off-mesh connections) and code for AI to decide how to use said offmesh connection (I know I can get working wallwalking, but have yet to experiment with pouncing and walljumping. Tyrants are... well, tyrants.).

But at this point, bots can't win at all, and can't assist players to win neither.
Now, counting building-entities or player-entities per navmesh is probably not very different, if there's even any difference, so fine for me.

> the alien high ground move location on thunder

I don't see the place you're talking about?

**Comment by slipher** [comment] 2022-01-12 21:34
What I always suggest when this topic comes up is to prune connected components of the navmesh which are too small.

**Comment by Viech** [comment] 2022-01-12 21:36
> > the alien high ground move location on thunder
> 
> I don't see the place you're talking about?

Sorry, I meant on Forlorn.

**Comment by bmorel** [comment] 2022-01-12 21:49
> What I always suggest when this topic comes up is to prune connected components of the navmesh which are too small.

I don't know enough of how recast works to do that (but I know it's possible, I've seen mentions of that possibility), and that might not solve the problem of bots being stuck: there is no proof that bots would try to reach the closest navmesh when they're out of any. Besides, defining "too small" is not really an easy thing. Crates? Sure. That might be doable. But the pipes on forlorn screenshot or "mineral processing attic"? Not so much.

Also, for places where navmesh is disconnected by a rather low height difference, #1691 helps, when navmeshes are generated with more reasonable value for climbHeight than STEPSIZE (which is 18, and "more reasonable values" depends on the class, which in turn means to have different climbHeight).
My tests suggests that for anything taller than marauders, the problem of most crates is fixed (that's dragoons, tyrants, and all human classes). For marauders themselves, considering their small size compared to their jump strength, not really, but it's still a non-negligible improvement (old parpax small holes, nexus6's pipe in human base, notably, should be fixed, and that, for any classes).
Sadly, this improvement can't apply for height differences higher than `maxs[2]-mins[2]-1`, otherwise, previous tests have shown navigation problems. I applied this specific limitation after spending some time reading messages on recast's googlegroup, where their communication is, suggesting climbHeight should ideally be Zmax / 2, but in all cases never higher than Zmax - 1 (well, Z for us, they talk about Y, because different "up vector").
Of course, in that case, the navmesh is connected, and thus no longer small and hence, no longer eligible for pruning, if someone knows how to apply prune and if someone can define what, exactly, is "too small".

**Comment by bmorel** [comment] 2022-07-06 00:00
I'm putting this goal to beta 0.54 because I have working patches which fix the vague reported issue.
They need further improvements, yes, but it's doable in reasonable limits for 0.54.

**Comment by necessarily-equal** [comment] 2023-01-10 12:03
So, many of the issues mentioned or that would fit this issue's title have been fixed by now.

* https://github.com/Unvanquished/Unvanquished/pull/984, bots have an unstick routine if they don't move enough for too long
* https://github.com/Unvanquished/Unvanquished/pull/2215, bots have another way to unstick themselves
* https://github.com/Unvanquished/Unvanquished/pull/2259, bots have less trouble navigating tight spaces
* https://github.com/Unvanquished/Unvanquished/pull/2360, bots now avoid door panes when doors are open

Important known issues for bot navigation are:
* https://github.com/Unvanquished/Unvanquished/issues/2263
* https://github.com/Unvanquished/Unvanquished/issues/2366, which tracks most of what has been discussed in this issue, and not fixed yet. Except maybe for the mineral attic on Forlorn, but that seems hardly fixable in a way that still gives good gameplay on that map.

**Closed by necessarily-equal** 2023-01-10 12:03 UTC
Labels: A-Bots, T-Feature-Request, S-DoneInFork
