### ISSUE TITLE
When FLying with the jetpack you can no-longer hear the Chainsaw sawing (whilst using it) 

### ISSUE THREAD

**Issue by Pretuer** [Unvanquished/Unvanquished#1343] opened 2021-03-08 13:14 UTC
When FLying with the jetpack you can no-longer hear the Chainsaw sawing (whilst using it) 

When I was playing I noticed that I couldn't hear the chainsaw while I was flying here is a [video](https://video.hardlimit.com/videos/watch/d0284301-e1cb-4618-905f-4139db77833a) of the bug if needed: https://video.hardlimit.com/videos/watch/d0284301-e1cb-4618-905f-4139db77833a

**Comment by bmorel** [comment] 2023-02-07 14:44
duplicate of #579

**Closed by bmorel** 2023-02-07 14:44 UTC
Labels: A-Gamelogic, T-Bug, A-Assets, A-Feedback
