### ISSUE TITLE
spawn buildings are not blocked when allied player is standing nearby

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1768] opened 2022-02-19 23:21 UTC
How to reproduce: remove all but 1 spawn, move on that spawn, add a bot.

What the game should do: warn the player that they're blocking the spawn, and *not* spawn the next player until the place is blocked.
Other actions like nudging the blocker or killing it can be nice, killing it being already implemented.

**Comment by slipher** [comment] 2022-02-20 06:13
Try grepping (case-insensitively) for `cvar.*block` and see if that's helpful

**Comment by necessarily-equal** [comment] 2022-02-20 06:44
I don't think this is about the same thing. It's that the the spawn distance check is borked. Here is a patch that kinda fixes it:

```diff
diff --git a/src/sgame/components/EggComponent.cpp b/src/sgame/components/EggComponent.cpp
index d016879f9..9a0d59d81 100644
--- a/src/sgame/components/EggComponent.cpp
+++ b/src/sgame/components/EggComponent.cpp
@@ -27,11 +27,12 @@ bool EggComponent::CheckSpawnPoint(
 
 	// Method 1.
 	// This describes the worst case for any angle.
-	/*{
+	{
 		displacement = std::max(VectorLength(spawnerMins), VectorLength(spawnerMaxs)) +
 		               std::max(VectorLength(clientMins),  VectorLength(clientMaxs))  + 1.0f;
-	}*/
+	}
 
+#if 0
 	// Method 2
 	// For normals with equal X and Y component these results are optimal. Otherwise they are still
 	// better than naive worst-case calculations.
@@ -63,6 +64,7 @@ bool EggComponent::CheckSpawnPoint(
 		// optimal (closest possible) distance.
 		displacement = (1.0f - frac) * minDistance + frac * maxDistance + 1.0f;
 	}
+#endif
 
 	spawnPoint = spawnerOrigin + displacement * spawnerNormal;
 
```

Maybe I misunderstood, but I think this is a duplicate of https://github.com/Unvanquished/Unvanquished/issues/1368.

**Comment by bmorel** [comment] 2022-02-20 09:01
Yes, duplicate of that one indeed. I tried to found related issue before opening but looks like I failed to use the correct search words.

**Closed** 2022-02-20 09:02 UTC
