### ISSUE TITLE
Motion blur glitch while windowed

### ISSUE THREAD

**Issue by Kangz** [Unvanquished/Unvanquished#239] opened 2013-05-30 04:01 UTC
| Release | v0.16.0pre (63cc766d5f) |
| :-- | :-- |
| Operating System | Gentoo 64 bits |
| Kernel Version | 3.8.13-gentoo |
| Video Card | Nvidia GTX 670MX |
| Driver Type | Proprietary |
| Driver Version | NVIDIA 319.23 |
| OpenGL Version | 4.3.0 NVIDIA 319.23 |
| Map tested | A.T.C.S. HD |
| Renderer used | GL3 |

When playing windowed with a part of the game window out of the screen graphical, glitches appear when the motion blur is triggered.

![Screenshot of the issue](http://i.imgur.com/aXuFkfJ.jpg)
# Reproducing

Open the game windowed so that a part of the window is out of the screen. Start atcshd and spawn as a dretch, on top of the tunnel ramp do a circle jump to trigger the motion blur. Enjoy the glitch.
# Notes

In the screenshot we can see that some parts of the image are corrupted: it is exactly the parts that were out of the screen so it isn't an encoding bug. The framebuffer was not draw there.

**Comment by illwieckz** [comment] 2017-10-23 10:34
what's the status on this?

**Comment by Kangz** [comment] 2017-10-23 18:05
I don't think it has been fixed.

**Comment by illwieckz** [comment] 2021-09-27 10:54
I'm not reproducing it on composited window manager, but I assume a composited window manager should hide this kind of bug by design (since the game window is expected to get fully rendered to some surface whatever it is on screen or not).

We have to test on a non-composited window manager.

**Comment by illwieckz** [comment] 2021-09-27 11:08
On Ubuntu 21.04 I'm not able to reproduce it on non-composited managers like TWM or IceWM, the game even get fully rendered, even the part that is not on screen.

It's possible we have fixed that when fixing many other things.

**Comment by necessarily-equal** [comment] 2021-09-27 22:57
May have been fixed by https://github.com/DaemonEngine/Daemon/pull/410: some parts of the screen were not redrawn. I would be in favor of closing this unless someone can reproduce the issue.

**Comment by bmorel** [comment] 2022-01-04 22:35
> We have to test on a non-composited window manager.

AFAIK I3 is not composited, and I never have seen that. Now, I don't know what's a circle jump.

I'll close it, feel free to reopen if can reproduce.

**Closed** 2022-01-04 22:49 UTC
Labels: A-Renderer, OS-Linux, T-Bug

**Comment by slipher** [comment] 2025-07-13 04:26
Only 2D rendering is done to the default framebuffer now, so I guess that can't happen.
