### ISSUE TITLE
impossible "X was bitten by Y; Z assisted"

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#1572] opened 2021-10-31 01:36 UTC
A few times, I noticed a message like "X was bitten by Y; Z assisted" with Z beeing a player only spectating during the whole game. See for instance the attached file daemon.log in line 895. In this case, the game had just begun, and Z was spectating. Z had also spectated the game before that one.

I am not sure if this happens only right after a game has started.

Server was "Alien's Wrath ITA vanilla", if I recall correctly.

[daemon.log](https://github.com/Unvanquished/Unvanquished/files/7447906/daemon.log)
[cgame.nacl_loader.log](https://github.com/Unvanquished/Unvanquished/files/7447907/cgame.nacl_loader.log)

**Comment by illwieckz** [comment] 2021-10-31 02:09
good catch… probably an use of an not-initialized memory!

**Comment by slipher** [comment] 2021-10-31 02:11
I see this is Gireen's server. Maybe it's another bug triggered by the unorthodox bot management :stuck_out_tongue:

**Comment by illwieckz** [comment] 2021-10-31 02:26
> I see this is Gireen's server.

Are you sure? At the beginning of the log I see Gireen's exgp mod package indeed, and bots named after Developer names, like bots on Gireen's server, but then after that the loaded packages are stock unvanquished 0.52.0 (not 0.52.1) and only ITA server is currently running outdated 0.52.0 games. Also the bots names are the ones we can find on ITA server (like `[bot]CoD@ITA`, `[bot]Ambigioz+`, `[bot]Kappolo.sr`, `[bot]Ostin powers`, `[bot]Raziel` or `[bot]Moldavius` to name a few).

@Sswweet probably switched server between the beginning of the log and the end.

Basicaly the interesting part of the log is at the very end:

```
Server: g_botKickVotesAllowedThisMap changed to 1
Server: g_doWarmup changed to 0
Server: g_friendlyBuildableFire changed to 1
Server: g_friendlyFire changed to 1
Server: g_teamForceBalance changed to 1
Server: g_warmup changed to 10
[!!!]gH0sTIsLoL.LsD entered the game
freem entered the game
Sweet entered the game
freem joined the aliens
[bot]Ostin powers disconnected
●[bot]Tucs was bitten by ●[bot]Raziel; ●[!!!]gH0sTIsLoL.LsD assisted
[S] [!!!]gH0sTIsLoL.LsD: ???
[A] freem: ?
[S] [!!!]gH0sTIsLoL.LsD: im in specs
metamorph777 entered the game
[S] Sweet: happens
[S] Sweet: is a bug
```

One problem with ITA server is that it's outdated, it's then harder don't know if the bug is still there or if it could have already been fixed. For example the very well known stray particle line bugs is still seen a lot on ITA server while we shipped a release fixing this on June…

**Comment by necessarily-equal** [comment] 2021-11-06 08:48
The kill assist is found using the credit accounting data: the one that isn't the killer (or the killee) and did the most damage, will be marked as assistant (see `G_FindKillAssist` in the code). In theory, the credits accounting array is cleared in `ClientSpawn`… So that if an entity exists in the world, it must have been spawned, and this piece of memory must be initialized.

In practice, I suspect this field is often not initialized correctly, and likewise, while this should be reset on team change, it doesn't seem to be. See https://github.com/Unvanquished/Unvanquished/pull/1564 / https://github.com/Unvanquished/Unvanquished/issues/1514.

As a side remark, if the credit accounting is to cleared in ClientSpawn, then the damages you did before an alien evolves are ignored :eyes:

**Comment by superdupont-fr** [comment] 2021-11-07 16:12
I confirm something similar on Gereen's server few days ago.

I recorded the game, and later watched someone playing (I call him He).
He was playing a Dretch, and was killed by human with flamethrower.
He spawned again, and, a few later, was killed again (I don't remember if it was by the same person).
I noticed that He was killed assisted by me, but I know that at this time I was far away, and he was freshly born from egg...

**Comment by necessarily-equal** [comment] 2021-11-07 17:52
It's very possible that this isn't actually uninitialized memory, but instead memory corruption. I think I would try to to put many bots as spect (`/putteam Bot#3 s`), some regular bots and try to reproduce some day

**Comment by Sswweet** [comment] 2021-11-11 22:18
I observed this today on bot stagging SK9 server, which I am told is running recent master. If interpret all this correctly, this has been in master since at least 0.52.0.

Sadly, I did not (yet) find a time-saving method to check a version for this behavior.

**Comment by necessarily-equal** [comment] 2021-11-12 00:00
@Sswweet if you could find/write steps to reproduce this locally (i.e. with bots only), it would help a lot fixing this

Le 11 novembre 2021 23:18:15 GMT+01:00, Sswweet ***@***.***> a écrit :

**Comment by Sswweet** [comment] 2021-11-18 18:12
I did some experiments, using

- a local server with 5 minutes timelimit
- server config that does not pause the game if no client is connected
- bots fighting and bots spectating

I let that runs for a few hours. Then i grepped through the server output, but did not catch anything.

I also tried having a daemon-tty client connected.

All this was done with 0.52.1 and master. Do you have any suggestions what I could do increase my chance of observing the bug?

**Comment by superdupont-fr** [comment] 2021-11-18 19:31
I suggest, if possible, that some bot join after the game started, some in spectator mode, other join a team.

And, why not some joined the previous game in a team but stay spectator in the next game.

**Comment by necessarily-equal** [comment] 2022-01-09 19:58
A similar, but probably different issue was fixed here: https://github.com/Unvanquished/Unvanquished/pull/1681

**Comment by bmorel** [comment] 2022-07-06 13:25
Long time no see. Bug fixed by accident?

**Comment by necessarily-equal** [comment] 2022-11-18 15:47
I believe this was fixed in https://github.com/Unvanquished/Unvanquished/pull/1681. Please reopen if you see it again.

**Closed by necessarily-equal** 2022-11-18 15:47 UTC
Labels: T-Bug, S-Old-Needs-Check
