### ISSUE TITLE
Can't replace building when power constraints

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#661] opened 2015-03-07 18:31 UTC
In this screenshot, there was a turret in place. I could not build a rocket pod because not enough power, so I marked the turret and tried to build over it.
The building failed even though I had a yellow go-ahead.

http://postimg.org/image/m768nef6z/

**Comment by illwieckz** [comment] 2015-03-07 22:02
Since there is the "no room to build here" message and since you are very near the structure, it seems to be a duplicate of #562.

**Comment by Viech** [comment] 2015-03-08 15:33
Nope, not a duplicate. The problem here is that the player entity stands on top of the structure to be replaced and the prediction detects an intersection with its bounding box. (A workaround would be to jump.)

**Comment by Viech** [comment] 2015-03-08 15:38
Didn't look at the new posts in the other issue. Seems like it's indeed a duplicate. (Either way, we can safely merge this in the other issue.)

**Closed by Viech** 2015-03-08 15:38 UTC
Labels: A-Gamelogic, T-Bug
