### ISSUE TITLE
quit & rejoin server: team is unpredictable

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#689] opened 2015-03-28 16:15 UTC
Sometimes when you quit and rejoin a server, you show up as a spec.
Sometimes you show up on the last team you were on.

**Comment by Veyrdite** [comment] 2015-11-17 06:10
Possible explanation: adding you back to your previous team is the default behaviour, but this is prohibited if it would break team balance.  If the player numbers in each team have changed since you left then this can happen.

**Comment by Viech** [comment] 2015-11-17 11:51
Either this or it is related to client slot handling, which would be a bug. @overvolting can you give more details?

**Comment by bmorel** [comment] 2021-09-27 11:38
Still around in 0.52

**Comment by bmorel** [comment] 2022-07-06 12:52
I'm tempted to close it.

**Comment by bmorel** [comment] 2022-07-16 01:00
I think this can be closed, now, as I don't reproduce  since many months and nobody said anything on that topic.

**Closed by bmorel** 2022-07-16 01:00 UTC
Labels: A-Gamelogic, T-Bug, S-Needs-Input, S-Old-Needs-Check
