### ISSUE TITLE
VM crash with NaCl exception

### ISSUE THREAD

**Issue by VReaperV** [Unvanquished/Unvanquished#2347] opened 2022-12-26 21:18 UTC
The crash hapepned randomly during a match, don't know what caused it.

From console log, not sure if the previous warning is relevant:

    Warn: [skipnotify]cent->pe.legs.skeleton.numBones != cent->pe.torso.skeleton.numBones
    Warn: CGame VM: Crashed with NaCl exception
 
Crashdump attached:
[crash-nacl-CGame-1671581787738.zip](https://github.com/Unvanquished/Unvanquished/files/10304816/crash-nacl-CGame-1671581787738.zip)

**Comment by DolceTriade** [comment] 2022-12-27 01:44
Hm, which server was this? This isn't from an official release which means we'll need to track down whoever the server owner is.

**Comment by VReaperV** [comment] 2022-12-27 02:20
I think it was `Map&Tactic Testing EU | 289 maps | SK6 | 0.53.2`, which is Sweet's server I believe. Also, just noticed there was another crash, I think it was in the main menu and happened when I was trying to connect to a server, so it looked like the server list just closed.

[crash-nacl-CGame-1671580729356.zip](https://github.com/Unvanquished/Unvanquished/files/10305393/crash-nacl-CGame-1671580729356.zip)

**Comment by DolceTriade** [comment] 2022-12-27 06:01
Nice, that one we do have symbols for:

This is very helpful. We'll try to get a fix out for this.
```
Operating system: NaCl
                  0.0.0 nacl
CPU: amd64
     family 0 model 0 stepping 0
     0 CPUs

GPU: UNKNOWN

Crash reason:  0x0000000b / 0x00000000
Crash address: 0x0
Process uptime: not available

Thread 0 (crashed)
 0  main.nexe!Rml::ElementStyle::SetPseudoClass(std::__1::basic_string, std::__1::allocator > const&, bool, bool) [string : 1726 + 0x18]
    rax = 0x00000000fffe6d40   rdx = 0x0000000000000000
    rcx = 0x0000000000000000   rbx = 0x000000003e38001c
    rsi = 0x00000000fffe6d40   rdi = 0x000000003e38001c
    rbp = 0x00000000fffeff80   rsp = 0x00000000fffe6bb0
     r8 = 0x00000000100d1632    r9 = 0x00000000fffe6a58
    r10 = 0x0000000011969c8d   r11 = 0x0000066e00132c00
    r12 = 0x0000000000000000   r13 = 0x0000000000000000
    r14 = 0x000000003e38002c   r15 = 0x0000066e00000000
    rip = 0x00000000002797a9
    Found by: given as instruction pointer in context
 1  main.nexe! [Element.cpp : 748 + 0x2f]
    rbx = 0x00000000fd45f030   rbp = 0x00000000fffeff80
    rsp = 0x00000000fffe6c10   r12 = 0x00000000fd45f030
    r13 = 0x0000000000000000   r14 = 0x00000000fffe6d40
    r15 = 0x0000066e00000000   rip = 0x000000000022c920
    Found by: call frame info
 2  main.nexe!SelectableDataGrid::ProcessDefaultAction(Rml::Event&) [rocketSelectableDataGrid.h : 115 + 0x20]
    rbx = 0x00000000fd5ca4f8   rbp = 0x00000000fffeff80
    rsp = 0x00000000fffe6c40   r12 = 0x0000000000000002
    r13 = 0x64657463656c6573   r14 = 0x0000000000000003
    r15 = 0x0000066e00000000   rip = 0x0000000000132ca0
    Found by: call frame info
 3  main.nexe!Rml::EventDispatcher::DispatchEvent(Rml::Element*, Rml::EventId, std::__1::basic_string, std::__1::allocator > const&, chobo::flat_map, std::__1::allocator >, Rml::Variant, std::__1::less, std::__1::allocator > >, std::__1::vector, std::__1::allocator >, Rml::Variant>, std::__1::allocator, std::__1::allocator >, Rml::Variant> > > > const&, bool, bool, Rml::DefaultActionPhase) [EventDispatcher.cpp : 210 + 0x3a]
    rbx = 0x00000000fd41c5ac   rbp = 0x00000000fffeff80
    rsp = 0x00000000fffe6df0   r12 = 0x00000000fd5ca4f8
    r13 = 0x00000000fd41c5a0   r14 = 0x00000000fd41c5cc
    r15 = 0x0000066e00000000   rip = 0x0000000000286700
    Found by: call frame info
 4  main.nexe!Rml::Element::DispatchEvent(Rml::EventId, chobo::flat_map, std::__1::allocator >, Rml::Variant, std::__1::less, std::__1::allocator > >, std::__1::vector, std::__1::allocator >, Rml::Variant>, std::__1::allocator, std::__1::allocator >, Rml::Variant> > > > const&) [Element.cpp : 1256 + 0x59]
    rbx = 0x00000000feefc248   rbp = 0x00000000fffeff80
    rsp = 0x00000000fffe6ef0   r12 = 0x0000000000000000
    r13 = 0x0000000000000020   r14 = 0x00000000feefc248
    r15 = 0x0000066e00000000   rip = 0x000000000022d920
    Found by: call frame info
 5  main.nexe!Rocket_ProcessKeyInput(Keyboard::Key, bool) [Context.cpp : 753 + 0x20]
    rbx = 0x00000000feefc248   rbp = 0x00000000fffeff80
    rsp = 0x00000000fffe6f00   r12 = 0x0000000000000000
    r13 = 0x0000000000000020   r14 = 0x00000000feefc248
    r15 = 0x0000066e00000000   rip = 0x00000000001447a0
    Found by: call frame info
 6  main.nexe!VM::VMHandleSyscall(unsigned int, Util::Reader) [cg_draw.cpp : 135 + 0x2a]
    rbx = 0x0000000000000000   rbp = 0x00000000fffeff80
    rsp = 0x00000000fffe6fd0   r12 = 0x00000000fffefeb0
    r13 = 0x0000000000000064   r14 = 0x0000000000000000
    r15 = 0x0000066e00000000   rip = 0x0000000000028d00
    Found by: call frame info
 7  main.nexe!main [VMMain.cpp : 66 + 0x20]
    rbx = 0x00000000fd41c540   rbp = 0x00000000fffeff80
    rsp = 0x00000000fffefe70   r12 = 0x00000000fffefeb0
    r13 = 0x0000000000000064   r14 = 0x00000000fffefe90
    r15 = 0x0000066e00000000   rip = 0x00000000001d0d20
    Found by: call frame info
 8  main.nexe!_start [start.c : 68 + 0x39]
    rbx = 0x0000000000000024   rbp = 0x00000000fffeff80
    rsp = 0x00000000fffeff30   r12 = 0x00000000fffeffbc
    r13 = 0x00000000fffeffc8   r14 = 0x0000000000000024
    r15 = 0x0000066e00000000   rip = 0x000000000056a780
    Found by: call frame info

Loaded modules:
0x00020000 - 0x005affff  main.nexe  ???  (main)
```

**Comment by slipher** [comment] 2022-12-27 06:52
It might be useful to investigate #1988 or #2149 which also demonstrate possible bugs with RML tables and may be easier to reproduce.

**Comment by DolceTriade** [comment] 2022-12-27 06:57
This looks like the same issue as #2149

**Comment by DolceTriade** [comment] 2022-12-27 06:58
Closing this issue in favor of #2149

**Closed** 2022-12-27 06:57 UTC

**Comment by sweet235** [comment] 2022-12-27 08:51
These crashes might or might not be more likely to happen using my mod. I use a few additional .rml files to provide GUI for some custom votes, as detailed here: https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/compare/master...sweet235:unvanquished_src.dpkdir:map-testing
